### ISSUE TITLE
OSD

### ISSUE THREAD

**Issue by Kallepitch** [fpv-wtf/wtfos-configurator#101]
Hey guys,

have 2 Vistas and on one vista the OSD wont work. My google say "OSD WAITING". Maybe the UART config is the problem?
VTX is soldered on UART1.
What do I have to type in Betaflight CLI? set displayport_msp_serial = 5 ?

**Comment by stylesuxx** [comment]
Hey @Kallepitch - could you please ask your question (or read the doc, it is described there how to set it up from BF) in the [MSP OSD repo](https://github.com/bri3d/msp-osd), this is not really related to the configurator.
