### ISSUE TITLE
Download package diagnostics

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#106]
Every installed package should have an additional Menu "More".

The first option being available there is a "Download diagnostics" button which retrieves the packages logs and diagnostic files from a pre-determined location.

Further each package should be allowed to override the command in which the diagnostics/logs are being fetched in order to add more data.

**Comment by j005u** [comment]
So, to be a bit more specific, the default would be to zip up and provide the user with:
- /opt/etc/package-config/$packageName/*
- /blackbox/package-logs/$packageName/*

The former relates to user settings for the package and #7 as well as https://github.com/fpv-wtf/wtfos-package-config

The latter can populated by the package dinit unit's logfile property with a combination of the entware logrotate package to keep things sane. The package may optionally use `package-config` to determine their loglevel.

Additionally, packages could specify further things to include either by
- Providing an arbitary command that to create the archive
- Providing a list of glob patterns of files to include and commands to run and store the output of (unrd, getprop, what have you).

I don't think we should necessarily provide both interfaces, but I'm not sure which is the better approach.

Looking for feedback from @funneld and @bri3d as well.

**Comment by stylesuxx** [comment]
Having implemented part of the functionality now, I am not super happy about an optional arbitrary command per package to create the archive. I would much rather prefer an optional script to be called before the archive is generated:

I check the package for a *preDownloadDiagnosticsHook.sh* script, run that which dumps everything it needs to dump into the log folders and then the configurator proceeds to archive everything up.

In step 1 I would suggest we only pack up the configs and logs dirs and see if there is need for any custom stuff to be added before downloading the archive.

**Comment by j005u** [comment]
That makes sense, in hindsight the custom streaming archive command is a bit obtuse.

So, where do we stick preDownloadDiagnosticsHook.sh, is it another one-off folder in /opt/etc? Is it stored next to the package config stuff? Could we add it as a new script in the packages control section?

Also, considering we want to stream the archive out and not use disk space (because we may not have it), could the executable optionally be able to return a newline delimited list of additional paths rather than be forced to copy into the logs folder?

**Comment by stylesuxx** [comment]
Yes, I would even prefer a script that return paths.
Not sure where the file should live. I think it would make the most sense to have it next to the package config stuff.

**Comment by stylesuxx** [comment]
Alright, so this is technically implemented in #111, but ultimately there is no need for this - closed.
