### ISSUE TITLE
msp-osd_0.6.2_pigeon-glasses.ipk  - how to manually install .ipk?

### ISSUE THREAD

**Issue by AndKe** [fpv-wtf/wtfos-configurator#117]
new msp-osd is out ... how can I install it manually before the packet manager gets updated?

**Comment by stylesuxx** [comment]
It is already in the repo (https://repo.fpv.wtf/pigeon/) and should be pulled in with a regular update.

**Comment by AndKe** [comment]
sorry - I were expecting 0.6.2 for airside too . my bad,
