### ISSUE TITLE
WTFOS installation fails on Linux

### ISSUE THREAD

**Issue by AndKe** [fpv-wtf/wtfos-configurator#118]
After a successful rooting of air and groundside, WTFOS installation fail with:

"Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window."

Feel free to tell if I can help with additional information.

**Comment by j005u** [comment]
This could also be a udev permissions issue where Chromium is unable to claim the bulk endpoint.

chrome://device-log/ can offer some insights.

**Comment by AndKe** [comment]
Yes, not only by adb kill-server, but I checked for an process with "adb"
... failing to spot a reason, I tried Windows in vmware.

If you have a set of commands that do the same job, I can run them in
terminal and see what fails.
Also: my adb behaves well with both my phone and OculusQuest, so I dont
suspect this the be related to the adb itself.

**Comment by stylesuxx** [comment]
So, did you try to connect to goggle/air unit with your local adb? Does this work?

adb locally and through the browser are two different things. The local has to not be running, otherwise it will claim the device and the browsers adb will not be able to connect.

Also did you check the device-log as suggested by @j005u? This should also be evident when trying to connect with your local adb.

**Comment by howels** [comment]
@AndKe do you have appropriate udev rules? I noticed that the DJI device presents as a ADB device with different ID to other ADB devices, so it needed an extra udev rule (and user must be member of "plugdev" group:

```
$ cat /etc/udev/rules.d/51-dji-adb.rules 
# rules for DJI goggles
SUBSYSTEM=="usb", ATTR{idVendor}=="2ca3", ATTR{idProduct}=="001f", MODE="0660", GROUP="plugdev"
```

**Comment by AndKe** [comment]
Thank you!  - the udev rule was indeed needed.

As for solution:
The best solution would be to:
When the webpage detects Linux,   or is about to display the error - tell the user that a udev rule is needed, and suggest:

```
sudo printf "## rules for DJI goggles \nSUBSYSTEM=="usb", ATTR{idVendor}=="2ca3", ATTR{idProduct}=="001f", MODE="0660", GROUP="plugdev"" > /etc/udev/rules.d/51-dji-adb.rules

then reload rules:

sudo udevadm control --reload-rules && sudo udevadm trigger

```

This should also be in a wiki, maybe even just mentioned in README.md

I totally love the work you've done - what a beautiful webpage!  :)

**Comment by stylesuxx** [comment]
Interesting. Thank you @howels and thanks @AndKe for confirming. I am on Linux too and did not need such UDEV rule.
@howels feel free to add a page here in the Wiki, it should be public for edits.

However, I will add a disclaimer if Linux is detected.

TODO:
* [ ] Disclaimer if Linux is detected that u UDEV rule might be needed

**Comment by howels** [comment]
> Interesting. Thank you @howels for pointing out and thanks @AndKe for confirming. I am on Linux too and did not need such UDEV rule.
> @howels feel free to add a page here in the Wiki, it should be public for edits.
> 
> However, I will add a disclaimer if Linux is detected.
> 
> TODO:
> * [ ] Disclaimer if Linux is detected that a UDEV rule might be needed

I can't see a wiki, maybe it's private... And the UI itself is a better place to put the information I think. A Linux-specific note, similar to the warning to stop other ADB servers.

**Comment by stylesuxx** [comment]
Closing this in favor of #129
