### ISSUE TITLE
WTFOS

### ISSUE THREAD

**Issue by stubugs** [fpv-wtf/wtfos-configurator#119]
hi rooted air unit but try to install wtfos it keeps rebooting and wont install wtfos 
rooted and installed wtfos on other of my airunits no problems and vistas
rootng was successfull
![20220902_184522](https://user-images.githubusercontent.com/34194921/188210078-a0e4d0cf-47a6-4f59-ac38-4c41d33d81d9.jpg)

**Comment by j005u** [comment]
Try this: https://github.com/fpv-wtf/margerine/wiki/Troubleshooting#wtfos-install-stuck-in-a-loop

**Comment by stylesuxx** [comment]
@stubugs - any success with the link @j005u provided?

**Comment by stubugs** [comment]
I don't know what happened but no osd dji doesn't recognise the air unit any more so cannot update 
Its just good for video no osd any more

**Comment by stylesuxx** [comment]
What does the configurator say? Did you check the troubleshooting page?
Please provide a bit more info what exactly is happening.

**Comment by stubugs** [comment]
There is no osd when connect to dji assistant it sees dji air unit but comes up with a error 
Cannot load firmware list 4-10 please retry 
When connected to configuratir I can install and remove packages no problem 
![Uploading 20220911_022710.jpg…]()

**Comment by stubugs** [comment]
I've removed wtfos with configurator but still the same with dji assistant and no osd

**Comment by j005u** [comment]
@stubugs run "wtfos-remove-adb" in the cli after uninstalling wtfos, configurator will work again then. After that you should downgrade and upgrade again, a simple re-flash of the same version is not quaranteed to fix everything

@stylesuxx Eating my own words, but I guess we should eventually integrate the complete uninstall process. People don't read the README... Not sure if it'd just be part of the uninstall or...?

**Comment by stylesuxx** [comment]
> @stylesuxx Eating my own words, but I guess we should eventually integrate the complete uninstall process. People don't read the README... Not sure if it'd just be part of the uninstall or...?

So #21 - could be part of the uninstall, not sure if it makes sense to have a separate step for unlocking.

**Comment by stubugs** [comment]
cheers it worked for upgrading and down grading with dji assitant but still no osd think dji air unit is damaged cheers stu

**Comment by stylesuxx** [comment]
> cheers it worked for upgrading and down grading with dji assitant but still no osd think dji air unit is damaged cheers stu

You did go through the setup steps in Betaflight, right? https://github.com/fpv-wtf/msp-osd

**Comment by stubugs** [comment]
I use inav I have 3 air units if I plug other two in osd is all there when I plug that one in there's no osd

**Comment by stylesuxx** [comment]
Just to be clear, by OSD you mean the DJI OSD, oder msp-osd?

**Comment by stubugs** [comment]
I can't get either to work osd

**Comment by stylesuxx** [comment]
Well, that is really strange, and you are saying the OSD worked before rooting and installing WTFOS? Did you change anything else?

**Comment by stylesuxx** [comment]
@stubugs any more info on this?

**Comment by stubugs** [comment]
Nothing changed others I have rooted work fine just this one won't show osd it did before rooting

**Comment by stylesuxx** [comment]
I'd suggest you jump onto Discord for a troubleshooting session - closing down here since it's not a configurator issue.
