### ISSUE TITLE
Attempting Step 2...

### ISSUE THREAD

**Issue by Thomas72fpv** [fpv-wtf/wtfos-configurator#120]
Hello, i've tried to root my dji FPV goggles v2 but i stick to the step 2. Impossible to go further ! :(

Any idea ?

**Comment by stylesuxx** [comment]
Whats the exact error? Does it keep rebooting? Which firmware are you on?

**Comment by laivn** [comment]
I have the same problem, after set1 restarts, set2 stops after 10 attempts. 
firmware: 01.01.0606

**Comment by stylesuxx** [comment]
> I have the same problem, after set1 restarts, set2 stops after 10 attempts. firmware: 01.01.0606

How did you check your version, DIY mode or FPV mode? DIY mode is lying, and you might need to downgrade to 0606...

**Comment by laivn** [comment]
> > I have the same problem, after set1 restarts, set2 stops after 10 attempts. firmware: 01.01.0606
> 
> How did you check your version, DIY mode or FPV mode? DIY mode is lying, and you might need to downgrade to 0606...

Yes on the dji digital fpv system mode, dji Assistant shows 01.01.0606

**Comment by stylesuxx** [comment]
Yours is a V1 goggle?

**Comment by kewayseen** [comment]
I met the same problem,the rooting details:
00:20 Attempting Step 1...

00:24 - Found Device: GP150, Version: Unknown

00:24 Step 1 - Success! Rebooting...

00:44 Attempting Step 2...

02:16 Failed after 10 retries.
My goggles V2 firmware is 01.00.0606, (goggles and dji assistance are all displayed on this firmware version)
v0.7.2 - Trace ID: c0346b84-90d3-443c-9fa2-76de070b4712

**Comment by stylesuxx** [comment]
@kewayseen you checked the version in FPV mode, node in DJI mode, correct?

**Comment by kewayseen** [comment]
> @kewayseen您检查了 FPV 模式下的版本，DJI 模式下的节点，对吗？

yeah,I checked it, all display 01.00.0606

**Comment by stylesuxx** [comment]
> yeah,I checked it, all display 01.00.0606

For you it's a different error. You don't seem to be able to contact the CORS proxy. Can you please check if you can open https://cors.bubblesort.me

**Comment by kewayseen** [comment]
yeah,Yes, I can't open it

> > 是的，我检查了它，所有显示01.00.0606
> 
> 对您来说，这是一个不同的错误。您似乎无法联系 CORS 代理。你能检查一下你是否可以打开 https://cors.bubblesort.me

**Comment by stylesuxx** [comment]
> yeah,Yes, I can't open it

You are from China, right?

**Comment by kewayseen** [comment]
> > yeah,Yes, I can't open it
> 
> You are from China, right?

HAhahah,yes,呃呃

**Comment by kewayseen** [comment]
> > yeah,Yes, I can't open it
> 
> You are from China, right?

 Do i need a VPN ?but i dont have

**Comment by stylesuxx** [comment]
> Do i need a VPN ?but i dont have

Yeah, you might need one - at least for now. It seems our CORS proxy has been blocked by your government...

**Comment by kewayseen** [comment]
Well, I want to figure out a way, thank you for the answer

**Comment by stylesuxx** [comment]
@kewayseen can you please post a screenshot of how https://cors.bubblesort.me looks for you? I now tested with different block checkers and my VPN within China and have no issues whatsoever to reach the CORS proxy. I am wondering if this issue is just a problem on your end.

**Comment by kewayseen** [comment]
Hmmm, I borrowed a VPN from a friend and have been successfully rooted.
![666](https://user-images.githubusercontent.com/88956657/190887890-dc10b5a7-b6a6-4d26-955f-83514024aa04.png)

**Comment by stylesuxx** [comment]
@kewayseen Interesting, but the screenshot shows you having access to the CORS Proxy - or is that via VPN? Am a bit confused.

**Comment by kewayseen** [comment]
> @kewayseen有趣，但屏幕截图显示您可以访问CORS代理 - 还是通过VPN？我有点困惑。
Yes, via a VPN, I can't open this page without a VPN

**Comment by stylesuxx** [comment]
@kewayseen alright - thanks for confirmation.

**Comment by SQuiDFPV** [comment]
I had to refresh Goggle update to make the Root start step 1. It passed step 1, then step 2 it failed after 10 tries. now step 1 will randomly complete but always fails step 2. ?? help

**Comment by stylesuxx** [comment]
@SQuiDFPV sounds to me as if some other program was trying to claim your device during the root process.

No need to re-do the root process once it is rooted and wtfOS is installed.

Regarding the waiting for OSD message only showing from time to time, is it possible that the bind button on your goggle is stuck sometimes? This would make it boot in the 2nd slot in which wtfOS is not installed. Once the message shows though and you don't get the OSD when the vista is plugged in, this is a pretty clear indicator that the FC is not configured properly.

I would suggest you jump onto discord for a troubleshooting session.

**Comment by SQuiDFPV** [comment]
@stylesuxx  thanks man! i just fixed it all though. Did a second air unit all worked perfectly. i then checked my MSP ports on my other quad, I accidentally had 2 MSP ports set (1 doing nothing) and i chose the wrong one.. once i turned off that MSP uart and then set it to uart 1 (0 in cli) it worked as it should..
so i learnt if it says Waiting for OSD.. you are on the wrong MSP port :) 
MY MISTAKE but all fixed and seems to be working a treat. love your work!

**Comment by stylesuxx** [comment]
Great, happy you got it working.

I will close this issue down, since it is now a big mix of different - partially solved issuess.

@kewayseen your issue has been extracted to #149 
@laivn and @Thomas72fpv does your issue still persist? If so I would suggest you jump onto Discord for a debugging session
