### ISSUE TITLE
e3 on ota unlock means the user needs to go downgrade

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#122]
When we get an e3 response on the ota unlock there's no reason to retry and we can tell the user: "The firmware on your device is too new. Please connect your device to the DJI FPV Assistant 2 in DIY mode and downgrade your device to V01.01.06060. If no downgrade is offered by Assistant then your Goggles have antirollback value 1 or greater and cannot currently be downgraded."

**Comment by stylesuxx** [comment]
Can you give me a rundown on how I could provoke the Error? I would need to lock my google again, update it to with DJI assistant, right? This is also only an issue with the goggles, both V1 and V2, not any of the air-units, correct?

**Comment by j005u** [comment]
Correct, only the V2 Goggles have this issue currently.

Update to V01.02.0020 via DH in FPV Drone mode to prevent OTA (doesn't need to be fresh) and trigger the E3, but be able to easily downgrade to V01.01.0606 in DIY mode via assistant.

**Comment by cqzone** [comment]
Is it charged to update to V01.02.0020 through DH

**Comment by j005u** [comment]
@cqzone this was instructions for stylesuxx to be able to replicate the error. Users shouldn't do this.
