### ISSUE TITLE
Linux: Warning UDEV rule

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#129]
* [x] Disclaimer if Linux is detected that a UDEV rule might be needed

```
$ cat /etc/udev/rules.d/51-dji-adb.rules 
# rules for DJI goggles
SUBSYSTEM=="usb", ATTR{idVendor}=="2ca3", ATTR{idProduct}=="001f", MODE="0660", GROUP="plugdev"
```

```
sudo printf "## rules for DJI goggles \nSUBSYSTEM==\"usb\", ATTR{idVendor}==\"2ca3\", ATTR{idProduct}==\"001f\", MODE=\"0660\", GROUP=\"plugdev\"" > /etc/udev/rules.d/51-dji-adb.rules

then reload rules:

sudo udevadm control --reload-rules && sudo udevadm trigger
```

Extracted from #118

**Comment by andersix** [comment]
Arch Linux user here.
Udev rules go in a diff spot, and don't have/want plugdev group.

This is what I added to get a udev rule in place for the Goggles:

Created file as root. i.e.: "sudo vi /usr/lib/udev/rules.d/51-dji-adb.rules" with the contents below:
Then reloaded rules as above in first post of this thread.

```
[:~] % cat /usr/lib/udev/rules.d/51-dji-adb.rules
# rules for DJI goggles
SUBSYSTEM=="usb", ATTR{idVendor}=="2ca3", ATTR{idProduct}=="001f", MODE="0666"
```

Note: I had to unplug goggles after successful root and after successful install.

**Comment by stylesuxx** [comment]
Great, thanks @andersix - I guess Arch users will be able to extrapolate from the general given information in the warning message
