### ISSUE TITLE
opkg usage needs a lock

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#13]
When switching pages fast it's possible to trigger an opkg update in the background and then get errors for example on the wtfos uninstall screen, because opkg-s lockfile is still open by the previous process.

**Comment by j005u** [comment]
Quick update: I've seen this more recently, possibly due to various async loads such as update checks?

**Comment by stylesuxx** [comment]
Yes, that could very well be the case. I will see if I can refactor opkg usage into a proper queue. Alternatively check for lock beforehand and fail - I think I would prefer the queue though.
