### ISSUE TITLE
Rooting is not starting (Even when COM is paired)

### ISSUE THREAD

**Issue by Mantofka** [fpv-wtf/wtfos-configurator#145]
So I tried to root a:
DJI Goggles V2, that has 1.00.0606 version. Unfortunately, every time I press "Root Device" button, prompt appears to pick a COM. However, nothing else is happening.

Using this URL: https://testing.fpv.wtf/root

**Comment by stylesuxx** [comment]
So there is no device to select? Which browser are you using?

**Comment by Mantofka** [comment]
No, the device appears. However, when I click on it and press "Connect" button - nothing happens.
That a Google Chrome

**Comment by stylesuxx** [comment]
Are you in DIY mode? Please check version with DJI Assistant.

**Comment by Mantofka** [comment]
Yes, I am currently in DJI Digital FPV system mode. The DJI assistant says that I am on version 1.00.0606

**Comment by stylesuxx** [comment]
Please check the version in drone mode.

**Comment by Mantofka** [comment]
The same.

**Comment by Mantofka** [comment]
Case/issue can be set to 'Closed' - devices has been rooted. Do not know what magic happened.
