### ISSUE TITLE
Just two Elements showing in OSD

### ISSUE THREAD

**Issue by GlnSevi** [fpv-wtf/wtfos-configurator#147]
Hey,
I flashed my goggles and my Air Unit. I installed the OSD and set my FC to the right Serial. When I start my Googles and power up my drone i just see two elements. 
![ba36b9d6-ad83-4c54-8cb4-fc8fe1ff9533](https://user-images.githubusercontent.com/90464210/191604296-ed231e73-68ba-4fb4-9c26-0dd734496ba4.jpg)

**Comment by stylesuxx** [comment]
Re-flashing the FC firmware seems to have resolved this issues.
