### ISSUE TITLE
Root Caddx Vista Air unit hangs

### ISSUE THREAD

**Issue by slowjun1** [fpv-wtf/wtfos-configurator#152]
Getting this issue while updating my caddx Airunit. it wont continue it just hang. Root Button does not proceed when you press it.
nothing happens. then when you try to click root device the connect device will open then the airunit will show.then when you try to remove the cable and plug back in, it will auto root then will show the below logs. and will not continue. tried tp changed cables resulted to the same error.s

30:01 Device went away...

30:12 Device came back...

30:15 Attempting Step 1...

30:36 Failed after 10 retries.

**Comment by stylesuxx** [comment]
Which OS and Browser. Dies the caddy vista connect to the DJI assistant?

**Comment by slowjun1** [comment]
Solved, just make sure that DJI app is not open during rooting of DJI Air unit.
