### ISSUE TITLE
WTF OS install freezes on 'Entware installing'

### ISSUE THREAD

**Issue by relentlesstech73** [fpv-wtf/wtfos-configurator#153]
Had no issues rooting my Air Unit, but it is frozen on the 'installing entware' part of the WTF OS install - I have already almost completely drained a 6s 1500mah lipo waiting! My Vista took less than 3 minutes, but this Air Unit is just not liking the install.

**Comment by stylesuxx** [comment]
Please check the output in the browsers debug console. Might find more info there.

**Comment by relentlesstech73** [comment]
I have this error in the debug log:

Access to fetch at 'https://github.com/fpv-wtf/wtfos-healthchecks/releases/latest/download/healthchecks.tar.gz?cachebust=0.044571828902029154' from origin 'https://fpv.wtf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by relentlesstech73** [comment]
Issue has resolved itself after restarting computer, and clearing browser cache
