### ISSUE TITLE
Linking to packages / detailed package view

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#16]
It would be nice to have the ability to link to a package screen in the package manager from an external website.

In the simple version this could simply be solved by having the search term be part of the URL.
In a more advance version we could have a package detail view that pulls in the github link, perhaps the README and possibly more.

Whatever we end up doing, the URL should be stable.

**Comment by stylesuxx** [comment]
I am not entirely sure that I understand this correctly:
* What would happen if you follow the link but have no device attached?
* What would be the upside of that in comparison to just linking to a URL that could be provided in the packages control file?

**Comment by j005u** [comment]
Ah good point, I didn't think of the situation when no device is connected. I guess it could just give you the normal please connect your device(/followed by loading packages) state since we let opkg itself take care of the package metadata, no point in doubling that functionality.

The detailed view is nice-to-have at some future point I think, in that regard the link in package metadata is absolutely sufficient.

It would still be nice if projects could link from their README/website into package search with the name pre-filled, that way it's a 2 click install experience.

**Comment by stylesuxx** [comment]
Ok, yeah - makes sense to me.

**Comment by stylesuxx** [comment]
This is basically now done with v2.0.0 - closed.
