### ISSUE TITLE
Unify rooting via webusb instead of webserial

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#163]
As suggested by @d3vl-jack the [webserial polyfill for webusb](https://github.com/google/web-serial-polyfill) could be used instead of webserial. This would allow us to have the user only interact once with the device selection dialog for both rooting and wtfOS related things.

**Comment by j005u** [comment]
This could also allow us to determine rooted state and evolve the UI to hold the users hand more.

**Comment by stylesuxx** [comment]
Ah yeah, right - now I can remember why I did not use it in the first place - this has actually been an issue with my other configurator too: there are no [remove and connect listeners](https://github.com/google/web-serial-polyfill/issues/20), I submitted a patch which was [not merged](https://github.com/google/web-serial-polyfill/pull/22) and the maintainer did not yet implement his intended clean solution.

We could technically use my [temporary fix PR](https://github.com/stylesuxx/web-serial-polyfill#temporary-fix)...

**Comment by stylesuxx** [comment]
The ```web-serial-polyfill``` does not want to cooperate if web serial itself is available, I simply can't claim the device, even with them demo.html provided in the repo I end up getting an error when attempting to open the device:

```
serial.ts:311 Uncaught (in promise) Error: Error setting up device: NetworkError: Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface.
    at SerialPort.open (serial.ts:311:13)
    at async demo.html:64:7
```

**Comment by j005u** [comment]
Presumably you made sure nothing else is claiming the iface? Anything in device-logs? Or maybe some udev bullshit?

**Comment by stylesuxx** [comment]
Yes, I did check that nothing else is claiming the interface. device-logs seem fine, nothing out of the ordinary. I am [not the only one having this "issue"](https://github.com/google/web-serial-polyfill/issues/14) though.

You could cross check by running the demo.html from the [webserial polyfill repo](https://github.com/google/web-serial-polyfill).

**Comment by j005u** [comment]
Same, with "Interface 4 uses driver "usbser" instead of WinUSB." in device-log.

So I guess without having the user involve Zadiq, we're boned? Don't want to do that, as then Assistant would break.

**Comment by stylesuxx** [comment]
Yup, I see it the same way. I don't want to involve external (non cross platform) tools at all.

**Comment by D3VL-Jack** [comment]
`Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface` 
Is the exact same error I was seeing when working with the BULK interface, @j005u is absolutely right about winusb driver
