### ISSUE TITLE
DJI Googles V1 Not recognized with Google Chrom or Edge

### ISSUE THREAD

**Issue by Nanocastica** [fpv-wtf/wtfos-configurator#166]
I cannot connect Googles to the WTFOS webpage.
Googles are connected to the PC without any problems, DJI FPV Assistant recognizes them immediately, however google chrome not.
I tried everything, different browsers, restarts .... many different cables ... etc.

Please any advice ?

![image](https://user-images.githubusercontent.com/84510286/192850145-8168b255-a85b-4bb6-bcce-780cbd10711b.png)
![image](https://user-images.githubusercontent.com/84510286/192850292-4df16af6-94c4-4a36-a502-962b307a7a15.png)

![image](https://user-images.githubusercontent.com/84510286/192850509-a1a768ff-00db-489a-9021-2a89c76c2bee.png)

**Comment by stylesuxx** [comment]
You are on the /root page?

**Comment by Nanocastica** [comment]
No WTFOS install page, I already /root the goggles, but then I reboot them and no way to connect them back to the WTFOS page, no idea where is the problem.

**Comment by stylesuxx** [comment]
If they are not showing on the Home page, then they are not rooted yet. Please try rooting them again and post output here. Also please check firmware version and make sure that all DJI assistants are closed.

**Comment by Nanocastica** [comment]
Oh OK, it works now like a charm, problem was that i shouldn't power off the goggles immediately after first rooting. I thought Goggles were already rooted but they were not so you were correct THX.
Now everything worked just fine and I installed all into the goggles.

![Snímka obrazovky 2022-09-28 204943](https://user-images.githubusercontent.com/84510286/192864935-ee5451e3-0e94-4b71-b013-dd9da2f234ec.jpg)

**Comment by stylesuxx** [comment]
Awesome, closing down here.
