### ISSUE TITLE
Add fallback for cases in which temperature can not be read

### ISSUE THREAD

**Issue by PaulFPV** [fpv-wtf/wtfos-configurator#168]
All done - your device has been successfully rooted!

...but then I cannot connect to that device.

I successfully rooted and added MSP-OSD on 1 goggles and 2 vistas but on the 3rd I had this problem. I tried may times but the problem remains the same. I cannot connect after the rooting. I tried to kill adb server but it doesn't fix the problem.

Trace ID
eb34e881-6cb0-46e6-b25d-f48a8b258e66

I don't have the Trace ID of the first run so this is of the last test: refresh firmware from DJI assistant and rooting again.

**Comment by stylesuxx** [comment]
Does the device show up in the selection box when you click the connect button, or is it not there at all.
It it is not there at all, please try re-rooting.

**Comment by PaulFPV** [comment]
Yes it's available in the selection box, but when I try to connect I just get this message:

"Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window."

killing the adb server doesn't solve it and I have just that tab open (and if I connect another caddx vista I get connected no problem in the same tab.

Now I remember that, at the first rooting run, I had the message about the partition that needed to be fixed and I let it do it... maybe it's related. How can I check it manually? Is there a way to remove everything to start fresh (as I noticed, flashing the firmware from the DJI assistant doesn't clean the device)

**Comment by stylesuxx** [comment]
If it had to switch slots, then you need to re-root (the text should have said so). So please try re-rooting. If this does not work, jump on Discord for a troubleshooting session please.

**Comment by PaulFPV** [comment]
Yep... re-rooted at least 10 times while doing my tests.. no change on that device.

When I go home this evening I'll go for the troubleshooting session on Discord.

thanks

**Comment by Kuchenz** [comment]
iv got a problöem like that too.... after root it shows up in device manager but i cant connect via browser, only to root again

**Comment by Kuchenz** [comment]
another usb port on my pc fixed a problem like that

**Comment by stylesuxx** [comment]
@PaulFPV I am not sure if this got sorted on discord?

**Comment by Kuchenz** [comment]
Yes, a different USB Port And reroot solved the Problem, thanks for asking
👍

Have a nice day
Lars

Chris ***@***.***> schrieb am So., 2. Okt. 2022, 13:15:

**Comment by stylesuxx** [comment]
@Kuchenz thank you, but I was asking the original poster ;-)

**Comment by Kuchenz** [comment]
saw it a sec later :D

**Comment by stylesuxx** [comment]
It turns out that on this Vista the temp readings return nothing (on temp 0-4):

```
cat /sys/devices/platform/soc/f0a00000.apb/f0a71000.omc/temp1
```

The temperature is used as an indicator that ADB is working correctly, that's why the connection seemed to fail. Re-connecting then results in "Device claimed", since the device is actually claimed - by us, just waiting for the temp reading to return something.

I can add a failsafe here, assuming that after 5 "failed" temp readings the device is actually ready to operate...
