### ISSUE TITLE
Filter out "system" packages by default in package view

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#172]
It would be nice to be able to filter out "system" packages that aren't useful to end users from the default view.

We can use the 'Section' meta, but what value? From entware there's "devel" that is somewhat appropriate, but not necessarily. "system"? "wtfos"?

In a sense the Entware repo should itself as a whole be considered under this category.

**Comment by stylesuxx** [comment]
Well, we already filter by repo, so entware is not shown by default anyway, only when filters are adjusted. I can also remove it completely from the display - this one would be pretty easy.

And yeah, filtering packages out by Section is definitely an option - I'd go with "system", seems more specific.

**Comment by stylesuxx** [comment]
@j005u I have been thinking about this a bit more - what do you think about a "Category" filter with the following options (for now):
* All
* All (except system) (Default)

This way we can extend this filter, have some sane defaults and the user still has the option to see all if he wants to?

**Comment by j005u** [comment]
I'm fine with the above. I'll do a pass on my packages to add the section (and README's) in right now.

Maybe we can ship it with V2.0.0?

**Comment by j005u** [comment]
I added HomePage and Section to my packages as appropriate, but since I didn't bump the versions I had to uninstall and re-install to get them to show up. I would've thought this goes based on just the index, but I guess not. Didn't feel worth making people update though.
