### ISSUE TITLE
DigiView

### ISSUE THREAD

**Issue by HARLOCKTAG** [fpv-wtf/wtfos-configurator#177]
Dopo root non trasmette più uscita video e Digiview non vede più immagini

**Comment by stylesuxx** [comment]
English please.

**Comment by HARLOCKTAG** [comment]
After root no longer transmits video output and Digiview no longer sees images

**Comment by stylesuxx** [comment]
Not really a configurator issue. Try using https://widefpv.com instead.
If you need more help please jump on our discord server.

**Comment by j005u** [comment]
I'll note that after some more research we haven't been able to reproduce and issue on wtfos. If there was anything it was really early on.

Usually it's a matter of drivers. widefpv has instructions for installing drivers with Zadiq. Depending on the USB port you plug into, a re-install is expected.
