### ISSUE TITLE
Cannot connect to DJI Fly app

### ISSUE THREAD

**Issue by teeraash** [fpv-wtf/wtfos-configurator#182]
After rooted my DJI goggles V2 cannot connect to dji fly.  If this is an issue then it can affects people who using this rooted goggles with DJI FPY or Avata drones.  Anyone experiencing this problem.  What should be done to get around this problem?

**Comment by stylesuxx** [comment]
Yes, the same way you can't connect to DJI Assistant with rooted goggles. Remove wtfOS and you should be able to connect again. If you fly Avata drone then the root hack will not do anything for you anyway... Or what is your exact use case here?

**Comment by stylesuxx** [comment]
Closed, not really configurator related.
