### ISSUE TITLE
Problem rooting vista kit

### ISSUE THREAD

**Issue by Thongjaj** [fpv-wtf/wtfos-configurator#185]
While rooting Vista kit
00:02 Attempting Step 1...

00:24 - Found Device: LT150, Version: 01.00.0606

00:24 Step 1 - Success! Rebooting...

00:44 Attempting Step 2...

01:22 Failed after 10 retries.

this happened

v1.0.0 - Trace ID: 7bedd74f-bae2-4b3e-8273-5c345d0f21ae

Please help

**Comment by Thongjaj** [comment]
I have tried rotting on the laptop, another Vista kit, new usb cable, no other software is running, all the same result, any other suggestions please.

**Comment by stylesuxx** [comment]
You can connect to DJI Assistant, right? See what version is showed there and try refreshing to 0606
I assume you could root your goggles?

**Comment by Thongjaj** [comment]
The price of getting old..... I did not activate the airunit.... well problem solved,  it is me.  thanks for your help.
