### ISSUE TITLE
Firmware upgrade after rooting the air unit lite (Caddx vista)

### ISSUE THREAD

**Issue by Nimrasol** [fpv-wtf/wtfos-configurator#186]
**Problem:**
As I rooted my air unite lite (Caddx Vista) the FW version 01.00.0600 was on the device instead of version 01.00.0606. My goggles v1 has the correct FW version 01.00.0606. Everything is working as expected but I get on every start up of my air unit lite a nasty firmware mismatch notification in the goggles. 

**Try to solve:**
I  uninstalled the WTFOS and connected the air unite lite with DJI Assistant 2 again. It connects  successful but with the assistant it's not possible to upgrade / downgrade the FW. The assistant states "Cannot find any Firmware". 

**Question:**
What can I do to upgrade the DJI FW with the DJI Assistant 2 (ore any other solution) on my air unite lite in order to get rid of the FW mismatch notification?

**Comment by stylesuxx** [comment]
Did you also run the adb remove command?

```
wtfos-remove-adb
reboot
```

**Comment by Nimrasol** [comment]
This was exactly the problem. Thank you so much! This was a quick fix, nice 💯
