### ISSUE TITLE
Installed on V1's and Air Unit, config'd BF, no OSD. Just a message reading "WAITING OSD"?

### ISSUE THREAD

**Issue by JamIceland** [fpv-wtf/wtfos-configurator#188]
Not really sure what's going on here. I followed the directions, I've checked the updater on the goggles (V1's) and the air unit and everything is installed correctly and up to date. 

I've got betaflight configured per the directions, still nothing.

**Comment by stylesuxx** [comment]
High chances are that your Betaflight is in fact not configured correctly. Please join Discord for a troubleshooting session.

**Comment by stylesuxx** [comment]
@JamIceland any update on this, otherwise I will close the issue...

**Comment by JamIceland** [comment]
Turned out to be some random BF issue. Ended up flashing and now it works.
