### ISSUE TITLE
problem rooting

### ISSUE THREAD

**Issue by NoobRescuer** [fpv-wtf/wtfos-configurator#202]
00:01 Attempting Step 1...

00:43 - Found Device: GP150, Version: 01.00.0606

00:43 Step 1 - Success! Rebooting...

01:05 Attempting Step 2...

02:10 Failed after 10 retries.

v1.0.0 - Trace ID: f207496c-6d08-4641-b8cd-c03f2ab41cd5

**Comment by vipfpv** [comment]
Same problem:
00:04 Attempting Step 1...

00:18 - Found Device: GL150, Version: 01.00.0606

00:18 Step 1 - Success! Rebooting...

00:35 Attempting Step 2...

01:15 Failed after 10 retries.

v1.0.0 - Trace ID: 4f933469-99a4-4e6d-a5c0-8b88c03c9ccc

**Comment by 1smj2** [comment]
Same problem.  Just got my V2 goggles from Amazon with the 0606 firmware and unable to get past step 2.
