### ISSUE TITLE
Menus are not working every time

### ISSUE THREAD

**Issue by Anton33455** [fpv-wtf/wtfos-configurator#204]
Menu in the google will only let me move forwarded but not back.  Randomly it works but most of the time I have to power cycle the goggles to get out of menu

**Comment by stylesuxx** [comment]
This is not a configurator issue. Are you sure it's not just your joystick that is stuck? You only have this issue after rooting? I would suggest you join discord for a troubleshooting session.

**Comment by Anton33455** [comment]
This is only happening after the rooting and upgrading to wtfOS.  to go back it's not joystick but back button.  For the most part it  does not work on WTFOS

**Comment by stylesuxx** [comment]
So uninstalling wtfOS makes the back button work again?

**Comment by bri3d** [comment]
What version of the firmware are you on? On some versions like 600 and 604 this is expected. You need to be on 606 DIY Mode for WTFOS to work in an expected way

**Comment by Anton33455** [comment]
How do i pick a version.  I was using the configurator, web based.  Is
there a link to configurator which will install latest OS?

**Comment by stylesuxx** [comment]
The configurator will install the latest version of wtfOS. What @bri3d is asking, is the firmware version that were on the goggles when you rooted them.
You can update that via DJI Assistant but you will have to [remove wtfOS first](https://github.com/fpv-wtf/wtfos#uninstalling) in order for DJI Assistant to connect.

**Comment by j005u** [comment]
> The configurator will install the latest version of wtfOS. What @bri3d is asking, is the firmware version that were on the goggles when you rooted them. You can update that via DJI Assistant but you will have to [remove wtfOS first](https://github.com/fpv-wtf/wtfos#uninstalling) in order for DJI Assistant to connect.

It might be just better to tell users to uninstall to be sure, but afaik 0604 is a V2 firmware only and you don't need to uninstall on V2. Reason being V2s don't require the startup patches to enable adb that disable configurator. Specifically changing mp_state via a bindmount.

**Comment by stylesuxx** [comment]
@Anton33455 any update on this, otherwise I will close this issue.

**Comment by stylesuxx** [comment]
Closing for the lack of activity. Feel free to re-open with more information.
