### ISSUE TITLE
root is stuck in "00:03 Attempting Step 1..." forever

### ISSUE THREAD

**Issue by guy111a** [fpv-wtf/wtfos-configurator#207]
Hello 

i followed this video : https://www.youtube.com/watch?v=0Z2GkYkKnmk

when connecting the goggles i hear the sound that the windows "see" them, i go to root, press the blue line, select com 5 ( only goggles are connected to the computer ) and get this line.

At some point i disconnected the usb-c cable and then i get more messages about googles went away and came back and stuff ... at some point i got "All done - your device has been successfully rooted.." but when going to HOME and trying to connect the goggles, there is nothing in the list.

Windows 11, tried edge, chrome.
goggles are on 606 ver. 
tried several cables but i have only one laptop to use.

00:03 Attempting Step 1... is now about 16 min.

i disconnected and connected to the plane, the system is working fine. but i cannot install the wtf os from the time.

Thank you
![WhatsApp Image 2022-10-20 at 18 04 56](https://user-images.githubusercontent.com/40334314/196997891-7faf36b9-55ab-4336-9d52-089e3bf319aa.jpg)
![WhatsApp Image 2022-10-20 at 18 04 49](https://user-images.githubusercontent.com/40334314/196997897-90b3478d-cf02-421b-a388-f753b4a13a51.jpg)

Guy

**Comment by stylesuxx** [comment]
Your connection is super flaky - I'd try a different USB port/cable. Also make sure that you are on the correct version, it does not seem that you are on 0606. Connect to DJI Assistant and downgrade to this version. Also make sure you are in DIY mode.

**Comment by guy111a** [comment]
Thank you for reply.

I am on 0606. this is for sure.

The cable is the same i use to configure the quad. it is a totally new high quality cable .. i also use it to transfer big files to the phone and to fast charge it. Any way, to be on the safe side, i DID try 2 more cables, all gave the same result.

I assum this is not the  issue.

![image](https://user-images.githubusercontent.com/40334314/197000578-968bfc68-07d2-4265-9521-81cbf73daae0.png)

**Comment by guy111a** [comment]
ok, from this video : https://www.youtube.com/watch?v=quJ5fGhXyXM @04:04 

I see that his air unit is detected as serial device. my goggles are identified as "bulk device" 
I do have the dji assistant insdtalled. 

if it helps.

Thank you

**Comment by stylesuxx** [comment]
You are not on 0606 - please upgrade to 0606...

**Comment by guy111a** [comment]
well ... i will re upgrade since as you may be able to see in the attached photo made from my goggles .. the number is 0606.

**Comment by guy111a** [comment]
b.t.w - the vista worked fine. without any issues ..  so the cables are ok.

**Comment by stylesuxx** [comment]
The screenshot you posted of DJI Asssistant clearly shows current version V00.00.0000 and shows you an option to upgrade to 0606. Please do so. If it still does not work afterwards we can look into other options.

**Comment by guy111a** [comment]
Yes sir. I already did it. The process went better. I removed the wtfos and reinstalled it. Now stuck with both sides installed but no osd on screen. This is another issue and looks like i did not do something i had too rather a technical issue Thank you. Guy AOn 20 Oct 2022, at 23:54, Chris ***@***.***> wrote:﻿
The screenshot you posted of DJI Asssistant clearly shows current version V00.00.0000 and shows you an option to upgrade to 0606. Please do so. If it still does not work afterwards we can look into other options.

**Comment by guy111a** [comment]
I do not know how it is possible but it appears that the goggles where on a version. While showing no versions at all

reflushed using dji assistant and issue fixed.
