### ISSUE TITLE
Provide functionality to lock the device again

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#21]
See https://github.com/stylesuxx/dji-hd-fpv-configurator/issues/4#issuecomment-1122411358

**Comment by stylesuxx** [comment]
@j005u so you don't think there should be functionality in the configurator to lock the device? I thought it might be useful in case people want to send it in for warranty repair - I would assume it'll be rejected when rooting is spotted. Or as you mention to make it flashable via Assistant...

**Comment by j005u** [comment]
You can add it if you want to, I just don't think it's critical.

**Comment by stylesuxx** [comment]
This can be easily done by removing wtfOS and then removing ADB. No need to have this in the configurator. Closed.
