### ISSUE TITLE
FPV Air-unit don't connect after root

### ISSUE THREAD

**Issue by staffan-w** [fpv-wtf/wtfos-configurator#210]
Rooted and installed everything on the goggles, worked great!
Rooted the air-unit, but when I was going to install wtfos first it complained on adb server, and then it said the unit was'nt supported.
Now I cant connect the air-unit to the wtfos paige or to the dji-assistant 2.
I also tried to remove wtfos from the goggles. It seemed to work but now I cant change the output settings and also not do the output power hack to get 700mW. So now Im stuck with 25mW and just 4 channels to use. This is not good Im afraid.
Please help me!

**Comment by stylesuxx** [comment]
I am not sure which problem you are trying to solve right now. I would recommend you install wtfOS on both, goggle and air unit and we will move on from there.

**Comment by stylesuxx** [comment]
@staffan-w any update on this?

**Comment by staffan-w** [comment]
Hi!
Thanks for asking!
Yes, I tried a couple of times but then I removed the SD-card and
everything worked as a charm!
Didn't thought that would be an issue!


Den lör 29 okt. 2022 18:12Chris ***@***.***> skrev:

**Comment by stylesuxx** [comment]
Interesting, thanks for the info. Will keep that in mind for the future. Closing this issue.
