### ISSUE TITLE
please power cycle and try again

### ISSUE THREAD

**Issue by DimitriyUmniy** [fpv-wtf/wtfos-configurator#212]
help solve the problem!  can't get root permanent writes

00:03 Attempting Step 1...

00:28 - Found Device: GP150, Version: 01.00.0606

00:28 Step 1 - Success! Rebooting...

01:30 Aborted! Device did not reboot in time, please power cycle and try again.

tried on different computers

**Comment by stylesuxx** [comment]
Make sure that nothing else is capturing the device in between. No other configurators running, no DJI Assistant or anything else that might be claiming the device (Cura is known to do that).

**Comment by Smolnyj** [comment]
> tried on different computers

What operating system do you have?

**Comment by DimitriyUmniy** [comment]
> > пробовал на разных компах
> 
> Какая у вас операционная система?

8.1 x64

**Comment by stylesuxx** [comment]
And you made sure no other program is running that could be claiming your device? Please also try on different computer.

**Comment by DimitriyUmniy** [comment]
> И вы убедились, что никакая другая программа не запущена, которая может претендовать на ваше устройство? Также попробуйте на другом компьютере.

tried on win 7. uninstalled DJI Assistant but it didn't help

**Comment by stylesuxx** [comment]
Yeah, win 7 is EOL. Pleas try on an up to date computer ;-)

**Comment by PogCarr** [comment]
I was having the same problem. Finally, when it said to power cycle the goggles, is unplugged the battery instead of using the button on the battery to power it down then back up. That got it. ymmv
![image](https://user-images.githubusercontent.com/4399486/199777087-67e0bf28-aa37-4c4d-abb9-99a23407605e.png)

**Comment by Smolnyj** [comment]
> > Какая у вас операционная система?
> 
> 8.1 x64

На Win7 x32 x64 аналогичная проблема. Если на тот же комп поставить Win10 - всё работает нормально, я проверил.
Вероятно, Win8 имеет ту же самую беду...

**Comment by DimitriyUmniy** [comment]
> > > Какая у вас операционная система?
> > 
> > 
> > 8,1x64
> 
> На Win7 x32 x64 аналогичная проблема. Если на тот же комп поставить Win10 - всё работает нормально, я заразился. Кроме того, Win8 имеет ту же национальную беду...

Thanks!  Everything went well on windows 10.

**Comment by DimitriyUmniy** [comment]
> Да, Win 7 - это EOL. Пожалуйста, попробуйте на современном компьютере ;-)

Thanks!  Everything went well on windows 10.) ))
