### ISSUE TITLE
Make uninstall wtfos run wtfos-remove-adb

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#214]
I was wrong. People don't read the README and this is causing too many questions.

I think we should make wtfos uninstall run wtfos-remove-adb (if present).

**Comment by stylesuxx** [comment]
Hmm, I am checking if the file exists `/system/bin/wtfos-remove-adb` and am only then showing the message and attempting the removal.

The question should then rather be, why is this script present on a V2 goggle...

**Comment by j005u** [comment]
Roger, must be a problem on my end then.

**Comment by stylesuxx** [comment]
Could you find the issue?

**Comment by stylesuxx** [comment]
Short follow up - @j005u can we close this again?

**Comment by j005u** [comment]
So sorry for leaving this dangling. Yes, the problem is on my end, closing.
