### ISSUE TITLE
After successfully rooting, goggles (Com port) don't show up on Com port popup window,

### ISSUE THREAD

**Issue by RaosFPV** [fpv-wtf/wtfos-configurator#224]
After successfully rooting, I can't connect the gogles to wtfos, they don't show up on comport,

**Comment by RaosFPV** [comment]
Slot 1 is corrupt, can reflash from Slot 2
Slot 2 active, wtfos should be installed in Slot 1


I managed to connect on another USB port on the my computer, but the name of the connection was written "pigeon?"
and then I got a message, something like Slot 1 is corrupt, can reflash and with the possibility of repair, after restoring the port a message appeared in, COM port options I can choose new port named pigeon-pared but massagi is 
-Slot 2 active, wtfos should be installed in Slot 1

**Comment by stylesuxx** [comment]
So, did you click the "Attempt fix" button?

**Comment by RaosFPV** [comment]
yes, I am, and after that I got a message Slot 2 active, wtfos should be installed in Slot 1

**Comment by RaosFPV** [comment]
and on Com port popup window appeared "pigeon?" when I connect to pigeon the message is the message - Slot 2 active, wtfos should be installed in Slot 1 and an inactive button, what does it say? ''install wtfos

**Comment by stylesuxx** [comment]
could you post a screenshot please?

**Comment by RaosFPV** [comment]
I didn't know I could upload pictures, in the meantime I went to buy a new usb cable and it seems the problem was in it, this is the message now
![root f](https://user-images.githubusercontent.com/117288775/199608588-1314007c-9bd8-4534-b3db-a9e9f53f60dc.jpg)

**Comment by RaosFPV** [comment]
should i try to install?

**Comment by RaosFPV** [comment]
after click install situation is ... gray area of click button I?cant click install wtfos
![root f2](https://user-images.githubusercontent.com/117288775/199609657-b5d15efb-af7f-487a-864a-11be4de1f6f9.jpg)

**Comment by RaosFPV** [comment]
I clicked attempt fixed port 1 and now I can't connect anymore
nothing happens when i click pigeon paired

**Comment by RaosFPV** [comment]
WORKS AGAIN
I had to click WTFOS/HOME 
![root f4](https://user-images.githubusercontent.com/117288775/199611542-76eea8c9-946b-446a-829b-2da2174c0a90.jpg)

**Comment by RaosFPV** [comment]
and now i can install
![root f5](https://user-images.githubusercontent.com/117288775/199611613-061b8c51-fb4b-4f4e-8e6c-8ff17deb78c6.jpg)

**Comment by stylesuxx** [comment]
Yeah, so everything is working as it should :-D

**Comment by RaosFPV** [comment]
but I couldn't do anything until I clicked HOME
