### ISSUE TITLE
WTFOS

### ISSUE THREAD

**Issue by Daramidon** [fpv-wtf/wtfos-configurator#225]
WTFOS is not installed. the ATTEMPT FIX button does nothing and the INSTALL button does nothing either. What should I do? I've been trying to install WTFOS for the second day. Root is done more than once successfully.
<img width="960" alt="wtfos" src="https://user-images.githubusercontent.com/117340783/199819739-0b51a937-ec08-4783-ba1b-35c0ff20a30b.png">

**Comment by stylesuxx** [comment]
Attempt fix should do something, you don't get a loading spinner at all? This will probably require a troubleshooting session via Discord...

**Comment by Daramidon** [comment]
trying to fix does nothing.  The screen freezes and nothing happens.  if I click install Wtfos then the situation is the same.

**Comment by Daramidon** [comment]
what is Discord?

**Comment by Daramidon** [comment]
three days ago i installed this on my dji googles glasses, air unit, caddx vista and it worked. but today caddx vista stopped working as it should. goggles and air unit work fine. For some reason, in DJI Assistant 2 (DJI FPV series), none of the devices shows what firmware is installed on them. That is how it should be?

**Comment by stylesuxx** [comment]
Yes, that is normal. You have to remove wtfOS for the devices to be recognized again.

So it was working at one point. That's an important part of information, at least the error makes sense now. Your slot is probably corrupted.

Discord is a chat, just follow the link on the configurators home screen.

**Comment by Daramidon** [comment]
should I follow this link? I'm just far from these technologies, I'm here for the first time.
<img width="960" alt="wtfos 1" src="https://user-images.githubusercontent.com/117340783/199834224-23383679-dd13-4637-98fe-948263a6d13f.png">

**Comment by Daramidon** [comment]
how can I remove WTFOS if the REMOVE window is not active?

**Comment by stylesuxx** [comment]
No, on the home screens one of the cards says "Discord". Follow that link, and set up an account

**Comment by stylesuxx** [comment]
Right now you don't remove anything because your slot is probably corrupted. Just join discord and let's talk there. It would literally take me five minutes to have a look...

**Comment by Daramidon** [comment]
THIS ONE?
<img width="960" alt="wtfos 2" src="https://user-images.githubusercontent.com/117340783/199835172-cf51d1b8-4314-4c6e-b145-00f755bbc5a7.png">

**Comment by stylesuxx** [comment]
YES!

**Comment by Daramidon** [comment]
куда мне надо нажать?
![Uploading wtfos 3.png…]()

**Comment by Daramidon** [comment]
where should i click?

**Comment by Daramidon** [comment]
<img width="960" alt="wtfos 3" src="https://user-images.githubusercontent.com/117340783/199836883-97f8ace7-b508-430b-a351-f61f14f6c77d.png">

**Comment by Daramidon** [comment]
no one answers me there.

**Comment by Daramidon** [comment]
Should I wait in discord for an answer to my problem?

**Comment by Daramidon** [comment]
did not wait for an answer and went to sleep

**Comment by stylesuxx** [comment]
I don't see a message from you, in which channel did you post? You can also just directly ping me if it's easier: stylesuxx#5855

**Comment by Daramidon** [comment]
could you please send a screenshot of the discord page where i should enter and what to click to chat with you. I am far from the world of computers and do not know how to use it.
