### ISSUE TITLE
DJI Goggles V2 - USB Device Not Recognized

### ISSUE THREAD

**Issue by Bookmdanno** [fpv-wtf/wtfos-configurator#227]
I was finally able to get my DJI Air Unit rooted and WTFOS installed but now my Win10 pc will not recognize the V2 Goggles.  I tried uninstalling/reinstalling the USB driver but no luck.  Is this a common issue with easy fix?  (Just out of curiosity, I also tried the goggles on a Win7 pc and it said the same thing.  Already tried multiple USB cables and ports.  Made sure no other apps running.
Thanks

**Comment by Bookmdanno** [comment]
No, it's not the same.  Before, Windows recognized the Air Unit but the Configurator couldn't open the serial port.  Now, Windows doesn't recognize the goggles so the Configurator popup only says it wants to connect to a serial port but it doesn't show the device and com port # now at all.


USBEvent[17:57:55] USB device function updated: guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{542906c5-b4f6-45b6-8e1c-3c50b40193de}", driver="usb_rndisx"

USBEvent[17:57:54] USB device function updated: guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#7&c130755&0&0003#{20343a29-6da1-4db8-8a3c-16e774057bf5}", driver="libusb0"

USBEvent[17:57:54] USB device function updated: guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{cac88484-7515-4c03-82e6-71a87abac361}", driver="usb_rndisx"

USBUser[17:57:54] USB device added: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "pigeon", serial="987654321ABCDEF", driver="usbccgp", guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a

USBUser[17:57:51] USB device removed: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=0860240a-e0f8-454e-b8cc-bae125596b70




    On Tuesday, November 8, 2022 at 05:35:27 PM MST, Chris ***@***.***> wrote: 


It is probably the same thing that prevented you from installing it on your air unit. Do the same thing I asked you to do with the air unit. Check version with DJI Assistant, and close whatever you had to close to get the air unit going.

**Comment by Bookmdanno** [comment]
Do the goggles need to be in fpv drone mode?  Tried that but Windows still doesn't recognize them.  Here's something weird - the Configurator did see the goggles ONCE and started the root process but it hung on Step 3.  Now back to same unrecognized device.

    On Tuesday, November 8, 2022 at 06:04:12 PM MST, Dan ***@***.***> wrote:  
 
  No, it's not the same.  Before, Windows recognized the Air Unit but the Configurator couldn't open the serial port.  Now, Windows doesn't recognize the goggles so the Configurator popup only says it wants to connect to a serial port but it doesn't show the device and com port # now at all.


USBEvent[17:57:55] USB device function updated: guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{542906c5-b4f6-45b6-8e1c-3c50b40193de}", driver="usb_rndisx"

USBEvent[17:57:54] USB device function updated: guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#7&c130755&0&0003#{20343a29-6da1-4db8-8a3c-16e774057bf5}", driver="libusb0"

USBEvent[17:57:54] USB device function updated: guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{cac88484-7515-4c03-82e6-71a87abac361}", driver="usb_rndisx"

USBUser[17:57:54] USB device added: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "pigeon", serial="987654321ABCDEF", driver="usbccgp", guid=ad99cdb5-be15-474b-9f93-fd01d6429d5a

USBUser[17:57:51] USB device removed: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=0860240a-e0f8-454e-b8cc-bae125596b70




    On Tuesday, November 8, 2022 at 05:35:27 PM MST, Chris ***@***.***> wrote: 


It is probably the same thing that prevented you from installing it on your air unit. Do the same thing I asked you to do with the air unit. Check version with DJI Assistant, and close whatever you had to close to get the air unit going.

**Comment by stylesuxx** [comment]
No - goggles have to be in DIY mode. Your log does not show a serial device.

**Comment by Bookmdanno** [comment]
Ok, after a lot of trouble finally got the Win10 pc to recognize the goggles.  Lots of fooling around with USB drivers but I don't think that had anything to with it.  It recognizd it ight after doing a factory reset on th goggles.
Now back to the same "Failed to open serial port: FILE_ERROR_ACCESS_DENIED" problem as on Air Unit. You said try admin mode.  I know how to open a program as administrator but how do you do it when it's a web based app like your Configurator?  I assume that since I'm logged into my pc as me, I must be in admin mode all the time, no?  Anyway, I did find how to run Chrome as admin and tried but I still get same ACCESS DENIED.


SerialError[09:24:17] Failed to open serial port: FILE_ERROR_ACCESS_DENIED

SerialEvent[09:23:55] Serial device added: path=COM5 instance_id=USB\VID_2CA3&PID_001F&MI_04\7&C130755&0&0004 vid=2CA3 pid=001F

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=4, path="\\?\usb#vid_2ca3&pid_001f&mi_04#7&c130755&0&0004#{86e0d1e0-8089-11d0-9ce4-08003e301f73}", driver="usbser"

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{cac88484-7515-4c03-82e6-71a87abac361}", driver="usbrndis6"

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{8942379d-e234-43b7-8110-17afba702273}", driver="usbrndis6"

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#7&c130755&0&0003#{20343a29-6da1-4db8-8a3c-16e774057bf5}", driver="libusb0"

USBUser[09:23:55] USB device added: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "pigeon", serial="987654321ABCDEF", driver="usbccgp", guid=6b7515d3-7a03-4bd4-b612-56847911f1f8

SerialEvent[09:23:48] Serial device removed: path=COM5

USBUser[09:23:48] USB device removed: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=e35b856e-04e6-4e93-9316-7e3a8436af8e

SerialError[09:23:40] Failed to open serial port: FILE_ERROR_ACCESS_DENIED




    On Wednesday, November 9, 2022 at 04:25:51 AM MST, Chris ***@***.***> wrote:  
 
 


No - goggles have to be in DIY mode. Your log does not show a serial device.

**Comment by Bookmdanno** [comment]
Hi Chris,
Well I've been to hell and back with the DJI system and this pc for 2 days and nights.  But I did finally get the goggles rooted and WTFOS installed.  I halted a bunch of services on the pc again and the Configurator was finally able to grab a serial port.  Don't have time to figure out if it was one particular service or not.  It started having trouble again afterward.  On the other hand, the Air Unit has been easy to connect and didn't have any further problems as I was using the CLI.  I never want to have to go through this kind of pain again.  But probably will ;)
Anyway, thank you for your help.  I'll be donating to you guys again.
Dan


    On Wednesday, November 9, 2022 at 09:35:59 AM MST, Dan ***@***.***> wrote:  
 
  Ok, after a lot of trouble finally got the Win10 pc to recognize the goggles.  Lots of fooling around with USB drivers but I don't think that had anything to with it.  It recognizd it ight after doing a factory reset on th goggles.
Now back to the same "Failed to open serial port: FILE_ERROR_ACCESS_DENIED" problem as on Air Unit. You said try admin mode.  I know how to open a program as administrator but how do you do it when it's a web based app like your Configurator?  I assume that since I'm logged into my pc as me, I must be in admin mode all the time, no?  Anyway, I did find how to run Chrome as admin and tried but I still get same ACCESS DENIED.


SerialError[09:24:17] Failed to open serial port: FILE_ERROR_ACCESS_DENIED

SerialEvent[09:23:55] Serial device added: path=COM5 instance_id=USB\VID_2CA3&PID_001F&MI_04\7&C130755&0&0004 vid=2CA3 pid=001F

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=4, path="\\?\usb#vid_2ca3&pid_001f&mi_04#7&c130755&0&0004#{86e0d1e0-8089-11d0-9ce4-08003e301f73}", driver="usbser"

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{cac88484-7515-4c03-82e6-71a87abac361}", driver="usbrndis6"

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#7&c130755&0&0000#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{8942379d-e234-43b7-8110-17afba702273}", driver="usbrndis6"

USBEvent[09:23:55] USB device function updated: guid=6b7515d3-7a03-4bd4-b612-56847911f1f8, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#7&c130755&0&0003#{20343a29-6da1-4db8-8a3c-16e774057bf5}", driver="libusb0"

USBUser[09:23:55] USB device added: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "pigeon", serial="987654321ABCDEF", driver="usbccgp", guid=6b7515d3-7a03-4bd4-b612-56847911f1f8

SerialEvent[09:23:48] Serial device removed: path=COM5

USBUser[09:23:48] USB device removed: path=\\?\usb#vid_2ca3&pid_001f#987654321abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=e35b856e-04e6-4e93-9316-7e3a8436af8e

SerialError[09:23:40] Failed to open serial port: FILE_ERROR_ACCESS_DENIED




    On Wednesday, November 9, 2022 at 04:25:51 AM MST, Chris ***@***.***> wrote:  
 
 


No - goggles have to be in DIY mode. Your log does not show a serial device.

**Comment by stylesuxx** [comment]
You should really think about re-installing your setup maybe. This is the first time I hear about such issues. I really think that there must be some service that for whatever reason is claiming the serial devices. That's why in some of the logs you don't see them at all.

I am just wondering, now that they are rooted - you don't have any issues connecting to them?

**Comment by Bookmdanno** [comment]
Yes, I do have the same issue with the goggles but not the Air Unit now.  The 2 PCs were very fast gaming machines with Intel i7 and 8GB of very fast DRAM but they were already a fews years old when i bought them several years ago (for $600 a piece).  I haven't been keeping up on what's out there now because I've been very happy with these.  Actually, I've only been using the Win7 one and the other was for a backup in case the 1st one bit the dust.  But now it's getting to the point where there's so much that only works on the newer Windows versions and that bloated sw takes so much horsepower that even the 8-core i7 is straining to run Windows 10 compared to how fast Win7 does eveything.  Maybe i'm wrong and even the newest PCs are bogged down by Win 10 and 11???  I have no idea.As far as the serial port problem, you may not have seen it but I wrote that the goggles had the same problem on the Win7 PC with getting a serial port.  So maybe it's some weird incompatibilty between the ASUS G74SX and the DJI hw/sw??  I'm going to start looking into new PCs and find out what's going on there again after not paying any attention to the industry for so many years.  I just really don't want to spend a big bunch of money.

    On Wednesday, November 9, 2022 at 03:42:10 PM MST, Chris ***@***.***> wrote:  
 You should really think about re-installing your setup maybe. This is the first time I hear about such issues. I really think that there must be some service that for whatever reason is claiming the serial devices. That's why in some of the logs you don't see them at all.

I am just wondering, now that they are rooted - you don't have any issues connecting to them?

**Comment by stylesuxx** [comment]
Windows 7 is EOL for more than 2 years, you should really not be using that in any case. I don't think that you need to buy new computers, just re-install/update windows... I'd probably upgrade the Win 7 box at first. I personally don't run Windows, but I would be afraid to run any OS that did not have Updates for over two years. I am surprised to hear that the 8 core machine is struggling to run win 10. My wifes notebook runs win 10 without issues and that's a pretty low spec machine.

I really don't think it is a hardware issue - there is really no reason for any incompatibility in that regards - especially since you are saying that disabling some services solves the issue.

**Comment by Bookmdanno** [comment]
Thanks Chris.  You know, you're likely right about not needing new PCs.  I forgot that I've got an SSD in the Win7 machine and a regular hard drive in the Win10 one.  So everything that requires HD transactions is of course a lot slower with the mechanical device.  You're right too about the EOL OS but I was so satisfied with it compared to Win10 that I just got lazy and kept using it.  I've got an antivirus app on it that's regularly updated but I realize I COULD get hacked sometime. 

    On Wednesday, November 9, 2022 at 06:33:36 PM MST, Chris ***@***.***> wrote: 


Windows 7 is EOL for more than 2 years, you should really not be using that in any case. I don't think that you need to buy new computers, just re-install/update windows... I'd probably upgrade the Win 7 box at first. I personally don't run Windows, but I would be afraid to run any OS that did not have Updates for over two years. I am surprised to hear that the 8 core machine is struggling to run win 10. My wifes notebook runs win 10 without issues and that's a pretty low spec machine.

I really don't think it is a hardware issue - there is really no reason for any incompatibility in that regards - especially since you are saying that disabling some services solves the issue.
