### ISSUE TITLE
Vista Rooted but site crashes when I try to connect to install WTFOS

### ISSUE THREAD

**Issue by FullHam** [fpv-wtf/wtfos-configurator#230]
Hello,

I rooted a Vista, but when I try to re-connect to install WTFOS, or to get into the CLI, or any type of connection besides a root, the fpc.wtf website crashes (I click connect, choose the Vista in the com port pop-up menu, connect again, and then crash). I tried re-rooting another three times, and it does so successfully every time, but I can't successfully connect to the Vista to do anything else after that.

I rooted another Vista successfully this very evening, but I'm having trouble with the second one. I tried two different browsers on two different PCs just to make sure. I did some searching to see if anyone else came across this issue, but I didn't find any answers. Any help would be greatly appreciated, thank you kindly.

**Comment by stylesuxx** [comment]
Could you please try the develop build: https://develop.fpv.wtf

**Comment by FullHam** [comment]
Hi, thanks for replying and your. I was able to install WTFOS and the packages using the develop build, but I do not have OSD in the googles. No WTFOS and no Custom DJI OSD.

**Comment by stylesuxx** [comment]
Please try using Butter to downgrade to a clean state: https://github.com/fpv-wtf/butter

**Comment by FullHam** [comment]
Thanks, I'll give that a try, hopefully it resolves the issue.

**Comment by stylesuxx** [comment]
Any update on this?

**Comment by FullHam** [comment]
Apologies but I haven't had the time to tend to it this week. I'm hoping to get to it next week, I'll leave an update when I do.

**Comment by FullHam** [comment]
I just had some time finally to sit down and go over the whole Butter process. So my Vista on this particular quad is currently on version 01.00.0606 (and it's working fine, it roots fine, it just refuses to install and run WTFOS properly). The recovery file says that it's for version 01.00.0608, which would mean that I would be required to upgrade all of my drones to that version of the firmware, which is something that I don't want to do right now. Is there a way for Butter to do a recovery to version 01.00.0606?

**Comment by stylesuxx** [comment]
I don't really think that there should be an issue between those two versions, I mean, no need to upgrade everything.

**Comment by FullHam** [comment]
Awesome, everything is updated and working as it should. Butter is pretty awesome! Thanks for all of your help and everything that you do for the FPV community 😎👍
