### ISSUE TITLE
report Custom OSD Pros/Cons on Nov 2022

### ISSUE THREAD

**Issue by upyopyo** [fpv-wtf/wtfos-configurator#231]
Hi, first of all, I would like to say, thank you so much for that team who develop that features.!! And here is my thought;

https://www.youtube.com/watch?v=OU07MH5wUrA
by following the above link, I just installed all the process, root, WTF, and custom OSD,

Pros:
now we can display additional OSD data in the goggles "during flying a drone", especially  another RSSI datas.

Cons:
After flight, we can see that OSD data when you only connect to his website and bake the OSD info to new mp4 movie. 
Font shape is not favorite so much because it's too fat and overlay is just 100%, no transparency at all.

Request
A. 
Is that possible to get some better fonts and have 80% transparency for the custom OSD in the goggles? For example, I like the original DJI OSD's font because it's nice font shape, and has some transparency. (little bit too small to read them) 

B.
Can we watch a custom OSD during playback mode with the goggles? 
I was hoping to be able to watch GPS's location data in playback with the goggle. This is because, if we lose the drone, we can write that longitude and latitude data to a  google map with a smartphone instantly, in order to find the drone.  However, in this case, we need to go home to produce an OSD baked video at first. 

C. Additionally this custom OSD keeps showing last osd info all the time. In order to hide it, we need to turn off/on the battery of the goggles. 

If I misunderstand something and we already have these features, please let me know, thank you!!

**Comment by stylesuxx** [comment]
A. That should be possible yes. I would suggest you join Discord, you can catch the dev there, I am sure.
B. I don't think that this is possible - @bri3d maybe you have more input on this?
C. I really don't understand - are you saying that the last from of the OSD is permanently visible in your googles even after powering down the air unit?

**Comment by bri3d** [comment]
B) This is possible but difficult. It can be done by loading the MSP data and rendering it over the video while it plays in the goggles. Knifa was working on it at one point. Unfortunately the way the video playback pipeline works on the goggles makes it hard to frame-synchronize the MSP data properly. What isn't possible is producing an MP4 file with the OSD already baked in, because it would require H.264 re-encode resources which we don't have.

C) This behavior is intentional for the exact reason you outline - in the event of a crash, you can see the last coordinates.

**Comment by upyopyo** [comment]
A) umm, I am not familiar with Dicord community, so will wait for development. 

B) C) bri3d;  uh, then that makes sense! I tested the goggles in my room, and I understood what you mean. Next time, I will test it outside, and use goggle map to find the drone. 

Thanks developers!

**Comment by stylesuxx** [comment]
Closing this, I think all questions have been answered here.
