### ISSUE TITLE
can the root work on v01.00.06.08

### ISSUE THREAD

**Issue by SteelBalls85** [fpv-wtf/wtfos-configurator#232]
there is a new v01.00.06.08 installed on a used set of goggles that i just bought, and the have v01.00.06.08, dont want to brik them, so can i do the root on the new version?

**Comment by SteelBalls85** [comment]
its the V1 goggles btw

**Comment by j005u** [comment]
Yes, it'll work just fine.

**Comment by SteelBalls85** [comment]
tnx Sendt fra E-post for Windows Fra: Joonas TrussmannSendt: søndag 20. november 2022 kl. 04:53Til: fpv-wtf/wtfos-configuratorKopi: SteelBalls85; AuthorEmne: Re: [fpv-wtf/wtfos-configurator] can the root work on v01.00.06.08 (Issue #232) Yes, it'll work just fine.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by SteelBalls85** [comment]
i get this:
----------------------------------------------------------------
00:03 Attempting Step 1...

00:17 - Found Device: GL150, Version: 01.00.0608

00:17 Step 1 - Success! Rebooting...

00:33 Attempting Step 2...

00:53 Failed after 10 retries.
