### ISSUE TITLE
DJI Goggles V2 - "Switch to DJI Digital FPV System option is missing from the About menu"

### ISSUE THREAD

**Issue by ipppolit** [fpv-wtf/wtfos-configurator#233]
**DJI Goggles V2 - V01.00.0606 - DIY MODE**
Successfully completed the steps: Root, Install WTFOS, Install Packages. MSP OSD – full Betaflight OSD support has been working correctly. 
While setting up the LED matrix through the CLI on the website https://fpv.wtf/root, the battery ran out of the glasses, something went wrong and they stopped working. 
After a hard reset, through a clamped bind when turned on, the glasses loaded successfully in DJI drone mode.

**Issue - Switch to DJI Digital FPV System option is missing from the About menu.**

I tried to go through all the steps to activate the glasses through the DJI Assistant in VPN mode through the US. The option to switch in DIY MODE did not appear.

When trying to flash V01.02.0020 FPV firmware (V01.02.0020_FPV_Racer_dji_system.bin Drone firmware from Dank Drone Downloader) via the Dronehacks desktop client, the error "_**This firmware is incompatible with the connected device**_" occurs.
The same error occurs when trying to flash other firmware versions:
_V01.00.0606_GP150_dji_system.bin
V01.02.0001_gl170_dji_system.bin_

Dronehacks desktop client recognizes the glasses as a _device gl170, firmware: V01.00.0606_ 

What I'm doing wrong?

**Comment by stylesuxx** [comment]
Did you try tor refresh the firmware via DJI Assistant?

**Comment by j005u** [comment]
See here for switching modes via CLI: https://github.com/fpv-wtf/wtfos/wiki/Troubleshooting#switching-between-diy-and-dji-fpv-drone-modes-from-the-cli

**Comment by ipppolit** [comment]
Thanks, it works great!

To switch to DIY Mode via CLI on the https://fpv.wtf/cli  

```
unrd product_type wm150_gls
reboot
```
