### ISSUE TITLE
Msp - OSD support for V01.00.0607 firmware on DJI goggles V2

### ISSUE THREAD

**Issue by leoponce82** [fpv-wtf/wtfos-configurator#234]
I rooted my goggles while on V01.00.0606 firmware. After updating to 607 firmware I still have the root access but lost all MSP-OSD support. Is this possible in the future? to gain back msp-osd support for 0607 firmware?

**Comment by stylesuxx** [comment]
What do you mean by you "lost" MSP-OSD support? You can connect via configurator, packages are installed, services are running, but you don't get the OSD?

Please provide more infos.

**Comment by leoponce82** [comment]
That is correct. I can connect via configurator, I re-installed the msp-osd package(after upgrading to version 607) but no osd is displayed in the goggles. 
I also notice that in the Startup page (in configurator) the services cannot be turned on.

**Comment by leoponce82** [comment]
I uninstalled WTFOS, tried re-rooting, got the message about "firmware version too new", re-connected to the configurator, re-installed WTFOS, and got the same message, but it still worked. Installed packages again and recovered complete functionality. 
Thanks for your support.
