### ISSUE TITLE
Start button hide by panel V1.0.0. Trace

### ISSUE THREAD

**Issue by reednoel4u** [fpv-wtf/wtfos-configurator#236]
Dear all,
I usìng Iphone and open link https://knifa-develop.fpv.wtf/osd-overlay but cann't touch ơn Start button.
Please show me họ to fix it.
Thanks
https://user-images.githubusercontent.com/19307447/203535333-19bb0d13-d25e-4572-bfd9-463118994181.mp4

**Comment by stylesuxx** [comment]
Won't work on an iPhone.

**Comment by stylesuxx** [comment]
Fixed in latest dev.
