### ISSUE TITLE
Rooting causes browser crash (STATUS_ACCESS_VIOLATION) on DJI FPV Googles v2

### ISSUE THREAD

**Issue by robertrypula** [fpv-wtf/wtfos-configurator#238]
When I try to root my googles my browser always crash with STATUS_ACCESS_VIOLATION. I also checked [develop.fpv.wtf/root](https://develop.fpv.wtf/root) and I face the same problem.

My setup
- Windows 10 pro
- All programs closed
- Avast antivirus protection turned off UPDATE: I uninstalled it from the system and still get STATUS_ACCESS_VIOLATION
- proper version on Googles (606 on **both modes** verified in the **googles** and in **DJI Assistant**)
- proper USB-C data cable (original from DJI)
- batteries charged, I wasn't touching any cable during first try (nothing was disconnected during the process)

I've tested in on Chrome, Edge, different USB ports in my laptop and same issue occurs:

![image](https://user-images.githubusercontent.com/6407731/204136998-7dc6fe62-f66a-47fa-9640-e003854946f4.png)
![image](https://user-images.githubusercontent.com/6407731/204137018-6263eec9-1b6c-47f1-bb25-b22756541a84.png)

Some dev tools log:
```
Created new watcher...
Startup check
connect true true true
Disposing old watcher...
Created new watcher...
00:01 Attempting Step 1...
00:02 Device went away...
Unlock step failed: DOMException: Failed to execute 'open' on 'SerialPort': Failed to open serial port.
00:08 Device came back...
00:11 Attempting Step 1...
```

After that browser crashes.

The additional problem that occurred **after** I tried rooting is that my googles are no visible in DJI Assistant anymore. I tried reinstalling it to the latest one v2.1.14 and same problem - no googles in DJI Assistant.
UPDATE: in DJI Assistant sometimes I do see googles but just for less than 1 second. That is not problem of broken cable or port in laptop or in the googles. 

My feeling is that my googles are available in the system for less that 1 second and they are gone. From time to time they re-appear and are gone again. It was not happening before trying to ROOT. Connection was rock solid before I tried to root.

**Comment by stylesuxx** [comment]
Are the goggles constantly re-booting - or can you use them normally when not trying to root them?

**Comment by robertrypula** [comment]
Googles works fine and connects to Vista. Before trying to root I removed SD Card and did not have it during rooting.

Now I did another test:

1. Inserted SD Card
2. Connected the Googles via USB-C cable
3. My system detects googles and shows Removable drive with all SD card content
4. Connection is rock solid when Assistant is **not** running
5. As soon as I run DJI Assistant it shows the googles for less than 1 second (in assistant) and then they are again gone including the USB mass storage drive with SD card content. After few seconds the mass storage is back again, DJI sees again googles for short moment and again it disappears. It continues with period of few seconds:

![image](https://user-images.githubusercontent.com/6407731/204139078-8cea1b00-4853-47f0-ba70-ec982b76f361.png)

![image](https://user-images.githubusercontent.com/6407731/204139167-89cb2006-d57b-4edd-b054-98b2aac79a94.png)

![image](https://user-images.githubusercontent.com/6407731/204139307-b978f54d-dcf7-43d9-93d0-cfb6ef814373.png)

Sometimes I end up with this error as well:

![image](https://user-images.githubusercontent.com/6407731/204139348-c6256a03-c7a3-4a27-aae8-0f5501ff845a.png)

Looks like something is crashing on the googles side as soon as I run any software that wants more than just mass storage access from the googles :(

**Comment by robertrypula** [comment]
I saw that you edited your message - answer for all your questions:

**Are the goggles constantly re-booting - or can you use them normally when not trying to root them?**
I can connect to vista and all seems to work expect after trying to root I cannot use DJI Assistant anymore as it constantly shows the googles for 1 second, then hides them and shows them again in the loop with period of few seconds.

**Also did the initial root go through, or what was the problem initially?**
First root immediately caused browser crash with STATUS_ACCESS_VIOLATION. I'm 99% sure that it was on attempt 1. It never went further.

**Can you connect through the home screen?**
Not really:

![image](https://user-images.githubusercontent.com/6407731/204139648-f835ee15-1ee9-4204-a1d7-6f3ebe4f9c8b.png)

**Comment by stylesuxx** [comment]
Yeah, something seems to be messing with your drivers and additionally your firmware seems to be off, since it shows "Unknown" in step 1. Any chance you could try on a different computer? If rooting did not go through there is no reason for DJI assistant rejecting it. You should definetly refresh firmware first

**Comment by robertrypula** [comment]
Yeah, I also saw "Unknown" which is weird because I checked the version and it was everywhere (DJI Assistant, Googles in both modes) v606.

I don't have different computer at home at the moment. I'll try it later. Thanks!

Generic question: Trying to root via fpv.wtf configurator on fresh machine will work or I still need to install DJI Assistant for some missing drivers?

**Comment by stylesuxx** [comment]
You will have to check that DJI assistant is showing 0606. And you have to make sure to refresh firmware. As long us the configurator shows "Unknown" you will most likely have some issues in one way or the other.

**Comment by Kopturov** [comment]
I have exactly the same problem, I tried it on 2 different PCs, it repeats, a temporary solution for it is to rename *.exe of the browser to a different name than Chrome, the root passes, but then I can’t install wtfos anymore, points v1 firmware 608

**Comment by stylesuxx** [comment]
@Kopturov if your root passes, then you don't have "exactly" the same problem ;-) Can you pleas open a seperate issue? otherwise it will get confusing. Please answer the following questions in your issue:
* Why does it behave differently if you rename the exe, what made you rename it in the first place?
* After rooting, can you connect via CLI?

**Comment by Kopturov** [comment]
I tried to root through the browser about 30 times, 28 times I was thrown out with the STATUS_ACCESS_VIOLATION error, if you google this error on the Internet, there are solutions, such as rename the exe, update the browser, create a new profile, etc., that's when I did all these options, on renaming the browser 2 times I was allowed to reach stage 5 and wrote that the root is ok, but then it wrote to me that something was installed in slot2, but it should be in slot1, I pressed FIX and that’s it, the device is not visible for installing WTFOS . Further, I thought that somehow the root got crooked and tried to repeat it, so as not to press the fix, but try to put WTFOS

**Comment by robertrypula** [comment]
@stylesuxx  I have some progress. I rooted my googles on my wife's laptop. Unfortunately she doesn't have admin rights as this is laptop from her work but it was perfectly possible to open fpv.wtf configurator in the Chrome browser and Root **without refreshing** in DJI Assistant as I could not install it as everything is blocked on her machine ;)

Now on my laptop (the one that has STATUS_ACCESS_VIOLATION error) I'm able to connect to the googles and open for example CLI:

![image](https://user-images.githubusercontent.com/6407731/204152894-42445a02-f823-4087-adda-7176d1384418.png)

Unfortunately Assistant on my machine still cannot connect as I get same endless loop of showing and hiding. I guess my laptop setup is somehow broken. Maybe due to Docker or other stuff that I have for work. I need to find someone with normal laptop with full admin rights and refresh v01.00.0606

**Question**: Does refreshing in Assistant removed already active root hack?

**Comment by robertrypula** [comment]
> I have exactly the same problem, I tried it on 2 different PCs, it repeats, a temporary solution for it is to rename *.exe of the browser to a different name than Chrome, the root passes, but then I can’t install wtfos anymore, goggles v1 firmware 608

@Kopturov Seems like you were just lucky enough to finish root step sooner than the browser crashed. That doesn't really solve the problem ;) I guess you should try to find yet another (third PC) and try again. On my wife's machine root went smoothly but when I got back to my laptop I still have some issues with connecting the googles with DJI Assistant. Maybe I still have to refresh the googles or just my laptop setup it broken. I need to dig into that

**Comment by Kopturov** [comment]
Yes, probably my problem is that my root is installed in the wrong Slot, then when I press FIX, FIX itself does not work and it looks like I have to root again and so on in a circle. I'll go look for a solution on the topic Slot

**Comment by robertrypula** [comment]
@stylesuxx Hurray!! I have almost 100% success with the googles:

![image](https://user-images.githubusercontent.com/6407731/204155329-45f655f8-f5a4-4bf6-9388-ec006d79ba73.png)

For the others to summarize my previous a bit messy messages in this thread. Here is what I did:
- First root attempt failed as my browser crashed with STATUS_ACCESS_VIOLATION
- I was not able to root on my machine as STATUS_ACCESS_VIOLATION continued whenever I tried
- I realized that my DJI assistant cannot connect to the googles anymore (sees the googles for 1 sec and the it's gone, after few seconds sees it again and gone - endless loop)
- I used my wife's PC (no admin rights as it's handled by organization and I couldn't install any software) and was able to ROOT using WTF configurator **without installing** DJI Assistant and doing any refresh
- After going back to **my PC** I was able to install WTF OS and all packages

**Only missing piece is:**
- My DJI Assistant still cannot connect to the googles but as of now I think I will ignore it ;) Probably it will again become a problem when I'll buy O3 Air Unit. Without connecting DJI Assistant it won't work...

In order to not loose it - there is still one question open from my side:
**Does refreshing v01.00.0606 in Assistant remove an already active root hack?**

**Comment by stylesuxx** [comment]
If you can not connect to DJI Assistent after rooting, that is expected and you will have to remove wtfOS completely - so this should also answer you last question - implicitly yes, since you remove it manually, but you will be able to root again since one fragment of rooting can not be undone.

**Comment by Kopturov** [comment]
For history, I also solved my problem, VPN helped me, it seems that some relationships are drawn from resources that are not available to me

**Comment by stylesuxx** [comment]
@Kopturov that is very interesting - which country are you from?

**Comment by Kopturov** [comment]
> @Kopturov that is very interesting - which country are you from?

Russia 😐
