### ISSUE TITLE
OSD not showing after few flights

### ISSUE THREAD

**Issue by Indazanfpv** [fpv-wtf/wtfos-configurator#240]
Hi,ive been using wtfos for one month now and after rooting ive got the osd but when im going for a flight tomorrow the osd is not there anymore goggle says “waiting for osd” it only works again when i plug vista into the website.this issue has been consistent for a month now.ive tried re root and setting it up all over again but still is the same.Thank you!

**Comment by slup67** [comment]
Most probably the same issue as the closed case #192 & the open #228

Did you connect to the FC with usb to enter Betaflight or do you get excessive arcing when connecting the battery... in between you saw the OSD working & when it stopped working?

**Comment by Indazanfpv** [comment]
Hey sorry for the late reply,after u mention on the previous issue it now make sense.its not arcing its just not showing maybe its true i did plug in and unplug rapidly.Thank you!

**Comment by stylesuxx** [comment]
@Indazanfpv - I did miss this issue - could you solve it in the end?

**Comment by stylesuxx** [comment]
Closed du to lack of answer.
