### ISSUE TITLE
After rooting cannot connecting again

### ISSUE THREAD

**Issue by Puttanamadonna** [fpv-wtf/wtfos-configurator#242]
I rooted my Goggles V2 and now cannot connect again to the configurator to install wtfos because doesnt see any device...Mac m1

**Comment by stylesuxx** [comment]
Then rooting probably did not go through. Could you post a screenshot of the rooting process? Also check with DJI assistant that you are on 0606.

**Comment by Puttanamadonna** [comment]
I tried rooting 4 times and all 4 times arrived until the end and was written success google rooted...
On the device info says FW 0606...but if I go now to assistant 2, it doesnt give me option to refresh 0606, only downgrade for 0606 and 0607...but it doesnt work eitther....

**Comment by stylesuxx** [comment]
if it gives you the option to downgrade to 0606, then you are not on 0606... What does the DJI Assistant show the version is? Please post screenshots of both, rooting process and DJI Assistant

**Comment by Puttanamadonna** [comment]
I repeat, in goggles info is written fw 0606...Dji Assistant doesnt show actual firmware, just 0606 downgrade and 0607 downgrade... there is something wrong...last week I checked new fw and was giving me option to  upgrade to 0608....
![IMG20221129183347](https://user-images.githubusercontent.com/119408044/204613919-439f2ac1-a887-4b0d-adc7-2721b0bc9eb4.jpg)
![IMG20221129184440](https://user-images.githubusercontent.com/119408044/204613965-aa1e8a63-f106-4764-b186-3e975f1241a4.jpg)
![IMG20221129185823](https://user-images.githubusercontent.com/119408044/204614024-63e71111-d5d8-4d38-ae7e-6937eedc68be.jpg)
![IMG20221129185958](https://user-images.githubusercontent.com/119408044/204614062-a94b93ee-d61a-4ecc-8942-80cab09a46e3.jpg)
![IMG20221129190014](https://user-images.githubusercontent.com/119408044/204614140-1900110e-0629-4053-aaf2-aa23a3289861.jpg)

**Comment by stylesuxx** [comment]
Last screenshot of DJI Assistant you can clearly see that you have the wrong firmware version: 01.02.0001

**Comment by Puttanamadonna** [comment]
Yes but that one is related at the fpv drone...that I never had...I use the goggles only with air units and vistas...and when I go to info is written (1 picture) 0606...it seems now locked in the 0001 fw...I dont know why...How can I solve?

**Comment by Puttanamadonna** [comment]
Doesnt give me the option to upgrade or downgrade...get stuck in transmitting (picture  3 and 4)

**Comment by stylesuxx** [comment]
> Yes but that one is related at the fpv drone...

Ok, well - if you know things better then why even bother asking? The goggles in diy mode "lie" regarding the version, they will always show 0606. Configurator and assistant tell the truth.

In the 2nd to last screenshot it shows "upload error log" you can't see any more information there?

**Comment by Puttanamadonna** [comment]
No more info unfortunately...I don't know anything...what I know is that before trying to root, in the Assistant was saying current 0606 and 0608 upgrade...now everything is fucked up...

**Comment by Puttanamadonna** [comment]
So please explane me, how can the system be in firmware version: 01.02.0001 and I'm in Dyi mode and flying a vista? I dont understand that...

**Comment by stylesuxx** [comment]
> So please explane me, how can the system be in firmware version: 01.02.0001 and I'm in Dyi mode and flying a vista? I dont understand that...

Why not? You should only be in 0606 for rooting.

Have you searched for the error you get during updating? There are a couple of people having the same issue on Mac and they seemed to be able to downgrade fine on a PC.

**Comment by j005u** [comment]
You can downgrade with butter instead: https://github.com/fpv-wtf/butter#usage

**Comment by Puttanamadonna** [comment]
I have a Mac m1

**Comment by j005u** [comment]
@Puttanamadonna 

I'm afraid DJI Assistant is broken on M1 Macs (nothing to do with the root) and butter also doesn't work on OS X. Beleive it or not, but for two completely different reasons.

But as you've indicated that the root has actually already succeeded you should try installing wtfos using this page: https://fpv.wtf/wtfos.

If you cannot get the device to show up when connecting, please try a Windows or Linux PC first if you're able to. It's possible there are more M1 Mac related problems. If it works on another PC, but not on your M1 Mac then that is useful info, please let us know.

If that doesn't work, then I would try finding a Windows PC to do the butter downgrade to V01.00.0606, then root, then install wtfos.

**Comment by Puttanamadonna** [comment]
Thank you, yes I’ll try with windows when I’ll find one….

**Comment by stylesuxx** [comment]
Going to close this. Feel free to re-open if issue persists.
