### ISSUE TITLE
[LT150] dinitctl: connecting to socket /data/.dinitctl: No such file or directory

### ISSUE THREAD

**Issue by robustini** [fpv-wtf/wtfos-configurator#244]
As I have already documented on Discord this Air Unit Light after rooted regularly does not allow correctly installed packages to run at boot for this dinit issue.
But then imparting this command in CLI the two selected services instead run smoothly as you can see in the image, without giving that command i cannot activate them, so I lose them at every reboot:

/opt/etc/init.d/rc.unslung restart

![immagine](https://user-images.githubusercontent.com/3864712/205854945-47026c3f-fcec-48cf-bb8b-4bdfa0126908.png)

@j005u has already performed remote session to check what it might be but has not figured out where the problem lies, and from what I read on Discord @stylesuxx had helped someone solve this problem always on an Air Unit Lite, I don't know if he succeeded or not.
We have already reflashed slot_1 to the stock version after checking the md5 of ota.zip with these commands, it gave no errors:

unrd slot_1.status_successful 0
unrd slot_1.status_active 0
unrd slot_2.status_active 1
rm -rf /blackbox/wtfos
reboot

But even after this operation, after wtfos repair/fix the problem was not solved.
Now in my ignorance if doing an initd restart after booting solves the problem one solution might be to create a check on whether the selected services actually start during boot (check of related PID or other), in case they are found to be disabled you run an rc.unslung restart, I think that would be the simplest solution.
It is possible that the execution of that services at boot occurs at a time where they find a condition so they cannot be executed? I don't know. 
If you do not understand where efffectively the problem lies I think it is enough to find an empirical way to skip the problem.
Tried with 606 and 608 firmware, same problem.
Re-executed reflashing with Assistant as well, but I remain in a dead end.
Without these services available at reboot the root in this unit is therefore useless.
I've execute root and everything else with the configurator on three other identical units and I haven't had any problems, selected services are performed at boot regularly.
I'm in your hands........ :-(

**Comment by robustini** [comment]
Don't ask me why but apparently all the services start, i've the msp-osd in the Goggles!

![image](https://user-images.githubusercontent.com/3864712/205878534-dd8f6a6a-878b-44c7-879e-6984b51a76ad.png)

It's the configurator that doesn't intercept them after a reboot, so they can't be activated in the startup, i can only activate/configure inside the startup page only after an rc.unslung restart in CLI!
Tested on two identical Vista Light, same issue.
So, after a reboot:

root@pigeon_wm150_tiny:/ # dinitctl list
dinitctl: connecting to socket /data/.dinitctl: No such file or directory

And after a "/opt/etc/init.d/rc.unslung restart":

root@pigeon_wm150_tiny:/ # dinitctl list
[[+]     ] boot
[{+}     ] wtfos-auto-naco
[{+}     ] msp-osd-airside (pid: 2736)

So this initd does its job at boot but then something abnormal happens.

**Comment by robustini** [comment]
I also performed a check on the third Caddx Vista Lite that I own, but funny thing is that here instead everything works as it should, initd has no problem at boot, services are configurable in the startup page.
So two Vista with this problem, one not.

**Comment by robustini** [comment]
I also performed a check on the third Caddx Vista Lite that I own, but funny thing is that here instead everything works as it should, initd has no problem at boot, services are configurable in the startup page.
So two Vista with this problem, one not, super weird, since I rooted and installed wtfos in exactly the same way.
**But there is a substantial difference: in the one where initd doesn't give problems after the boot I never updated the firmware (in fact /cache/ota.zip is missing), it came with 606.
In the other ones where I have updated the firmware instead initd does that weird thing.**

**Comment by stylesuxx** [comment]
Just to recap, we checked `env` and `mount` state before running  `dinit` in the `init.d` startup script - everything is looking fine so far.

`dinit` and the actual `msp-osd` is also running - that's why the OSD is working. Obviously the socket is not being created for some reason.

One thing we can do now is pull the system partition via ADB from one working vista and one broken one and diff it. After that we can try transplant parts of the system from the working one to the non working one and see what happens.

**Comment by robustini** [comment]
> 

Performed dump of two units with 606, one working and the other with problematic initd, you have PM on Discord.

**Comment by robustini** [comment]
@j005u @stylesuxx if it helps I did this,
I removed wtfos and root from the right unit running 606, upgraded to 608 and immediately noticed that after the upgrade by turning the unit off and on again the Assistant correctly detects version "1.00.0608" installed.
In the other two "broken" units with the initd problem after the upgrade the Assistant shows version "00.00.0000" and the configurator fails to pass attempt 1 during the root automatically, I have to turn off and on the Caddx Vista again to continue with attempt 2.
While rooting the good unit instead, attempt 1 resets the unit by itself, and when reconnected it correctly detects the firmware version.

00:21 - Found Device: LT150, Version: 01.00.0608

In the problem units, however:

00:09 - Found Device: LT150, Version: Unknown

And it is on these two that then initd gives that problem.
It can't be a fluke.
In the good unit that I upgraded to 608 of course the services start automatically without any problem.

**Comment by stylesuxx** [comment]
Interesting. I have seen people not being able to root with 00.00.0000 and the fix is to refresh the 0606 firmware via DJI assistant. So maybe this is something that you could try...

**Comment by robustini** [comment]
If comparing the system and wtfos in the units turn out to be identical in my opinion we should now focus on the /data, it is perhaps in there that something important changes.
My two cents...

**Comment by stylesuxx** [comment]
The version string is saved in an XML - the DJI assistant will also show you the 0000 version. This definitely should not be this way. Yes, some can root with this broken state, some can't, some can after doing weird things. The correct thing would be to downgrade to 0606  and make sure that this is also the version being displayed (during root and the DJI assistant - they both use the same location to read this version number).

It's probably not an issue with `/data` per say. It is an issue with the socket not being created there for some reason, or rather it being created, and being deleted somewhere in-between.

Is your working device showing the correct version number in the assistant?

**Comment by robustini** [comment]
> 

Before the root yes, turning it off and on again.
While the other two go to 00.00.0000 after repower.

**Comment by robustini** [comment]
Unfortunately, the "00.00.0000" problem is not solved by downgrading from 608 to 606, I just tried after removing wtfos and root.
The incorrect version problem was obviously generated after rooting, originally it did not.
This is the sequence:

This is before downgrading
![image](https://user-images.githubusercontent.com/3864712/206116877-6c8b0820-280f-4290-a2a6-fc3a4eb4fc68.png)

Successful downgrade
![image](https://user-images.githubusercontent.com/3864712/206117070-f8fa48bc-5914-4fb8-b985-6e6d2167c3f7.png)

Without restarting Caddx, the Assistant shows the correct version
![image](https://user-images.githubusercontent.com/3864712/206117201-53a7ee7d-94c0-4c8b-9f96-98ea52b6e663.png)

After restarting Caddx here comes the error again
![image](https://user-images.githubusercontent.com/3864712/206117300-66a4a793-8137-4b49-8cd3-cbb11c3f2ebb.png)

If we cannot figure out how to get out of this deadlock, the initd problem I think cannot be solved easily.

**Comment by robustini** [comment]
Browsing through the chat on Discord and searching for "00.00.0000" I see that others have had the same problem.

**Comment by stylesuxx** [comment]
Can you please use the latest version  of **DJI Assistant 2 (DJI FPV series)**?

**Comment by robustini** [comment]
> Can you please use the latest version of **DJI Assistant 2 (DJI FPV series)**?

Tried it now, same result, that 00.00.0000 won't go away even if i shoot it, damn.

**Comment by robustini** [comment]
It should be understood where he is and why he stays.
Could a /data dump of the working unit and this fucked one with the same firmware version be useful to figure out how we can solve it?

**Comment by j005u** [comment]
Using butter to reset to 0608 and then further re-flashing through the assistant solved the problem.

Closing.
