### ISSUE TITLE
Uninstalled WTFOS from Goggles 1.  Still seeing canvas mode!

### ISSUE THREAD

**Issue by ramiss** [fpv-wtf/wtfos-configurator#248]
Hi.  I uninstalled all packages and WTFOS from my Goggles 1 and Vista because my non WTFOS friends in audience mode said the image was terrible once I "installed that new firmware".

However, I still see BF Canvas mode from Vista!  So.... is it actually uninstalled?? How can I tell?   the WTF web site clearly thinks I'm uninstalled because the only option is to install.

**Comment by j005u** [comment]
Are you sure that's not the DJI "Custom OSD"?

If you are, you can use the newly released butter recovery tool to fully reset to stock: https://github.com/fpv-wtf/butter#usage

**Comment by slup67** [comment]
Just a thought...

The 2 Betaflight CLI commands you make initially when rooting+wtfos ...

_set osd_displayport_device = MSP_
&
_set displayport_msp_serial = (and here -1 uart from where the vista is)_

... doesn't these need to be reversed or put to default if not using wtfos? And then of course activate the Custom OSD in the goggles again.

**Comment by stylesuxx** [comment]
@ramiss any update on this? Otherwise I will close this issue.

**Comment by stylesuxx** [comment]
Closed due to inactivity.
