### ISSUE TITLE
Unable To Update Firmware And Install WTFOS After Butter Rollback

### ISSUE THREAD

**Issue by dantestyle83** [fpv-wtf/wtfos-configurator#249]
Steps Taken:
I1)  used BUTTER to roll back to v01.00.0606 
2) Then I rooted my device successfully
3) I used DJI Assistant to update to v01.05.0000 When I use assistant it automatically tells me that it needs to update due to somethign not matching
4) After update, I now have v01.05.0000 installed
5) When I go to fpv.wtf to install FPVOS - it shows an error to be fixed "Slot 2 active, wtfos should be installed in Slot 1" when I click 'fix' it essentially rolls me back to v01.00.0606 again. 

Not sure if this is user error or an issue with the recently released Butter.

**Comment by j005u** [comment]
Please see here for details and a fix: https://github.com/fpv-wtf/wtfos/wiki/Troubleshooting#installing-wtfos-after-upgrading-downgrades-the-firmware
