### ISSUE TITLE
V1 goggles won't root past step 2

### ISSUE THREAD

**Issue by advancedtacmachine** [fpv-wtf/wtfos-configurator#250]
Had V1 rooted and working. At some point they stopped searching for air unit and reading font from SD card.  Started the root process again but wouldn't get past step 2 site would crash.

Using different computer I was able to get them to root but after root screen said something about slot 1 and 2 (can't find the picture) and offered attempt to fix tab which I pressed. 

Didn't seem to work tried rooting again but it's back to failing root after and crashing site after step 2.  

![Wtf2](https://user-images.githubusercontent.com/76758227/207886713-98c2e90e-727b-470f-acad-40699fca5696.jpg)
![Wtf1](https://user-images.githubusercontent.com/76758227/207886743-eaf9d0a0-9c73-4fc8-983f-b968966ff550.jpg)

**Comment by stylesuxx** [comment]
@advancedtacmachine any update on your issue? Otherwise I will close it.
