### ISSUE TITLE
Error to install MSP-OSD

### ISSUE THREAD

**Issue by SkyDroneFPV** [fpv-wtf/wtfos-configurator#251]
Error during package installation:
Collected errors:

* opkg_install_pkg: Checksum or size mismatch for package jq. Either the opkg or the package index are corrupt. Try 'opkg update'.

* opkg_install_cmd: Cannot install package msp-osd.

Package msp-osd version 0.8.0 has no valid architecture, ignoring.

Package msp-osd version 0.8.0 has no valid architecture, ignoring.

Package msp-osd version 0.8.0 has no valid architecture, ignoring.

Package msp-osd version 0.8.0 has no valid architecture, ignoring.

Installing msp-osd (0.8.0) to root...

Downloading http://repo.fpv.wtf/pigeon/msp-osd_0.8.0_pigeon-airside.ipk

Installing jq (1.6-2) to root...

Downloading http://bin.entware.net/armv7sf-k3.2/jq_1.6-2_armv7-3.2.ipk

**Comment by stylesuxx** [comment]
So, did you try `opkg update` via CLI?

**Comment by stylesuxx** [comment]
@djgoldeneye you might try to re - install. There was an error with some third party apps, this should be solved now. Remove wtfOS and re-install.

**Comment by djgoldeneye** [comment]
Thank you!!

**Comment by SkyDroneFPV** [comment]
So I did this. On my Mac I get this error. I went to do this on windows and it worked with no error. It will not load pkg thru Mac OS. it works with Windows.
