### ISSUE TITLE
v2 black screen 

### ISSUE THREAD

**Issue by Redguy4life85** [fpv-wtf/wtfos-configurator#258]
hey so i tried the rollback for my v2 goggles and now theres nothing i tried to do the process again and it say initially something was a triumph waiting and then all that happens is the sound like usb is plugged in and un plugged please help this sucks cause now i cant afford goggles and wont fly without cause ive lost to many drones that way i was finally starting to get comfortable just wanted more info while flying and yeah please and thank you

**Comment by stylesuxx** [comment]
Not sure what you have exactly tried. Best thing is to reset via Butter: https://github.com/fpv-wtf/butter

**Comment by Redguy4life85** [comment]
Thanks and I forgot I posted on here but I managed to get it but it was really the same thing I was doing just a different day Sent from my iPhoneOn Dec 24, 2022, at 1:44 PM, Chris ***@***.***> wrote:﻿
Not sure what you have exactly tried. Best thing is to reset via Butter: https://github.com/fpv-wtf/butter
