### ISSUE TITLE
Despues de instalas WTFOS no carga los Packages

### ISSUE THREAD

**Issue by dadidani** [fpv-wtf/wtfos-configurator#259]
Root succeful, install succeful, no show packages

**Comment by stylesuxx** [comment]
Could you provide more info on what is happening? From what I understand you don't see packages in the package installation screen?

**Comment by dadidani** [comment]
Ready, i can install MSP Package, thanks a lot!!!

**Comment by dadidani** [comment]
it is ready thanks a lot!!
