### ISSUE TITLE
No Hd osd on pavo360 vista & no fw list on dji assistant 2

### ISSUE THREAD

**Issue by zorba70** [fpv-wtf/wtfos-configurator#260]
Happy Christmas to you!

...and thank you for the knowledge you re sharing everyday!

I' ve a little more Question : i' ve rooted my googles V2 after downgrade by butter and i' ve update 3 of my vista to wtf os and the fc to betafly 4.4 rc 1 to have the hd osd font and it works fine but on my betafpv pavo 360 ...i' ve done the same the same process and nothing ! No bf osd and no dji custom osd???!!
WTF? (What the fuck!???)

And when i go with all my vista rooted on dji assistant 2 ( fpv or consummer series)
I cant have the firmware list to upgrade vistas even if i remove the wtfos...
WTF!!!??? 

Can you help me again?

Best regards and happy Christmas for you and your family.

Nico the old french guy ...

**Comment by stylesuxx** [comment]
If the stock OSD is not working, then you have some general setup going wrong. Probably serial port is set up incorectly. I would first make sure you get the DJI OSD working before you get the MSP OSD working.

> I cant have the firmware list to upgrade vistas even if i remove the wtfos...

I don't quite understand the question. You can remove wtfOS anytime and run with the official firmware again - in case that answers your question?

**Comment by zorba70** [comment]
Hi 
Thanks for your quick response....
Yes the dji osd was working fine before on pavo 360 with gps datas etc but since i' ve rooted and put wtfos ...i have some dji datas but not the gps one and no canvas mode(hd with bf 4.4 or ckassical with bf 4.3.2)
I' ve open the right port on bf for my vista and add "msp display port "option and cli hd command...but nothing with bf 4.4 rc1 fw and no change with bf 4.3.2 fw?
I' ve thought that it was perhaps the curious electrical configuration of the pavo 360 that was not match with the wftos needs in vista??? 
I ' ve remove wtfos after rooted my vistas to Upgrade them to the last dji fw version but i have an Error screen on dji assistant 2 that is tellin me: " can not load firmware list( 4- 10) please retry....
Can you help me?
Regards

**Comment by stylesuxx** [comment]
If you want to use DJI assistant, you will have to remove wtfOS first, then DJI Assistant will recognize it. With errors in the DJI assistant we can't really help you. Just make sure that you use DJI Assistant 2 for HD FPV.

If the DJI OSD worked, there is no reason for the msp OSD not to work. GPS data will only show when there is actually valid data. I would revert to the original BF state that you had on there, make sure that the "normal" OSD is working and then cleanly set up MSP OSD.

**Comment by zorba70** [comment]
Ok ....
Thanks for all my friend.
I will do so.
Happy Christmas for you and your family.
Best regards.
Nico.

**Comment by zorba70** [comment]
Hi 
Can you explain  why incan read gov150 version 01.00.0607 when i root dji V2 after done butter gp 150 version 01.00.06.06?
Regards

**Comment by zorba70** [comment]
Hi
Can you explain why incan read gp 150 version 01.00.0607 when i root dji V2 after done butter gp 150 version 01.00.06.06?
Regards

**Comment by j005u** [comment]
You see 01.00.0607 after using butter because the current firmware version is stored separately from the actual firmware and butter can't erase that file. This in and of itself shouldn't be a problem.

I would try uninstalling, running "wtfos-remove-adb" in the CLI, reflashing with DJI assistant and starting again.

msp-osd setup is out of scope here, make sure you follow all steps in the README for setup.

**Comment by stylesuxx** [comment]
@zorba70 any update on this? Otherwise I will close the issue.

**Comment by zorba70** [comment]
Ok do it...

**Comment by zorba70** [comment]
Hi
Ok close it.
Thanks
