### ISSUE TITLE
v2 goggles rooting

### ISSUE THREAD

**Issue by chaneytrenching** [fpv-wtf/wtfos-configurator#261]
can't root my dji v2 goggles.  It starts and then,  01:32 Aborted! Device did not reboot in time, please power cycle and try again.  and when I recycle it does the same thing.  what are I doing wrong?

**Comment by stylesuxx** [comment]
Please show the full log. Also make sure that you are on firmware version 0606.

**Comment by ManuPeche** [comment]
I have exactly the same problem.I rebooted the mask manually, lipo and usb but still not working.
![step 2](https://user-images.githubusercontent.com/121618215/209957091-8c58bd82-795d-4c48-b040-6b56387c8019.PNG)

**Comment by MindRiderFPV** [comment]
Check the FW using DJI assistant, the one reported in the goggles can be corrupted. Had the same issue, refreshing 0606 fixed it.

**Comment by chaneytrenching** [comment]
![Web capture_31-12-2022_91226_fpv wtf](https://user-images.githubusercontent.com/16272075/210140227-94d380d0-2498-4ced-8c12-a9ffae177329.jpeg)

**Comment by chaneytrenching** [comment]
![20221231_092610](https://user-images.githubusercontent.com/16272075/210140734-3e5eee53-171f-43bc-bb25-4419e7f0c811.jpg)

**Comment by chaneytrenching** [comment]
![20221231_092405](https://user-images.githubusercontent.com/16272075/210140745-d25a7204-ef70-4548-8743-224e46e6aa23.jpg)

**Comment by chaneytrenching** [comment]
Root times out after saying update successful and that it is version 607.  DJI Assistant shows compatibility issues with 607 on the screen and the compatibility error.  Goggles show 606 installed.  Can someone help me understand what I need to do to correct this issue, or I am going to consider buying Fat Shark Goggles.

**Comment by stylesuxx** [comment]
Refresh your goggle firmware via DJI assistant to 0606. Post FULL screenshots in the future - I can't see which DJI Assistant version you are using...

If all else fails, use https://github.com/fpv-wtf/butter to reset to a known good state.

> ...or I am going to consider buying Fat Shark Goggles.

Such comments are unnecessary. If you want to use Fatshark, use it. Be aware that it will not work with DJI equipment though.

**Comment by DJIBryan** [comment]
Have the same problem, can't root my Goggles V2, it keeps saying: Failed after 10 retries.

Have the latest Firmware on it 01.05.00.00. you keep talking about the Firmware 0606 ?????. But can't find it anywhere when connected to the DJI Assistant 2 (Consumer Drones)

**Comment by DJIBryan** [comment]
> @DJIBryan That is not the correct firmware. Also you have to use DJI Assistant 2 for HD FPV products.

I do have the DJI Assistant 2 (DJI FPV series), but cannot find any DJI Assistant 2 2 for HD FPV products ?? on the DJI Download site.

Could it have something to do with the fact that I live in the Netherlands?

**Comment by stylesuxx** [comment]
Yeah whatever the one is with FPV in the name...

No, this is not a location based issue. Also let me know which version is being shown during rooting process - post a screenshot please.

**Comment by DJIBryan** [comment]
> Yeah whatever the one is with FPV in the name...
> 
> No, this is not a location based issue. Also let me know which version is being shown during rooting process - post a screenshot please.

**Comment by DJIBryan** [comment]
Only have these Firmware there

![Schermafbeelding 2023-01-04 162741](https://user-images.githubusercontent.com/56634636/210590145-8bc551d8-afe9-4c48-bbce-9568645dbb37.jpg)

**Comment by stylesuxx** [comment]
Your goggles are in DIY mode, right? Anyway, you should be able to use Butter to downgrade to a known working state: https://github.com/fpv-wtf/butter

**Comment by DJIBryan** [comment]
Was able to root it, but now it stops here and won't go any further ??

![Schermafbeelding 2023-01-04 214255](https://user-images.githubusercontent.com/56634636/210646441-f73b691d-531a-4ef6-824a-926fe65e1ff2.jpg)

**Comment by stylesuxx** [comment]
15 minutes is steep, but yeah - it depends on your internet connection. You can have a look in the network tab in the inspector, you should see requests going off there (or at least an error in the console)...

**Comment by robustini** [comment]
> 15 minutes is steep, but yeah - it depends on your internet connection. You can have a look in the network tab in the inspector, you should see requests going off there (or at least an error in the console)...

Could you put something during that operation that at least indicates what it is doing?
At least you would be able to tell if it can't download the file, or if it can't do anything else.
Something to show the progress of the operation.
1 Gbit WAN here, tried with other computers in the same network, same problem.
Also tried on a WAN connection in LTE, same thing.
Then I tried a friend's house with a poor ADSL and it took two minutes.
Is it something at the browser level or precisely firewall or antivirus that maybe slows it down, but 15 minutes compared to 2 is an eternity.

**Comment by dronedynamicsusa** [comment]
Can someone PLZ explain how you fixed this screen. Cant seem to get past it and ROOT. In DIY mode, re-installed drivers multiple time. running on V01. 06 (have tried on V01.04 & V01.05; same thing); STUCKK

![Screenshot (2)](https://user-images.githubusercontent.com/118017712/212441267-f57b2762-2cef-4a80-8d0d-bcea266280c6.png)
![Screenshot (3)](https://user-images.githubusercontent.com/118017712/212441270-70aa72ea-9991-443d-abc7-a99bfcebb44b.png)

**Comment by stylesuxx** [comment]
> Could you put something during that operation that at least indicates what it is doing, some kind of debug console? At least you would be able to tell if it can't download the file, or if it can't do anything else. Something to show the progress of the operation.

No, not easily since this is started and then is running in the background and either finishes or fails - only then I can act upon it.

> 1 Gbit WAN here, tried with other computers in the same network, same problem. Also tried on a WAN connection in LTE, same thing. Then I tried with a paltry ADSL at a friend's house and it took two minutes, damn. Is it something at the browser level or precisely firewall or antivirus that maybe slows it down, but 15 minutes compared to 2 is an eternity. But downloading entware at the command line takes a few seconds, LOL, so where is the issue about this long time?

I don't know, I don't have this issue - so you would need to test it on your end, disable firewall, antivirus and see if it changes anything. Again, looking in the network tab is the best way to get a feeling of what is going on - it will show the files being downloaded (or failing) - you can use this data to benchmark the issue.

**Comment by stylesuxx** [comment]
@dronedynamicsusa you are on the wrong firmware. Use butter to downgrade to a know  working state. Please also open a separate issue and don't hijack this one.

**Comment by dronedynamicsusa** [comment]
@stylesuxx It was a v2 goggles rooting question. thanks for the assistance.

**Comment by stylesuxx** [comment]
@dronedynamicsusa yes, and now it is a mix of four different issues. Pleas use butter to downgrade to a known working state and open your own issue in case you run into any problem.

**Comment by dronenoob** [comment]
Having same issue as DJIBryan where it failled after 10 attempts while trying to root
![rootscreensto](https://user-images.githubusercontent.com/122718245/212528789-da470671-9c76-415c-a521-a4c7878ae60e.jpg)

I used butter to flash 0606 already a few times but still same thing. Am i missing something? I have to be in DIY mode?

**Comment by stylesuxx** [comment]
@dronenoob yes you have to be in DIY mode. Also to you: please open your own ticket. Such tickets with 10 people thinking that they have the same problem are a pain to maintain and everyone involved gets notifications if someone posts something.

**Comment by stylesuxx** [comment]
Closing this since it is an absolute mess, if anyone is still having issues, please open a separate ticket.
