### ISSUE TITLE
Can't connect Vista

### ISSUE THREAD

**Issue by EachGlobe** [fpv-wtf/wtfos-configurator#262]
I can't connect my Caddx Vista with the configurator. On the developer version it shows up on the menu but then I get the "adb kill server" error. I tried to upgrade the driver with Zadig like someone else on this GitHub did but unfortunately it still doesn't work. 

Also and I don't know if that's related to the problem. When I connect my Vista the first time it isn't recognized as a USB driver, it's in the devices and printer menu. I always have to connect a second time so that it recognizes it as a USB driver.

**Comment by stylesuxx** [comment]
Can you connect other vistas or goggle? Can you see the vista with the DJI assistant? Which OS are you on, which browser?

**Comment by EachGlobe** [comment]
With my V2 googles everything worked fine. I can see the vista in the DJI assistant. (Also firmware is the right one) I'm using windows 10 and I tried it with Google Chrome and Edge.

**Comment by EachGlobe** [comment]
> With my V2 googles everything worked fine. I can see the vista in the DJI assistant. (Also firmware is the right one) I'm using windows 10 and I tried it with Google Chrome and Edge.

I don't have any other Vistas to try but I could use one of a friend and try it. Atleast I will now if my Vista is the problem or not. My PC should be fine because I tried the same thing on another laptop and the same problems occured.

**Comment by stylesuxx** [comment]
Hmm, if you can see it in the assistant, there should not be an issue with the configurator either. Usually when the adb kill message comes it means that something else is claiming your USB device. It is a bit strange that you need to plug it in twice for it to show up as the correct device. I still suspect a driver issue there.

Just to be on the safe side, try refresshing the firmware from assistant. and by right one you mean 0606 - right?

**Comment by EachGlobe** [comment]
Alright I will try to refresh it tomorrow when I'm back at the office. I will reply here after I tried it. And yes it's the 0606 firmware ;) Thx for your inputs.

**Comment by EachGlobe** [comment]
So.... now the amount of times it needs to be unplugged and plugged in again to be recognized as a USB driver is just random. Sometimes it's 3 times other times 20 times. I tried to refresh the 0606 software multiple times but it always disconnects by itself. Sometimes at 99% during download and a couple of times it went to the next step (transmitting) but never above 0%. 

So yeah unfortunatley nothing changed. Does the naco "hack" interfere with it maybe? Is it possible to reset the vista to factory settings?

**Comment by stylesuxx** [comment]
No, the Naco hack does not interfere in any way. You can try downgrading with butter to a working state and see what is going on. You have tried on diffferent machines and you can confidently say its only this one Vista, not a general problem with vistas on your end, right?

**Comment by EachGlobe** [comment]
I still have to try it with another Vista. I will let you know when I did so. I will try to downgrade my Vista with butter.

**Comment by ibexFPV** [comment]
I've just experienced the same issue as @EachGlobe.

My googles v2 my 1 air unit (no1) pick up perfectly fine in WTFOS Configurator but my other air unit (no2) which I wanted to root does not :(

All are on firmware 0606
All three (Goggles, Air unit 1 & 2) show up in DJI FPV assistant
I've tried multiple cables with all 3, chrome, and even a different laptop, and still only the Goggles and air unit 1 get picked up in WTFOS configurator.

I'm pretty darn confused.

**Comment by stylesuxx** [comment]
@ibexFPV what is air unit no2? Is it a vista? Did you try butter to downgrade to a known working state?

**Comment by ibexFPV** [comment]
Sorry for the confusion, Air unit no2 is just my second air unit. 

Yes, I've tried downgrading and updating to different versions or firmware but it still does not pick up on WTFOS.

What would you suggest is a known working state?

Thanks,

**Comment by stylesuxx** [comment]
OK, but I still don't know if it's an original (big) air unit or a Vista...
Just to be clear, you are in the root tab, and you can not see it in the device selection there, right?

Known working state is the state that you get after running [butter](https://github.com/fpv-wtf/butter).

**Comment by EachGlobe** [comment]
So, I just flashed succesfully with butter but the same problems are still here. Unfortunately nothing changed.

**Comment by ibexFPV** [comment]
@stylesuxx it's an original air unit.
Yes, I'm in the root tab but there is not device available for selection.

I will give butter a try when the power comes back on.

Thanks

**Comment by stylesuxx** [comment]
Closed due to inactivity

**Comment by EachGlobe** [comment]
USBUser[21:25:40] USB device added: path=\\?\usb#vid_2ca3&pid_001f#123456789abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "DJI FPV Air Unit Lite", serial="123456789ABCDEF", driver="usbccgp", guid=6b56d051-bf69-4ef6-aeb4-f51b4482dcbb

USBUser[21:25:35] USB device removed: path=\\?\usb#vid_2ca3&pid_0040#5&153678d8&0&10#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=deee7b29-68d2-43d3-8e01-04c7332a94cc

USBUser[21:25:30] USB device added: path=\\?\usb#vid_2ca3&pid_0040#5&153678d8&0&10#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "", product=64 "", serial="", driver="libusb0", guid=deee7b29-68d2-43d3-8e01-04c7332a94cc

FIDODebug[21:24:44] webauthn.dll version 2

USBError[21:22:28] SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element nicht gefunden. (0x490)

USBUser[21:22:26] USB device removed: path=\\?\usb#vid_2ca3&pid_001f#123456789abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=3d0efbf8-9a0c-41d3-9315-555667d94279

USBUser[21:22:04] USB device added: path=\\?\usb#vid_2ca3&pid_001f#123456789abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "", product=31 "", serial="123456789ABCDEF", driver="usbccgp", guid=3d0efbf8-9a0c-41d3-9315-555667d94279

USBEvent[21:22:04] USB device function updated: guid=3d0efbf8-9a0c-41d3-9315-555667d94279, interface_number=4, path="\\?\usb#vid_2ca3&pid_001f&mi_04#6&3a7fe9b5&1&0004#{86e0d1e0-8089-11d0-9ce4-08003e301f73}", driver="usbser"

USBEvent[21:22:04] USB device function updated: guid=3d0efbf8-9a0c-41d3-9315-555667d94279, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#6&3a7fe9b5&1&0003#{86e0d1e0-8089-11d0-9ce4-08003e301f73}", driver="usbser"

USBUser[21:22:04] USB device added: path=\\?\usb#vid_046d&pid_c52b#5&153678d8&0&12#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=1133 "Logitech", product=50475 "USB Receiver", serial="", driver="usbccgp", guid=cd33250a-3b5a-45c8-8991-f63b24c9f8dc

USBUser[21:22:04] USB device added: path=\\?\usb#vid_044f&pid_b660#5&153678d8&0&3#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=1103 "Thustmaster", product=46688 "T500 RS Gear Shift", serial="", driver="HidUsb", guid=60c6d660-99b4-4a1f-8c43-bd4c222d9527

USBUser[21:22:04] USB device added: path=\\?\usb#vid_1b1c&pid_0c29#6&c50e7f0&0&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=6940 "Corsair Inc.", product=3113 "H60iRGBPROXT", serial="", driver="HidUsb", guid=76fd1333-36f6-40ee-9435-ee648d01e9c4

USBUser[21:22:04] USB device added: path=\\?\usb#vid_0b05&pid_19af#9876543210#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=2821 "AsusTek Computer Inc.", product=6575 "AURA LED Controller", serial="9876543210", driver="usbccgp", guid=f1f102d2-214f-456c-b5ce-eb6ecd34f422

USBUser[21:22:04] USB device added: path=\\?\usb#vid_044f&pid_b371#5&153678d8&0&8#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=1103 "Thrustmaster", product=45937 "Sim Pedals", serial="", driver="usbccgp", guid=42506458-808a-4376-b4ce-395e4f06b2d9

USBUser[21:22:04] USB device added: path=\\?\usb#vid_0b05&pid_190e#00e04c239987#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=2821 "", product=6414 "", serial="00E04C239987", driver="BTHUSB", guid=7bcca5d2-9601-4a91-bd46-c4d7d677456c

USBError[21:22:04] Failed to read descriptor from node connection: Ein an das System angeschlossenes Ger�t funktioniert nicht. (0x1F)

USBUser[21:22:04] USB device added: path=\\?\usb#vid_044f&pid_b692#5&153678d8&0&7#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=1103 "Thrustmaster", product=46738 "Thrustmaster TS-XW Racer", serial="", driver="tmhidusb", guid=573e9efa-558c-43c8-a3de-d7d6c49d35c7

USBError[21:22:04] Failed to read descriptor from node connection: Ein an das System angeschlossenes Ger�t funktioniert nicht. (0x1F)

USBUser[21:22:04] USB device added: path=\\?\usb#vid_1b1c&pid_0c2a#8009107020d184aa93ddfa061091005f#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=6940 "Corsair", product=3114 "CORSAIR iCUE COMMANDER CORE XT", serial="8009107020d184aa93ddfa061091005f", driver="usbccgp", guid=ea406e5c-4540-42c2-b839-c450538c1133

USBError[21:22:04] Failed to read descriptor from node connection: Ein an das System angeschlossenes Ger�t funktioniert nicht. (0x1F)

USBError[21:22:04] Failed to read descriptor from node connection: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. (0x3E3)

USBError[21:21:59] Could not read device interface GUIDs: Das System kann die angegebene Datei nicht finden. (0x2)

BluetoothEvent[21:21:56] BluetoothAPI: 0000798C0015D340
