### ISSUE TITLE
O3 and Caddx Vista Compatability

### ISSUE THREAD

**Issue by bobbycisneros** [fpv-wtf/wtfos-configurator#263]
Team,

Installing of the 1.05.000 firmware renders the MSP OSD inoperable when switching the googles from O3 back to DJI Digital FPV. 

I have had very good success with WTFOS so thanks a ton for what you have done.  I purchased an O3 air unit and went through the upgrade steps of 1) Update the digital FPV system to the latest firmware using the assistant FPV edition to firmware version 1.00.0607 then I switched to the assistant consumer drone version and installed firmware 1.05.000.  Since I plan to run both Vista and O3 units I am testing the steps to swap between the two systems.  In the googles, when switching from the O3 system back to the digital FPV system, I found the MSP OSD feature for the Caddx was no longer functional.  I restored the MSP OSD by connecting to the WTF configurator and running the "fix".  But, in doing so, I could no longer switch back to the DJI O3 system without updating the firmware in then consumer drone assistant.  Installing of the 1.05.000 firmware renders the MSP OSD inoperable when switching the googles from O3 back to DJI Digital FPV. 

Robert

P.S. I also have to re-bind my VTXs whenever I make the switching between O3 and the DJI digital FPV system.

**Comment by j005u** [comment]
There's an issue where sometimes assistant will only update one firmware slot and you'll end up in the situation you're describing.

Run the following commands in the CLI and after that let the configurator do it's automatic fixes.

```
unrd slot_1.status_successful 0
unrd slot_1.status_active 0
unrd slot_2.status_active 1
reboot
```

This will trigger the configurator to use a cached update image on the goggles to re-flash the second, unflashed slot.

The problem should go away after that. Note that you'll probably need to re-install wtfos after doing so.

**Comment by stylesuxx** [comment]
Does not matter, as long as you can connect to the CLI you can enter the commands.
