### ISSUE TITLE
OSD Overlay encoder error

### ISSUE THREAD

**Issue by kubru** [fpv-wtf/wtfos-configurator#264]
Hi. For a week I can't overlay the recorded osd on my video. Updated to the latest version, selected fonts, tried absolutely everything, this error is issued every time. Please help me solve it.
![2023-01-07_15-31-50](https://user-images.githubusercontent.com/48690185/211151064-02454228-223c-4983-9459-f5336f1e7a82.png)
![2023-01-07_15-32-16](https://user-images.githubusercontent.com/48690185/211151065-a2c89d9d-7e4e-4adf-8a67-c248f1580109.png)
![2023-01-07_15-32-28](https://user-images.githubusercontent.com/48690185/211151066-541683c6-4462-4ad6-9cec-9cc58cba26f7.png)

**Comment by stylesuxx** [comment]
@Knifa - any input on this issue?

**Comment by stylesuxx** [comment]
@kubru - any update on this? Otherwise I will close this issue.

**Comment by stylesuxx** [comment]
Closed due to lack of response.
