### ISSUE TITLE
Goggles V2: more than 10 minutes to install entware?

### ISSUE THREAD

**Issue by robustini** [fpv-wtf/wtfos-configurator#266]
From the console I can't see anything to help, but systematically entware installs after about 15 minutes, doesn't seem normal to me.
I remember well that until a few months ago it took less than a minute here.
I think it would be helpful to add something visible in the console as it takes these steps, so we can see where the problem lies.
Tried with two different computers, on different WAN connection, identical problem.
Trace ID: 8f62f950-c428-41f4-9e53-6c2e4133bf0e

![immagine](https://user-images.githubusercontent.com/3864712/212016235-c1150924-4948-4411-9282-2f1da33b7234.png)

**Comment by stylesuxx** [comment]
Check the network tab, see how long it takes to fetch the entware related files. Last month we made a mirror of entware and are [using that](https://github.com/fpv-wtf/wtfos-configurator/commit/a626aaa6759f1425e5dcec27a7ef6d3beeadcf6a). I don't think that this is the issue though, since I don't see it on my end and you mentioned in the other ticket that it's working fine on one of your friends computers too.

To confirm, try the version before this commit and see if this changes anything for you.

**Comment by robustini** [comment]
> Check the network tab, see how long it takes to fetch the entware related files. Last month we made a mirror of entware and are [using that](https://github.com/fpv-wtf/wtfos-configurator/commit/a626aaa6759f1425e5dcec27a7ef6d3beeadcf6a). I don't think that this is the issue though, since I don't see it on my end and you mentioned in the other ticket that it's working fine on one of your friends computers too.
> 
> To confirm, try the version before this commit and see if this changes anything for you.

If it's been about a month since you changed this imho then it's definitely that.

**Comment by paulpwi** [comment]
Any updates on this issue?   I'm having the same exact problem.  Does entware get loaded after 15min?  Was there a link for the earlier version provided?   Thanks

**Comment by stylesuxx** [comment]
> Any updates on this issue? I'm having the same exact problem. Does entware get loaded after 15min? Was there a link for the earlier version provided? Thanks

You can clone the repository and run any version locally. Unfortunately I can not reproduce the issue on my end, so I need your help in debugging this. A log from the network tab would already help immensely. Try wtfOS installation and record it with a screen grabber having the browsers network tab in the debugger opened.

**Comment by robustini** [comment]
Locked there, and transferring at 4k/sec.

![immagine](https://user-images.githubusercontent.com/3864712/213651157-429daf0c-85be-4910-8b0a-18f978ef4378.png)

**Comment by robustini** [comment]
Second attempt, after a slot fix, stuck there.

![immagine](https://user-images.githubusercontent.com/3864712/213652845-f749cbb0-ea1e-4140-b79a-85faa123d4cd.png)

**Comment by j005u** [comment]
> If it's been about a month since you changed this imho then it's definitely that. Others on Discord have also reported this issue. Surely you will do before me, if you can put the 1.0.0 somewhere and leave me the test url I will try with a Caddx, obviously the problem does with that too. That way I could do a comparison in a moment. I'd rather not touch the Goggles now that I've managed to put up 1.06 with all the features for O3 active.

The whole reason we changed over to our own mirror was that the entware one was having issues and thus people would get stuck at this install step.

Judging by the screenshots, it appears that the downloads are completely fine (100-200ms per file), the strange part is that it's taking so long in between each download.

@stylesuxx I have no better ideas on this topic than to just console.log each command we execute and the results along with timestamps. It'll likely be useful in future debug cases as well.

Do you think you could add this soon-ish, or should I take a look at it?

**Comment by stylesuxx** [comment]
@j005u well, the logs are there, just the installation is one step, I show output once it is done, no matter if it fails or succeeds.

I think it would be best here to trigger the installation via CLI and see what the output is. For me this looks as if everything is working fine, until the end where some prompt might show up where the user would need to interact with...

@robustini could you try and run the entware installation from the CLI and post a log:
```
export PATH=$PATH:/opt/bin:/opt/sbin:/system/bin
export http_proxy="http://127.0.0.1:8089"
wget -q -O - http://repo.fpv.wtf/entware-armv7sf-k3.2/installer/alternative.sh | sh
```

**Comment by robustini** [comment]
> export PATH=$PATH:/opt/bin:/opt/sbin:/system/bin

/system/bin/sh: wget: not found

**Comment by stylesuxx** [comment]
You ran the commands after the install hangs? Seems like the other things are not in place if `wget` is not being found.

**Comment by robustini** [comment]
> You ran the commands after the install hangs? Seems like the other things are not in place if `wget` is not being found.

Sorry, I didn't realize I had to switch to CLI when the install hangs, I run it after the slot fix, I'll try again tomorrow.

**Comment by stylesuxx** [comment]
Feel free to ping me on discord on the weekend, I could try connecting remotely and see if I can find anything from there.

**Comment by robustini** [comment]
> wget -q -O - http://repo.fpv.wtf/entware-armv7sf-k3.2/installer/alternative.sh | sh

This is the output:

Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Warning: Folder /opt/bin exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/etc exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/lib/opkg exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/tmp exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/var/lock exists!
Warning: If something goes wrong please clean /opt folder and try again.
Info: Opkg package manager deployment...
Connecting to 127.0.0.1:8089 (127.0.0.1:8089)
saving to '/opt/bin/opkg'
opkg                 100% |********************************|  734k  0:00:00 ETA
'/opt/bin/opkg' saved
Connecting to 127.0.0.1:8089 (127.0.0.1:8089)
saving to '/opt/etc/opkg.conf'
opkg.conf            100% |********************************|   176  0:00:00 ETA
'/opt/etc/opkg.conf' saved
Info: Basic packages installation...
Collected errors:
 * opkg_conf_load: Could not lock /opt/tmp/opkg.lock: Resource temporarily unavailable.
Collected errors:
 * opkg_conf_load: Could not lock /opt/tmp/opkg.lock: Resource temporarily unavailable.
Collected errors:
 * opkg_conf_load: Could not lock /opt/tmp/opkg.lock: Resource temporarily unavailable.
Info: Congratulations!
Info: If there are no errors above then Entware was successfully initialized.
Info: Add /opt/bin & /opt/sbin to $PATH variable
Info: Add "/opt/etc/init.d/rc.unslung start" to startup script for Entware services to start
Info: Use ssh server from Entware for better compatibility.
Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues

**Comment by stylesuxx** [comment]
I did not catch you on Discord: opkg being locked indicates that the previous process did not complete. I think we need to start from a clean state, you will have to move busybox first though, since you need to use the version which is moved there during installation and it will be wiped once you apply the healthcheck fixes:

```
cp /opt/bin/busybox /blackbox/busybox.bak
```
then apply the health check fixes which will remove the broken install.

From this clean state trigger the installation manually:

``` bash
# create dir
mkdir -p /blackbox/wtfos/opt/bin

# remoutning FS
mount -o rw,remount /
mkdir -p /bin

# Link everything in place
ln -sf /system/bin/sh /bin/sh
ln -sf /blackbox/wtfos/opt /opt

# Setup busybox and link wget
cp /blackbox/busybox.bak /opt/bin/busybox 
chmod u+x /opt/bin/busybox
ln -sf /opt/bin/busybox /blackbox/wtfos/opt/bin/wget

# Run entware installation
export PATH=$PATH:/opt/bin:/opt/sbin:/system/bin
export http_proxy="http://127.0.0.1:8089"
wget -q -O - http://repo.fpv.wtf/entware-armv7sf-k3.2/installer/alternative.sh | sh
```

**Comment by robustini** [comment]
> ```shell
> /blackbox/wtfos/opt/bin/wget
> ```

I've follow all your steps, no errors but:

root@pigeon_wm150_tiny:/ # wget -q -O - http://repo.fpv.wtf/entware-armv7sf-k3%3E
/system/bin/sh: /opt/bin/wget: No such file or directory

**Comment by stylesuxx** [comment]
Alright, so the output when triggering installation manually is like so:

```
tf/entware-armv7sf-k3.2/installer/alternative.sh | sh                         <
Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Warning: Folder /opt/bin exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/etc exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/lib/opkg exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/tmp exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/var/lock exists!
Warning: If something goes wrong please clean /opt folder and try again.
Info: Opkg package manager deployment...
Connecting to 127.0.0.1:8089 (127.0.0.1:8089)
opkg                 100% |*******************************|   734k  0:00:00 ETA
Connecting to 127.0.0.1:8089 (127.0.0.1:8089)
opkg.conf            100% |*******************************|   176   0:00:00 ETA
Info: Basic packages installation...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Installing busybox (1.35.0-3) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/busybox_1.35.0-3_armv7-3.2.ipk
Installing libgcc (8.4.0-11) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libgcc_8.4.0-11_armv7-3.2.ipk
Installing libc (2.27-11) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libc_2.27-11_armv7-3.2.ipk
Installing libssp (8.4.0-11) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libssp_8.4.0-11_armv7-3.2.ipk
Installing libpthread (2.27-11) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libpthread_2.27-11_armv7-3.2.ipk
Installing librt (2.27-11) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/librt_2.27-11_armv7-3.2.ipk
Installing libubox (2022-09-27-ea560134-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libubox_2022-09-27-ea560134-1_armv7-3.2.ipk
Installing libjson-c (0.16-2) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libjson-c_0.16-2_armv7-3.2.ipk
Installing jsonfilter (2018-02-04-c7e938d6-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/jsonfilter_2018-02-04-c7e938d6-1_armv7-3.2.ipk
Configuring libgcc.
Configuring libc.
Configuring libpthread.
Configuring libssp.
Configuring librt.
Configuring libubox.
Configuring libjson-c.
Configuring jsonfilter.
Configuring busybox.
Warning: '/opt/bin/wget' is already exists, skipping.
Installing entware-opt (227000-3) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/entware-opt_227000-3_all.ipk
Installing libstdcpp (8.4.0-11) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libstdcpp_8.4.0-11_armv7-3.2.ipk
Installing entware-release (1.0-2) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/entware-release_1.0-2_all.ipk
Installing zoneinfo-asia (2022f-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/zoneinfo-asia_2022f-1_armv7-3.2.ipk
Installing zoneinfo-europe (2022f-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/zoneinfo-europe_2022f-1_armv7-3.2.ipk
Installing findutils (4.9.0-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/findutils_4.9.0-1_armv7-3.2.ipk
Installing terminfo (6.3-1a) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/terminfo_6.3-1a_armv7-3.2.ipk
Installing libpcre2 (10.37-2) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/libpcre2_10.37-2_armv7-3.2.ipk
Installing grep (3.8-2) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/grep_3.8-2_armv7-3.2.ipk
Installing locales (2.27-9) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/locales_2.27-9_armv7-3.2.ipk
Installing opkg (2022-02-24-d038e5b6-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/opkg_2022-02-24-d038e5b6-1_armv7-3.2.ipk
Installing entware-upgrade (1.0-1) to root...
Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/entware-upgrade_1.0-1_all.ipk
Configuring terminfo.
Configuring libpcre2.
Configuring grep.
Configuring locales.
Entware uses separate locale-archive file independent from main system
Creating locale archive /opt/usr/lib/locale/locale-archive
Adding en_EN.UTF-8
Adding ru_RU.UTF-8
You can download locale sources from http://bin.entware.net/other/i18n_glib227.tar.gz
You can add new locales to Entware using /opt/bin/localedef.new
Configuring entware-upgrade.
Upgrade operations are not required.
Configuring opkg.
Configuring zoneinfo-europe.
Configuring zoneinfo-asia.
Configuring libstdcpp.
Configuring entware-release.
Configuring findutils.
Configuring entware-opt.
Info: Congratulations!
Info: If there are no errors above then Entware was successfully initialized.
Info: Add /opt/bin & /opt/sbin to $PATH variable
Info: Add "/opt/etc/init.d/rc.unslung start" to startup script for Entware services to start
Info: Use ssh server from Entware for better compatibility.
Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues
```
And at this point the script just HANGS, we are not being dropped back to the shell. This process goes through in the time you would expect it to finish.

Currently we are waiting for me to being dropped back to the shell, @robustini says that this will happen at some point.

So yeah, we need to inspect the entware installation script and see why it might be hanging there...

**Comment by j005u** [comment]
My gut feeling says wget thinks it's waiting for more data from the proxy and just chills there, so sh never reaches EOF. Something to do with content-length headers once again?

**Comment by stylesuxx** [comment]
Ahh, yeah - good point, that's the only thing that's left making sense. Since the alternate script ends with the "Found a bug?" message.

**Comment by robustini** [comment]
> My gut feeling says wget thinks it's waiting for more data from the proxy and just chills there, so sh never reaches EOF. Something to do with content-length headers once again?
> 
> If we can't figure out the underlaying issue then adding a timeout flag to wget might also help, I suspect 15 minutes is the default.

Yeah, 10 minutes, sorry:

wget: download timed out

**Comment by stylesuxx** [comment]
For some reason the content-length headers are missing on @robustini's setup:

```
HTTP/1.1 200 
  cache-control: max-age=600
  content-type: application/x-sh
  expires: Sat, 21 Jan 2023 16:25:19 GMT
  last-modified: Thu, 29 Dec 2022 22:01:34 GMT
```

**Comment by stylesuxx** [comment]
The problem was that the content-length header was missing. The fix is to skip the content-length header in case it is available and simply attach it always in the end with the actual size of the buffers content.

**Comment by robustini** [comment]
#276
