### ISSUE TITLE
DJI V1 goggles, Ran Butter successfully, Rooted, but can't install WTFOS

### ISSUE THREAD

**Issue by quaddude** [fpv-wtf/wtfos-configurator#267]
V1 goggles, I loaded latest DJI firmware (too high for WTFOS)
Ran Butter. It completed successfully. It reported version V01.00.0608
Did the Root, completed all 5 steps report success.
Here is my issue-
The next step is to load WTFOS.
I am in the WTFOS selection, it sees my goggle
"DJI FPV Goggles V1-67C"
But the bar "Install WTFOS" is greyed out. 
I am not able to install WTFOS
v1.0.1 - Trace ID: 382c097c-4efd-4917-b8c8-0426c54eded2
When I go into DJI assistant it now gives an error "Cannot load firmware list (4-10) Please retry"

**Comment by stylesuxx** [comment]
Can you open the CLI in the configurator?

**Comment by quaddude** [comment]
I can get to the CLI (looked at the directories)

**Comment by quaddude** [comment]
/opt/bin/opkg is not there -

root@pigeon_wm150_gls:/ # ls -l
drwxr-xr-x root     root              2023-01-12 17:30 amt
drwxr-xr-x root     root              2023-01-12 11:22 blackbox
drwxr-xr-x root     root              2022-12-18 19:26 cache
drwxr-xr-x root     root              2023-01-12 17:30 data
-rw-r--r-- root     root          410 1970-01-01 00:00 default.prop
drwxr-xr-x root     root              2023-01-12 17:30 dev
lrwxrwxrwx root     root              2023-01-12 17:30 etc -> /system/etc
drwxr-xr-x root     root              2018-01-14 20:56 factory_data
-rw-r--r-- root     root        16640 1970-01-01 00:00 file_contexts
-rw-r----- root     root         1267 1970-01-01 00:00 fstab.pigeon
drwxr-xr-x root     root              2023-01-12 17:30 ftp
-rwxr-x--- root     root       637776 1970-01-01 00:00 init
-rwxr-x--- root     root          540 1970-01-01 00:00 init.environ.rc
-rwxr-x--- root     root         2096 1970-01-01 00:00 init.pigeon.usb.configfs.rc
-rwxr-x--- root     root        10119 1970-01-01 00:00 init.rc
-rwxr-x--- root     root         1921 1970-01-01 00:00 init.trace.rc
-rwxr-x--- root     root         8457 1970-01-01 00:00 init.usb.rc
drwx------ media_rw media_rw          2023-01-12 17:30 mnt
dr-xr-xr-x root     root              1970-01-01 00:00 proc
-rw-r--r-- root     root         3461 1970-01-01 00:00 property_contexts
drwxr-xr-x root     root              1970-01-01 00:00 res
drwx------ root     root              2020-06-22 20:22 root
drwxr-x--- root     root              2023-01-12 17:30 sbin
-rw-r--r-- root     root          596 1970-01-01 00:00 seapp_contexts
-rw-r--r-- root     root           80 1970-01-01 00:00 selinux_version
-rw-r--r-- root     root       174492 1970-01-01 00:00 sepolicy
-rw-r--r-- root     root         9769 1970-01-01 00:00 service_contexts
drwxr-xr-x root     root              2023-01-12 17:30 storage
dr-xr-xr-x root     root              2023-01-12 17:30 sys
drwxr-xr-x root     root              1970-01-01 00:00 system
drwxrwxrwt root     root              2023-01-12 17:30 tmp
-rw-r--r-- root     root         4587 1970-01-01 00:00 ueventd.rc
drwxrwxrwt root     root              2023-01-12 17:30 var
drwxr-xr-x root     root              1970-01-01 00:00 vendor
-rw-r--r-- root     root          524 1970-01-01 00:00 verity_key

**Comment by stylesuxx** [comment]
This is extremely wired... if opt is not present, then the only reason why it would be grayed out is if the health checks failed, the configurator would show this though. Can you post a screenshot of the home screen after connecting please?

I think the easiest option would be to join discord and ping me there, we could have a 1:1 session where I connect to your device and have a look.

**Comment by quaddude** [comment]
I plugged in the goggles and (I don't understand what changed) I was able to
![Startup](https://user-images.githubusercontent.com/99520086/212437969-2ff22b81-b1b9-4e3c-b9e3-76819defb199.JPG)
 load WTFOS !!
I was monitoring the process and saw /opt was created. It finished error free.
I was able to load packages.
I think this issue can be closed. Thank-you!
