### ISSUE TITLE
Trying to root the v1. It have the 0606. Fw. I connect the Goggles and start the step on but after 30s it fails and show me a webpage problem. 

### ISSUE THREAD

**Issue by Photozulu** [fpv-wtf/wtfos-configurator#268]
Tryin to root the V1's it only start step 1 and it said server error. I did all the process with my V2 and it did all the root and installing os the driver  but at the end the osd is not showing in the goggles. Any help will be very welcome!!! Is not a good idea to fly without OSD. I guess it can be that this is my first build. with mu ARF quads I got the osd from factory. But maybe I miss something in the way.

Cheers guys!

**Comment by stylesuxx** [comment]
Which problem are we trying to solve here? The V1's not rooting or the OSD not showing on the V2's?

For the V1's not flashing please post the exact error that you are getting - screenshot of the whole root process.

Regarding OSD not showing - which OSD do you mean, the stock DJI OSD or the MSP OSD?

**Comment by Photozulu** [comment]
Hey stylesuxx !!! Im focus on the V1 at the moment. Just try again and in step 2 it goes to Aw,snap something went wrong when displaying this website.
Error code: STATUS_ACCES_VIOLATION.
It happens every time I try to root.
Thanks for the help!!

**Comment by Photozulu** [comment]
![wtf](https://user-images.githubusercontent.com/16760481/212291456-8bf62487-d6ee-42a4-b20e-e7e2001c661f.png)

**Comment by Photozulu** [comment]
With the Version 2 I don't get the MSP osd. But I think first I would like the V1 to work.

**Comment by Photozulu** [comment]
I first try the microsoft Edge but also though that could be the reason and installed Chrome but the outcome was the same. The pc is new. I just bough it for this task. Yes would love to be helped. I'm gonna give it a try. Thanks!

**Comment by Photozulu** [comment]
Had change cable, usb port, restarted the pc and it always send me to the same bricked page.

 Would you guys recommend me to try with the goggles v2 instead,  as I did already the rooting and installers also did the BF part for the SMP osd. On PAL.  But it didn't show after all the process.  In that case I will create another issue for the V2's.

**Comment by stylesuxx** [comment]
The dev version gives you the same result?

Regarding MSP OSD, please read the Readme in the msp-osd repo. It is probably a configuration issue, if that does not help, open a separate issue - thanks.

**Comment by Photozulu** [comment]
Yes I tried the dev link you gave me and it was the same. after starting step 2 it goes to the warning page . 
Thanks a lot stylesuxx!!! I will do that. tomorrow I will create the separated issue.

**Comment by stylesuxx** [comment]
@Photozulu any update on this? Otherwise I will close the issue.

**Comment by stylesuxx** [comment]
Closed du to lack of response.
