### ISSUE TITLE
OSD Overlay Video Output Quality

### ISSUE THREAD

**Issue by TheFrisco** [fpv-wtf/wtfos-configurator#271]
I used your OSD overlay feature for a few times last week and it put out great video. But yesterday, it seems I get very low quality output, heavily pixelated and the file size is much too small (11MB) for what I put in before (520MB).

Something broke or me?

**Comment by stylesuxx** [comment]
Probably you. Try the same files you tried before and see if you get the same output.

**Comment by TheFrisco** [comment]
Sorry no, any of my files do that now and I haven't changed a thing.

[image: photo]
*Robert Schmid*

+1 (408) 805-5450 <+1+(408)+805-5450> | ***@***.***

theschmids.org
<https://www.youtube.com/channel/UCpA0wWoSCmc7end0Xrck8Kg>
<http://facebook.com/roberteschmid> <http://linkedin.com/in/roberteschmid>
<http://twitter.com/roberteschmid>
"Age is something that doesn't matter, unless you are a cheese." - Luis
Bunuel.

**Comment by Knifa** [comment]
Maybe something going wrong here with the bitrate detection? It tries to match the input video's bitrate. 

https://github.com/Knifa/wtfos-configurator/blob/knifa/rec-overlay/src/osd-overlay/processor.ts#L151-154

**Comment by Ddraig62SPD** [comment]
@Knifa Hi. Further to our chat earlier today about this issue. I just managed to test the overlay functionality on my antique Win10/32-bit laptop and .... and (like your testing) the processed overlay file looked absolutely fine. It looks increasingly like a Mac-related issue (both Intel/Catalina & M1/Ventura variants). For convenience I added the 'low quality' processed overlay file to the source .mp4/.osd files and font files that I used on my shared [google drive folder](https://drive.google.com/drive/folders/1qBXl_rMhqj7v9kq96IHAA86Q2D_fHSQE). If you need any more details please let me know. Thx again for the support and for the fantastic dev effort :)

**Comment by Ddraig62SPD** [comment]
Update: I installed a 14-day trial of Parallels 18 onto my Mac Mini M1 and had some success. The correctly processed file with Knifa fonts has been uploaded to the same google drive folder as before (also worked for SeakyFPV fonts). I'll keep my eye on this ticket for any updates. Thx

**Comment by Knifa** [comment]
I gave it a go today on my M1 work MacBook and it processed successfully, so not too sure where to go from here. Even tried with and without charging on a hunch it was forcing some low-perf mode to save battery.

It feels like the bitrate setting is being ignored, though. It processes fine but the bitrate is just being yanked low for some reason? Maybe can add a manual tweak and see if overriding helps.

**Comment by Ddraig62SPD** [comment]
@Knifa Much appreciated. Is is possible to provide a link to your older version of the overlay tool that worked for me on my Intel/M1 Macs 2-3 months ago (the version where only 2 font files needed to be uploaded)? It would be interesting to see if it still works on my hardware; it might also provide a clue to the failure mechanism and possible manual tweaks. Happy to be a guinea-pig ;) Thx

**Comment by 3dcadfreak** [comment]
Hi guys, just experienced the same on my '21 MacBook Pro 14" with Apple M1 Pro and macOS Monterey 12.3.1. Great speed of video conversion but 1/100 the file size of original file. Started my old Win10 machine using the same files and overlayed the OSD in perfect quality. Up to ca. 3 weeks ago the MBP worked just fine. Thanks for the great work!

**Comment by kdosiodjinud** [comment]
Hi, i have same issue, Macbook with M1 (but it was working on december 22). I started project on localhost and set bitrate "hardcode" - not working and changes not affect output file size, I try set framerate to 30 and different output codec, but still not working. :( Nice feature, bu not working for me now. I'm 🤞 that a solution can be found :)

**Comment by Ddraig62SPD** [comment]
Haven't been able to test again since moving to the official BF 4.4 release as my Parallels trial on my M1 Mini is over. Moreover, the only quad I own which was running BF 4.4 is now at the bottom of a lake after a schoolboy error on the day I maidened it. First LiPo was fine and the RTH worked fine but on the second pack I accidentally flicked the disarm switch instead of disabling the RTH switch! :( I normally use stick arming so my muscle memory was off base!! I have the GPS co-ordinates from the goggles DVR but just waiting on a local sub-aqua club to get permission to conduct a rescue dive for the drone ... plus the attached GoPro Mini 11. Happy days!

**Comment by kdosiodjinud** [comment]
@Knifa @Ddraig62SPD i can provide my videos for debuging (if @Ddraig62SPD is out of business :D - sorry, i sympathize with you). My files: https://drive.google.com/drive/folders/17d7YmHF41GkQO0MwS2crjUjbt18HJ1vK?usp=sharing

**Comment by Ddraig62SPD** [comment]
@Knifa @kdosiodjinud Thanks! I tried with your files on my Intel Macbook Pro but no success I'm afraid. Still the same issues.

**Comment by 3dcadfreak** [comment]
I think it's pretty clear that the files are not the problem ;-)

**Comment by Ddraig62SPD** [comment]
@3dcadfreak Agreed. Looks like a hardware/OS/browser issue. Tough to debug. The fact that we have full HD OSD overlay on the DVR with BF 4.4 is a godsend :)

**Comment by rdamron** [comment]
Having the same issue on a Macbook Pro m1 running: 
Ventura 13.1 (22C65). 
Chrome 110.0.5481.77

2.16GB source file, 80mb output file.

**Comment by dismaldunc** [comment]
I have that same issues on an M1 macbook pro, it also worked great a while back.  my output file is about 10% of the size of the original vid file, but if it works on Window I shall go and do it there, thanks again SO much for all the fabulous work you have done for us all. you are awesome ( even the cool kids think so!)

**Comment by Knifa** [comment]
My guess is this is a new Chrome issue or something to do with how the encoder wants configured, though I can't say it's obvious. 

https://github.com/Knifa/wtfos-configurator/blob/knifa/rec-overlay/src/osd-overlay/processor.ts#L136

There's not exactly much to tweak though.

The thing is, I have an M1 Macbook for work and it works fine for me so I'm stumped.

**Comment by Knifa** [comment]
I can actually replicate this on my work Mac now so I'll have a look.

**Comment by Knifa** [comment]
Adding `scalabilityMode: "L1T2",` seemed to fix it, whatever that actually means.
https://github.com/Knifa/wtfos-configurator/commit/81056fd8c7703aaaf032b179322a4163190d61a1

**Comment by Ddraig62SPD** [comment]
@Knifa It worked on my old Intel MacBook Pro. What a hero!! Overlay file similar size to original .mp4. Bravo Dan!! :)

**Comment by stylesuxx** [comment]
@Knifa - this is now fixed with your last push - right?

**Comment by Knifa** [comment]
> @Knifa - this is now fixed with your last push - right?
Yes! So it was included in the PR. 💪

**Comment by kdosiodjinud** [comment]
Yes, actual version is OK! 👍 thank you
