### ISSUE TITLE
failed after 10 retries 

### ISSUE THREAD

**Issue by Txsthomas8420** [fpv-wtf/wtfos-configurator#273]
when rooting, after going through the butter steps, i start to root my goggles v2 and receive a message saying "00:33 Failed after 10 retries." it sits and does nothing else until i power off the goggles or unplug them. The goggles were brand new and had the latest firmware. I thought i was out of luck until i heard about butter, maybe i still am...

00:03 Attempting Step 1...

00:33 Failed after 10 retries.

**Comment by stylesuxx** [comment]
After going through butter it should work. You are in DIY mode, right?

What does DJI Assistent show you when you connect?

**Comment by Txsthomas8420** [comment]
that did it! sorry to be a bother... it was not in diy mode and once i did that the goggles rooted like i thought they should. could have sworn i was in diy mode but alas... thanks for the help!!!
