### ISSUE TITLE
cant connect multiple vista units

### ISSUE THREAD

**Issue by sbladesltd** [fpv-wtf/wtfos-configurator#277]

**Comment by stylesuxx** [comment]
Yes, that's by design. Only one device is supposed to be connected at one time.

**Comment by stylesuxx** [comment]
You are in the root tab? And the devices don't show up in the device selection? Or do they show up and you can't root? Which firmware version did you flash exactly?

Please always provide as much information as possible, otherwise debugging is very painstaking.

**Comment by stylesuxx** [comment]
Closed due to lack of activity.
