### ISSUE TITLE
adb server

### ISSUE THREAD

**Issue by Flatfoot157** [fpv-wtf/wtfos-configurator#279]
I just rooted my V1 DJI goggles by using Google Chrome on my Mac. The root went great and I'm having problems completing the process since fpv.wtf wont continue due to the adb server is not turned off. Unable to locate a adb server on my Mac. Can anyone help me.
Thanks

**Comment by magixfly** [comment]
copied from wtf.os configurator:

When wtfos is started, the /system partition is overwritten with a writable copy of the partition kept in /blackbox/wtfos/system.img

If you hold the bind button down during boot **wtfos startup will be skipped with adb enabled** to allow for wiping of wtfos or diagnosis

If wtfos detects any fatal issues, it will likewise attempt to boot up without any modifications and with adb enabled

**Comment by stylesuxx** [comment]
@Flatfoot157 did you get this sorted, or do you need assistance still?

**Comment by Flatfoot157** [comment]
I got it figured out. It’s working great. Thanks for the help. Sent from my iPhoneOn Feb 6, 2023, at 2:36 AM, Chris ***@***.***> wrote:﻿
@Flatfoot157 did you get this sorted, or do you need assistance still?
