### ISSUE TITLE
Cant install WTFOS Googles 2

### ISSUE THREAD

**Issue by Poxan100** [fpv-wtf/wtfos-configurator#280]
- Buy new
- updated to 606
- rooted seccesfully
- trying to install WTFOS and hanging at
"Found "pigeon_wm170_gls"
Creating basic directory structure...
Remounting file-system...
Moving busybox into place...
Linking wget...
Installing entware (can take a couple of minutes)..."

- wiping,
- "WTFOS_DIR=/blackbox/wtfos
if [ -d "$WTFOS_DIR" ] ; then
    echo "cleaning up previous wtfos in /blackbox"
    rm -rf "$WTFOS_DIR"
    rm -rf /blackbox/wtfos.log
    echo "wtfos cleaned up, please reboot your device and try installing wtfos again"
    echo "you may use 'reboot' to do so"
else
    echo "wtfos install not found, aborting"
    exit 1
fi"
- "unrd product_type wm150_gls
reboot"
NOT HELPED

Guys please help to install WTFOS

**Comment by stylesuxx** [comment]
There is a fix for this issue, I have not yet deployed it though. Maybe I get to it later today. for the time being just wait for 10 minutes in the entware installation screen, it will continue.

**Comment by Poxan100** [comment]
@stylesuxx waiting 10-12 mins really helps. WTFOS is installed. Thank you!
