### ISSUE TITLE
Ardupilot_Walksnail Rx_OSD Overlay

### ISSUE THREAD

**Issue by srhassan71** [fpv-wtf/wtfos-configurator#281]
I cannot start the overlay process with OSD and Video files from the goggles. There are no font files. Do I have to have a font file?
Where do you get this font file from, FC log file?

**Comment by stylesuxx** [comment]
I am confused - Why walksnail? This is for DJI not walksnail. Please specify what your setup is exactly.

**Comment by srhassan71** [comment]
I was trying to overlay video and Osd recording from walksnail and landed on WtFos. I guess I am on the wrong forum. Thanks

**Comment by stylesuxx** [comment]
Yeah, that's not going to work :-)
