### ISSUE TITLE
Goggles Restarted mid Flight

### ISSUE THREAD

**Issue by adityanayak28** [fpv-wtf/wtfos-configurator#282]
I was flying today and the v2 Goggles Restarted mid flight.
Vista AU
BF 4.4

**Comment by stylesuxx** [comment]
Could you provide more information please? Did the configurator complain about a slot being corrupted when you connect the goggles? Usually goggles restarting mid flight is a sign of power loss. I would check the wiring and make sure you can't reproduce this behavior by wiggling the cables on the bench.

**Comment by adityanayak28** [comment]
I replaced my DJI wire last week so I doubt that would have been the
problem.

Also, After the restart the next flight had some message pop up above where
it said "Unlocked"( this is just for reference) . It was something i
couldn't read because i was flying really fast in a jungle but then it
vanished. I have some gigs next week and i am worried what if it restarts
during the shoot. Shall i uninstall WTF OS before the shoot ?

**Comment by stylesuxx** [comment]
When you connect to the goggles through the configurator, it will tell you if something is broken (ie.: the slot switched)

**Comment by adityanayak28** [comment]
This is what the CLI says when i connect:

[sec_debug state:202] secure debug value 0×1

***@***.***_wm170.g1s: /

**Comment by stylesuxx** [comment]
Not the CLI - in the top of the configurator, are there any warnings shown? Please post a screenshot of the configurator after connecting to the goggles.

**Comment by stylesuxx** [comment]
@adityanayak28 any update on this?

**Comment by stylesuxx** [comment]
Close du to lack of response.
