### ISSUE TITLE
Root not working

### ISSUE THREAD

**Issue by Axposure** [fpv-wtf/wtfos-configurator#286]
Hey there!! 
I downgraded my fpv v2 goggles via butter, what has worked so far. If i try to root the goggles, the connection is established via com4. After half a minute or so, it cancelled after attempting Step 1..... it says "Failed after 10retries".
What can be wrong here? I use Edge as browser on windows 11pro

Thanks in advance

**Comment by stylesuxx** [comment]
Your goggle is in DIY mode?

**Comment by Axposure** [comment]
i dont think so. how do i turn them into diy?

**Comment by Axposure** [comment]
okay it worked!! needed to turn settings from AVATA to FPV SYSTEM,<

**Comment by stylesuxx** [comment]
post a screenshot of the rooting process, does not seem that the downgrade went through then...

**Comment by Axposure** [comment]
big fpv v2 goggles. not the expensive ones for avata. I did Butter on them and tried to root. Says Firmware too new. Currently i am on v01.00.0607. i thaught butter will downgrade to make the root hack work
btw thanks for your help

**Comment by Axposure** [comment]
![Unbenannt](https://user-images.githubusercontent.com/124731699/217364315-a5a43ba2-7a0e-45b8-b3c8-3faa6359e452.jpg)

**Comment by stylesuxx** [comment]
Please try to downgrade to 0606 via assistant

**Comment by Axposure** [comment]
i tried, assistant doesnt show any downgrade option. i tried to find an older version of assistant, but i cant find one. i am using assistant v2.1.2
![u2](https://user-images.githubusercontent.com/124731699/217366875-f64addda-07ab-4f1c-827b-6405f47edb9f.jpg)

**Comment by stylesuxx** [comment]
Hmm, try refreshing and start over, something went wrong somewhere...

**Comment by Snowhack** [comment]
I'm getting the same thing. I have V01.02.0015 before and after the downgrade attempt. Tried restarting, reinstalling drivers. Still get failed after 10 retries.

**Comment by Snowhack** [comment]
I fixed my issue. The goggles have to be switched to DIY mode and then attempt the whole process again. For me it was not a one and done, I had to repeat the root process a few times before it took. Power cycling after each step, etc. A couple of times it stated that it was a success and my device was rooted only to not have the ROOT button greyed out. So I repeated until finally it worked.

**Comment by jerimybonds** [comment]
I successfully got through butter and when I rooted it went through no problem, but when i go back to home after it completed the WTFOS was still grayed out. attached screen shot of my root
![2023-02-26](https://user-images.githubusercontent.com/126444390/221486563-d40784cb-d9ed-4032-9fdb-1d01f9bf53ef.png)

**Comment by stylesuxx** [comment]
@Axposure from what I understand your issue is solved - closing this. Feel free to re-open if you still need help.
