### ISSUE TITLE
connecting goggles

### ISSUE THREAD

**Issue by pontuspumba** [fpv-wtf/wtfos-configurator#287]
i can't connect my dji goggles v1 after rebooting,

**Comment by stylesuxx** [comment]
Could you be more specific what you are trying to do and where it fails?

**Comment by pontuspumba** [comment]
i can root the goggles with no problem but when i go to the home page and click connect device it does not show up

**Comment by stylesuxx** [comment]
Then it is not rooted. Which firmerversion are you running, please show a screenshot of the rooting process.

**Comment by pontuspumba** [comment]
![image](https://user-images.githubusercontent.com/126020763/220463159-6f31482a-11ca-47ab-9dbc-630815395930.png)

**Comment by stylesuxx** [comment]
Hmm, the goggle is disconnecting a lot inbetween - could you please try with a different cable just to be on the safe side?

**Comment by pontuspumba** [comment]
yeah i can try

**Comment by pontuspumba** [comment]
same result

**Comment by stylesuxx** [comment]
Could you please show the output of `chrome://device-log/`? Please clear, then connect the goggles and post a screenshot of the output.

**Comment by pontuspumba** [comment]
sorry i don't  understand what you mean

**Comment by stylesuxx** [comment]
Open chrome and put `chrome://device-log/` in the url bar, hit enter. clear log, plug in goggles, post a screenshot.

**Comment by pontuspumba** [comment]
![image](https://user-images.githubusercontent.com/126020763/220688923-aa8e6fb3-b6e1-434d-a290-31b6790be331.png)

**Comment by stylesuxx** [comment]
so? Plug in your goggle...

**Comment by pontuspumba** [comment]
![image](https://user-images.githubusercontent.com/126020763/220691115-b8a6dd7f-d5bd-4db1-a09b-3e5e5144a490.png)

**Comment by stylesuxx** [comment]
Is this with all checkboxes being checked?

**Comment by pontuspumba** [comment]
oh sorry i missed one

**Comment by pontuspumba** [comment]
![image](https://user-images.githubusercontent.com/126020763/220692436-0b133b2d-937c-44ba-9058-81297c76d8ea.png)

**Comment by stylesuxx** [comment]
Nah, the errors don't look good at all. You can connect to the goggles with DJI assistant? If so, please try refreshing the firmware. Alternatively if you can, please try on a different system. If non of this works, try using [Butter](https://github.com/fpv-wtf/butter) to reset to a known working state.

Also - your goggles are in DIY mode - right?

**Comment by pontuspumba** [comment]
waht is diy mode?

**Comment by stylesuxx** [comment]
Are you using an air unit or vista with your goggles, or are you flying with the DJI FPV copter?

**Comment by pontuspumba** [comment]
i have a diy drone but i don't know if it is air unit or vista

**Comment by stylesuxx** [comment]
OK, does not matter if it's either or, and you can see an image, you are in DIY mode. Please try the other things I suggested. I'd also be interested to know which OS you are using.

**Comment by stylesuxx** [comment]
@pontuspumba any update on this?

**Comment by stylesuxx** [comment]
Closed du to lack of answer.
