### ISSUE TITLE
After successfull rooting can't install WTFOS

### ISSUE THREAD

**Issue by Andrey-Svetlichny** [fpv-wtf/wtfos-configurator#288]
Goggles V1, successfully rooted
![2023-02-23_234439](https://user-images.githubusercontent.com/8205024/221049370-4a82c08f-354e-4c60-8c3b-742865d5d87e.png)
After that I got a message "Slot 2 active..."
I Pressed a button "ATTEMPT FIX"
![2023-02-23_234502](https://user-images.githubusercontent.com/8205024/221049791-19324f3f-8520-4980-918f-65d7ad567433.png)
After that could not connect to device.
![2023-02-23_234856](https://user-images.githubusercontent.com/8205024/221049931-e7ee7b73-3e14-46fc-b9f3-ecdb84a74395.png)
DJI assistant can see my googles.
If I start "ROOT DEVICE" again, have an error on step2: 
```Error code: STATUS_ACCESS_VIOLATION```
![2023-02-24_000320](https://user-images.githubusercontent.com/8205024/221050926-52f5060b-5b59-48a1-9131-55d353136a2a.png)

**Comment by stylesuxx** [comment]
Yes, unfortunately that happens from time to time. Could you please try with a different browser (eg. edge) or on a different machine?

**Comment by Andrey-Svetlichny** [comment]
Did it from my wife notebook (chrome, no DJI software installed). And I kept SD card in glasses during process (for my first attempt I removed SD card). Done! Thank you!
