### ISSUE TITLE
OSD Overlay: Incorrect number of frames in joined file prevent process from finishing.

### ISSUE THREAD

**Issue by vvs1024** [fpv-wtf/wtfos-configurator#290]
Goggles split recordings into multiple files at 10min or ~2.3 GB mark. After I join files back using avidemux or VLC resulting video play fine in any player. 
If I am trying to apply OSD Overlay on it fails, the process reach the end of combined timeline but never finishes. I can see in the UI that overlay was correctly placed until the end of combined file, so there is nothing wrong with the sync. Problem is that it never finishes and resulted file on the disk is zero size. 

In the UI I can see that number of expected frames is very huge and does not represent actual frames number in the file. Attached is example of last frame where process stopped.

Hopefully this is easy fix, just detect that there are no more frames in the source and stop or fix frames number estimation.

![image](https://user-images.githubusercontent.com/81448728/221756105-1dbc6ed4-d9de-43b7-ba0b-c47ff49fc523.png)

**Comment by Knifa** [comment]
The overlay tool doesn't currently support any files other than those that come directly out of the DVR, as it says at the top of the page. 😄
