### ISSUE TITLE
screen saver doesn't work

### ISSUE THREAD

**Issue by hsu8116** [fpv-wtf/wtfos-configurator#291]
screensaver01 and screensaver02  is not working, any ideas?

**Comment by hsu8116** [comment]
splashscreen working normally or rather it won't go into the screensaver

**Comment by j005u** [comment]
The screensaver images will not work if you are using msp-osd as the latter uses the same framebuffer drawing layer as the screensaver.

It's a won't fix for now.

**Comment by stylesuxx** [comment]
See here: https://github.com/fpv-wtf/wtfos/issues/70#issuecomment-1443596643
