### ISSUE TITLE
Rooting 

### ISSUE THREAD

**Issue by Dwayne242** [fpv-wtf/wtfos-configurator#292]
my goggles doesnt what to root even after I did the downgrading process it either tells me the firmware is too new which I already did the recovery or it keeps failing... it also says version unknown in the root part

**Comment by stylesuxx** [comment]
Please make sure the goggles are in DIY mode and show a screenshot of the rooting process.

**Comment by stylesuxx** [comment]
@Dwayne242 any update on this? Otherwise I will close the issue.

**Comment by stylesuxx** [comment]
Closed due to incactivity.
