### ISSUE TITLE
gogglesV2 GP150 Rooting

### ISSUE THREAD

**Issue by notgohobo** [fpv-wtf/wtfos-configurator#293]
fresh goggles 01.02.00.60

used butter to downgrade
assistant says no firmware change
try to root via site.  error message Aborted! Device did not reboot in time, please power cycle and try again.

tried booting up in HD mode has 606 FW.
connect to dji assistant says downgrade to 01.00.0607, do so retry rooting, same error

try butter again
try rooting, same error Aborted! Device did not reboot in time

any advice would be helpful.
Kind Regards, Notgohobo.

![DJI Assistant](https://user-images.githubusercontent.com/127024775/222959610-a708f89c-1576-44e8-b2ef-24d8c09c8adf.jpg)
![flash 10  1 00 0606](https://user-images.githubusercontent.com/127024775/222959620-484db5d3-8955-4260-a8a1-bc9c2ed5d3ba.jpg)
![rooting aborted](https://user-images.githubusercontent.com/127024775/222959626-b44fd799-f925-49ec-8e78-676a0c2ecc2e.jpg)

**Comment by stylesuxx** [comment]
You need to be in DIY mode.

**Comment by notgohobo** [comment]
thank you for your reply

Is this DIY Mode?

![1678044579319](https://user-images.githubusercontent.com/127024775/222981608-2607bcc5-6ca3-4a1f-8918-da9d2a0949fc.JPEG)
![1678044579389](https://user-images.githubusercontent.com/127024775/222981611-3e363774-2fea-4020-84cc-9ff918f61f9c.JPEG)
![1678044579397](https://user-images.githubusercontent.com/127024775/222981612-43a15e3f-a4b8-4924-82d6-a58e9f02a90e.JPEG)

**Comment by stylesuxx** [comment]
Yes, this looks fine.

**Comment by notgohobo** [comment]
ok Tried rooting again 

00:01 Attempting Step 1...

00:33 - Found Device: GP150, Version: 01.00.0607

00:33 Step 1 - Success! Rebooting...

01:35 Aborted! Device did not reboot in time, please power cycle and try again.

regards, Sean.

**Comment by stylesuxx** [comment]
Can you hear the goggle actually rebooting? Can you please post output of chrome://device-log/ after the rooting process (please clear before connecting the goggles)

**Comment by notgohobo** [comment]
Ok
![log2](https://user-images.githubusercontent.com/127024775/223092071-6102b634-fc7d-474f-93c5-c6689b2f42dd.jpg)
 
Yes can hear the goggles reboot. 
[Device Log2.zip](https://github.com/fpv-wtf/wtfos-configurator/files/10897343/Device.Log2.zip)

**Comment by stylesuxx** [comment]
Yeah, you should not be using this anymore. Win 8 is EOL since beginning of this year.
I would recommend you try on a different - more up to date - machine.

**Comment by notgohobo** [comment]
Alright I will try an updated machine. Thank you

**Comment by famousamos793** [comment]
Hello, I am getting this exact same issue running Windows 10 Home...

**Comment by stylesuxx** [comment]
@notgohobo - any update on this? Otherwise I will close this issue.

@famousamos793 - please open your own issue and provide all needed information. Basically the same things I asked from @notgohobo.

**Comment by famousamos793** [comment]
Hello and good afternoon! Thank you for following up! My issue was fixed after simply restarting windows, and trying everything all over again.

I think a windows restart might be required for some machines after the driver install.

**Comment by stylesuxx** [comment]
Closed due to inactivity
