### ISSUE TITLE
UI chores

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#30]
A few small thoughts for future reference:

- [x] Add friendly device names to the header
- [x] Add a link to report issues on Github
      Unless we prefer Discord being the main point of contact for now?
- [x] On the wtfos page add a link to the fpv-wtf/wtfos github repo, which should get more documentation
- [ ] On the wtfos page add a short description paragraph or two
- [x] Add some reference to the configurator github repo
- [x] Add a 404 route handler either with 404 page or redirect to /

**Comment by stylesuxx** [comment]
Regarding friendly device names, is this all:

```
pigeon_wm170_gls: DJI FPV Goggles V2
pigeon_wm150_gls: DJI FPV Goggles V1
pigeon_wm150_tiny: DJI FPV Airunit Light (Caddx Vista)
pigeon_wm150: DJI FPV Airunit
```

or do the goggles identify differently when not in DIY mode? Also should I drop the 'DJI FPV' prefix?

I would prefer Github issues for collecting issues. In discord stuff often times gets lost...

Could you by any chance make up some description paragraphs for the WTFOS page?

**Comment by stylesuxx** [comment]
#107 needs to be merged - other than that we are done here.
