### ISSUE TITLE
Cant Root with Wtf.fpv Online Configurator on my DJI FPV Goggle's V2 from my DJI FPV Drone. Already downgraded from V0015, using Butter. I now have an O3 air unit i want to use with these goggles with the WTF.OSD

### ISSUE THREAD

**Issue by KTM1551** [fpv-wtf/wtfos-configurator#309]
Cant Root DJI FPV Goggle's V2 from my dji fpv drone and i now have a new O3 air unit i want to connect to them as well, but i cant get past the rooting process of my V2's.
The wtf.fpv online configurator will recongize them and it will find them as Com Port 7, i can select them, but when i go to actually click Root, i get an error of 10 failed attempts or something to that effect. It never really gets past the first part at all. it fails within 45secs according to the log.

The v2 goggles are in dji fpv drone mode and have always been since ive had them. I use the recommended file package with BAT file for the V2's which was GP150.

Hoever, after some reading it seems that the DJI FPV Goggles V2's in DJI FPV DRONE "fpv racer" mode uses the GP170 FW File set and BAT command file, but that doesnt seem to be an option on the site. 

What do i need to do to properly Root these V2 Goggles so that i can upgrade them and actually use them for my drone and my 5" quad with the O3 air unit..?

Also how do i switch the goggles v2's to diy mode/air unit from DJI FPV Drone Mode? I am on the welcome screen and when i click english, it will go to the no image screen. But NO menu options for swtiching them over to "DIY Mode". Googled everywhere and cant  find a way to do it.

Can the rooting be done in DJI FPV Drone mode? Or do i need to switch it first? I read the wiki's and i dont see any information on these two issues. Rooting failures and switching modes.. 

Thanks
Anthony

**Comment by stylesuxx** [comment]
Goggles need to be in DIY mode for rooting.

**Comment by KTM1551** [comment]
> Goggles need to be in DIY mode for rooting.

Ok thanks for the reply! How do i go about switching my goggles v2 into DIY mode, bc there's no menu option? 

Ive watched many videos and where there's supposed to be the option to switch to DIY Mode in my Goggles V2 (settings-> About) instead of going down further it to switch to DIY FPV mode, it stops at factory reset in the list.


Do i need to reconnect it to my FPV Drone first to switch to DIY Mode? If thats the case, how would you do it if you only had an Air Unit for example? Because I'm going to eventually sell the FPV drone once i try it and see how it is, just so i know for the future.

Also was using the GP150 V01.00.0606 FW correct or should i have use a different version like the GL170?

I also used the Butter Downgrade tool while the goggles were still connected to the FPV Drone with live video. I had read that you could do it either way as long as you pick the right FW Package for the model name.

Thanks

**Comment by stylesuxx** [comment]
You might need to be connected with the fpv drone for the option to show up, then you should be able to switch to DIY mode. I am a bit surprised though, technically that should not be an issue after downgrading with butter...

Not being able to switch to DIY mode has been an issue on some (?) versions before... you can google it, there are quite some people who ran into this problem. Downgrading/refreshing the firmware should fix the issue though (that's why I am surprised you don't see it...).

**Comment by KTM1551** [comment]
Yea thats what was kind of confusing for me. I had read some of those already..

Is it possible i was using the wrong Zip file script set for the downgrade with Butter or would it just fail?

I used the link for the Goggles V2 on the wtf.fpv Github page, and it downloaded, "gp150_01.00.0606_recovery" zip for me.

But now im seeing that since my goggles came from a DJI FPV Drone and was never used with an air unit, that the Zip file should be something 170, for example gl170 or gp170 to match the goggles or is that for something different?

I will try to connect the FPV drone and see what happens, hopefully the option will somehow come back..

If not, what should be the next thing to try, you think?

Thanks

**Comment by stylesuxx** [comment]
There are only two versions of goggle, V1 or V2(V2 comes with diy and FPV mode, but that's only a software distinction). If you are in FPV mode anyway you can check the version.

If you can't switch to diy mode after connecting to the drone, try running butter again and pay close attention to the Readme.and the output.

**Comment by KTM1551** [comment]
Ok. So i turned on the fpv drone and controller along with the goggles and it all instantly connected again. weird. 
Anyway, the option to switch to DIY FPV Mode re-appeared again without even restarting the goggles and i immediately switched it into FPV mode. 

On the FPV side it does say FW v01.00.0606 under Device Info. So it seemed like everything worked okay? Im going to try and Root them now that its in DIY Mode. 

Maybe future FPV Drone user's should be told to switch to FPV mode as the first step, since you can do all this in the DIY mode and then just return to the FPV Drone mode without any issue it seems.

So after i root the googles succesfully, i then switch them back to FPV Drone mode, and then DJI Assistant to update the goggles or do they just stay on the current firmware? 
I do have an FPV Drone i want to use, but i wanted to rollback & root the v2's, before i did anything with the Drone like trying to fly it, and then a forced update or something to mess up being able to eventually get the wtf.osd and other things. Same with the drone itself, but that parts already done so im just about ready.

I do have my first digital system all done, just need to do some small changes to the drone, so i have an O3 air unit to use with these as well. What firmware for the fpv drone side or the diy mode should i use/upgrade too after rooting?

Thanks for all the help!

**Comment by stylesuxx** [comment]
Once you are rooted you are fine. Generally you are fine since butter exists. But you can update to any other version technically.

Also it is mentioned to switch to DIY mode here: https://github.com/fpv-wtf/wtfos But you are right, it might be worth to add a note in the configurator itself.

Also rooting only really has a benefit if you are in DIY mode anyway, if you just want to fly the DJI FPV drone, then you are not really gaining anything.

Let me know if rooting works out, if so feel free to close this issue.

**Comment by KTM1551** [comment]
Ok i got it rooted and everything installed for the WTF.OSD & some packages. thank you for your help!

And as far as the V2's FW., the reason I ask because right now i have both a FPV drone and a "DIY Air Unit" in a 5" Freestyle Drone, now with HD lol. 

So i basically just want to know what the best FW for each would be, in each mode. Do i just update the V2's now to the newest FW available with DJI Assistant 2? DJI A2 says their current FW is v01.02.0020.
I think its like V01.04.0000 now for the dji fpv but i have to switch it over first it says.

I have an Air Unit im putting in a 5" i already had for a few years now, that i basically always use. So i just want to have the goggles fully setup and upgraded to use any of the cool new features..

**Comment by KTM1551** [comment]
update the goggles in dji drone mode with dji assistant 2 to newest FW or leave them where they are? 

i have both dji fpv drone and a diy mode fpv quad with an O3 Air unit, if that makes a difference.

diy mode says im on v01.01.0020
