### ISSUE TITLE
failed firmware

### ISSUE THREAD

**Issue by 907fpv** [fpv-wtf/wtfos-configurator#315]
### Device

Goggles V2

### Describe the issue

![IMG_7184](https://user-images.githubusercontent.com/128775601/227428237-89e8c208-e180-42a0-9e69-baffbd5dc15c.JPG)
why does it keep doing this i have done everything correct

**Comment by stylesuxx** [comment]
By "everything" you also mean you tried downgrading with Butter?

**Comment by famousamos793** [comment]
Yes, I have used Butter successfully 3 times... the version still states 01.00.0607. I am having this problem as well.

**Comment by 907fpv** [comment]
yes I downgrading with butter to verion 0606 dji v2 goggles says its on the version but i get that message every time

**Comment by stylesuxx** [comment]
The error might be a false positive if you successfully run butter. If you see this message, just power-cycle your device and try to run root again. It might take a couple of attepmts

**Comment by stylesuxx** [comment]
@907fpv any update on this? Otherwise I will close the issue.

**Comment by 907fpv** [comment]
I have tried about 10 times and just won’t work so I gave up. Thanks for trying to helpSent from my iPhoneOn Apr 11, 2023, at 6:38 AM, Chris ***@***.***> wrote:﻿
@907fpv any update on this? Otherwise I will close the issue.
