### ISSUE TITLE
Packages screen can appear empty 

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#316]
### Device

Goggles V2

### Trace ID (bototm left)

7d63a1a8-ed9e-453d-8e06-320463856f6a

### Describe the issue

The packages screen can be navigated to showing 0 packages with no loading status. Navigating back and forth does not help, a refresh does.

Can be seen here on the latest JB news live stream: https://youtu.be/YjaIEUEUWWk?t=2691

I had this happen to myself just now, but don't have a reliable repro yet.

If I had to guess I think this has something to do with ipkg locking?

**Comment by stylesuxx** [comment]
Yes, I am pretty sure this is an issue of locking too. I have a queue and lock check in progress. This should improve things.
