### ISSUE TITLE
Could not connect to device

### ISSUE THREAD

**Issue by AdrThomas** [fpv-wtf/wtfos-configurator#332]
### Device

Goggles V1

### Describe the issue

Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window.

**Comment by j005u** [comment]
Please give our latest driver installer a try and see if it helps: https://github.com/fpv-wtf/driver-installer/releases/tag/v1.1.0

**Comment by j005u** [comment]
Update: I now beleive the problem is different. Please go to https://fpv.wtf/root and root the device again. It may be normal in some circumstances to need to do this more than once.

**Comment by stylesuxx** [comment]
@AdrThomas any update on this, otherwise I will close the issue.

**Comment by stylesuxx** [comment]
No response, closed.
