### ISSUE TITLE
adb no longer works in non DIY mode on latest firmware

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#334]
### Device

Goggles V2

### Trace ID (bototm left)

7d63a1a8-ed9e-453d-8e06-320463856f6a

### Describe the issue

Previously this worked regardless of mode, but on the latest V2 ("FPV Mode") firmware adb no-longer works by default with secure_debug enabled.

Any command executed results in
```
- exec '/system/bin/sh' failed: Permission denied (13) -
using port=5555
```
It's fine if the user switches to DIY mode.

Haven't run into it much yet, but we should probably catch this and tell the user to switch modes in future.

**Comment by j005u** [comment]
This may also be due to other things I did to my goggles. Will report back.

**Comment by j005u** [comment]
Yup, turns out erasing the userdata partition makes non-DIY modes go all kinds of haywire.

This isn't something the configurator should really have to deal with.

If by some wonder some user should get themselves into this situation they can contact me for a userdata image to reflash with butter.

**Comment by stylesuxx** [comment]
Is this worth documenting somewhere? Maybe throw it in the wtfOS wiki?

**Comment by j005u** [comment]
The only reason I was running into it is because I manually erased my userdata partition. Haven't heard of anyone else running into this. Figured having the issue here being searchable should be enough.

**Comment by stylesuxx** [comment]
Perfect - makes sense.
