### ISSUE TITLE
Decoder error in some videos

### ISSUE THREAD

**Issue by wessi86** [fpv-wtf/wtfos-configurator#339]
### Device

Goggles V2

### Trace ID (bototm left)

76668fcc-6c91-46d5-9aad-f1914895afd8

### Describe the issue

Hey everyone,
for some recordings I'm getting a Decoder error at some point when rendering.
Browser console says:
- Uncaught DOMException: Decoder error.                                       processor.ts:338
- Uncaught (in promise) DOMException: Aborted due to error        asyncToGenerator.js:6
- Uncaught (in promise) DecoderError: Decoder error.                     asyncToGenerator.js:6 
    at e.value (processor.ts:337:25)
     
I tried different browsers, devices and fonts and the knifa-development site. The error comes up at the same frame all the time.

If you need the files, let me know and I'll upload them somewhere.

Thank you in advance,

Christian

**Comment by wessi86** [comment]
> Yes, please upload the files.

For some reason it worked now after another try. But here's another video which is currently not working.

https://www.dropbox.com/s/yowxw535jw2voqy/DJIG0025.mp4?dl=0
https://www.dropbox.com/s/vhy6vpgf5vlzvty/DJIG0025.osd?dl=0

**Comment by stylesuxx** [comment]
Oh great, so it just worked randomly? That will be fun to debug...

**Comment by wessi86** [comment]
> Oh great, so it just worked randomly? That will be fun to debug...

Ok, I think I figured it out and the problem is on my end. It's probably an issue with the card reader or the USB hub. I copied the files again and now it seems to work.
