### ISSUE TITLE
Warning about active cooling for Air Unit / Vista

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#34]
We should probably add a warning about needing active cooling on the bench for the air side.

If we want to be fancy about it then it'd be awesome to be able to dismiss that message either once, or permanently (local storage). Or super fancy: active temperature monitoring and warnings.

I think the capability to dismiss could also apply to the safety measures.

**Comment by stylesuxx** [comment]
At least for now I want this to be there all the time. If people have the chance to klick it away, they will do so without reading. In the root screen there is actually a hint that you should cool it. I can make it more explicit and show it as soon as an air unit is detected - also during non rooting.

Temperature monitoring also sounds like a good idea - this will obviously only work in "ADB" mode - I will look into it.

![Screenshot from 2022-05-16 20-55-48](https://user-images.githubusercontent.com/978192/168662832-2cb4d362-9784-40d3-b4cc-23efdb924f49.png)
