### ISSUE TITLE
Fails to connect. Starting firmware version: v01.07.0000

### ISSUE THREAD

**Issue by madhtr** [fpv-wtf/wtfos-configurator#340]
DJI V2 goggles.
Starting firmware version: v01.07.0000
Windows 10

1) installed drivers.
2) (restarted)
3) ran the rollback.
4) (restarted)
5) attempted to root ...

I'm getting ...

00:02 Attempting Step 1...
00:33 Failed after 10 retries.
00:38 Device went away...  (I turned off the v2 goggles)
00:56 Device came back... (I turned the v2 goggles back on)
00:59 Attempting Step 1...
01:29 Failed after 10 retries.

**Comment by stylesuxx** [comment]
Your goggles are in DIY mode?

**Comment by stylesuxx** [comment]
@madhtr any more info on this, otherwise I will close the issue.

**Comment by stylesuxx** [comment]
No response, closed.
