### ISSUE TITLE
Firmware version do not match

### ISSUE THREAD

**Issue by GootyS** [fpv-wtf/wtfos-configurator#348]
### Device

Goggles V2

### Operating System (Including version)

MacOS 10.15.7

### Browser

Chrome

### Describe the issue

I had to roll back on some firmware using butter on a Caddx Vista using dji cam. Goggles are on v01.00.06.06 and the Vista is now on v01.00.06.08. All my other Vistas are on v01.00.06.06. Now on the rolled-back firmware vista im getting a message in the goggles that says "Firmware versions do not match, Use DJI Assistant 2 to upgrade" with two options if "Skip" and "Check".

Anyone know what this is?

**Comment by j005u** [comment]
Here's a 0606 package for a vista: https://mega.nz/file/dioAEKYJ#d2i9YlhEUvSc7piR_TrwBkrSi1Wnjdc_RFzXIIT-kFE

**Comment by GootyS** [comment]
Greetings again, sorry to reopen this one. I have only managed now to install this version, (been a little busy) Im still getting the same message in the screen after the update. Im guessing pressing skip wont do any harm each time? Its either that all update Goggles and other vistas to 608? Thoughts?
