### ISSUE TITLE
After update to wtfOS failed to fetch updatable packages, unable to get/update packages

### ISSUE THREAD

**Issue by zoran-grujic** [fpv-wtf/wtfos-configurator#357]
### Device

Goggles V2

### Operating System (Including version)

Windows 10

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

6c042c7a-5226-4d08-a859-3443ab42c52c

### Describe the issue

Here is the error message>

Failed fetching upgradable packages:

Collected errors:

* opkg_download: Failed to download http://repo.fpv.wtf/entware-armv7sf-k3.2/Packages.gz, wget returned 255.

* opkg_download: Failed to download http://repo.fpv.wtf/pigeon/Packages.gz, wget returned 255.

Downloading http://repo.fpv.wtf/entware-armv7sf-k3.2/Packages.gz

*** Failed to download the package list from http://repo.fpv.wtf/entware-armv7sf-k3.2/Packages.gz

Downloading http://repo.fpv.wtf/pigeon/Packages.gz

*** Failed to download the package list from http://repo.fpv.wtf/pigeon/Packages.gz

**Comment by zoran-grujic** [comment]
OH, I am stupid! Restart required after update! Maybe some message might popup after every update...

**Comment by j005u** [comment]
Normally wtfos updates shouldn't require a restart and I can't quite make sense why those specific errors would get cleared by one. 

Glad you got it sorted. I'll keep an eye out for more users running into the same issue, but closing this here meanwhile.
