### ISSUE TITLE
Goggles V2 can't get root!

### ISSUE THREAD

**Issue by Avi4ka** [fpv-wtf/wtfos-configurator#364]
### Device

Goggles V2

### Operating System (Including version)

windows 10

### Browser

Ghrome, Edge, Vivaldi

### Trace ID (bottom left of the configurator screen)

v2.1.0 - Trace ID: 61d532ee-e684-424d-9110-2c46c5b36c7d

### Describe the issue

Hello. I've been struggling with this problem for days now. Glasses version 01.00.0606(in goggles menu). 
Always hangs at step 2:
00:03 Attempting Step 1...
00:34 - Found Device: GP150, Version: 01.02.0000
00:34 Step 1 - Success! Rebooting...
00:59 Attempting Step 2...
01:02 "The signing server could not be reached. It might be down or your ISP might be blocking it."

If you use develop.fpv.wtf - 
at step 4 "Unlock failed, please power-cycle your device and try again." 
Please help me figure it out.

**Comment by j005u** [comment]
V01.02.0000 can't be rooted and you need to downgrade via butter https://github.com/fpv-wtf/butter#usage

The DIY mode menus lie and you are actually on a newer firmware version. This is normal.

**Comment by MrNoname2120** [comment]
I have the same issue but on every thing i look it at it says i have the .606 version

**Comment by Nitron2000** [comment]
I have exacly the same issue  on .606 version

**Comment by MrNoname2120** [comment]
> I have exacly the same issue on .606 version

I figured it out try upgrading back the latest then back to .606 and try again

**Comment by Nitron2000** [comment]
Hi MrNoname120, what do you mean with "upgrading back"?

**Comment by MrNoname2120** [comment]
> Hi MrNoname120, what do you mean with "upgrading back"?

Upgrade the goggels firmware to the latest version then re down grade it using the the git hub website zip file and follow the step again
