### ISSUE TITLE
DJI Integra lässt sich nicht mit wtfos verbinden

### ISSUE THREAD

**Issue by domi2023** [fpv-wtf/wtfos-configurator#365]
### Device

Goggles V2

### Operating System (Including version)

Windows 10 Home

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

12a41112-1910-4043-8ade-8d4ad92a1bbf

### Describe the issue

Hallo Zusammen,

die DJI Integra lässt sich nicht mit wtfos verbinden.....

e3t USB

Vielen Dank und Gruß

**Comment by j005u** [comment]
There are no current plans to add support for the O3 AU, Goggles 2 or Goggles Integra.
