### ISSUE TITLE
40min dvr, rendering for 30+ min just for a 0byte file

### ISSUE THREAD

**Issue by Timmzz** [fpv-wtf/wtfos-configurator#376]
### Device

Goggles V2

### Operating System (Including version)

windows10 19045

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

83e15916-9162-427a-b821-6d8306ec8758

### Describe the issue

![image](https://github.com/fpv-wtf/wtfos-configurator/assets/104192806/fb80eae3-57c4-45d3-981c-60854d249a65)
First flight with this plane, REALLY NEED THIS DVR every damn time it produces a currupted file. Takes 30+ min to render each time.

**Comment by Timmzz** [comment]
EDIT: seconds after posting my first bug report the file randomly started working! Confusing but gratefull
![image](https://github.com/fpv-wtf/wtfos-configurator/assets/104192806/28723086-670d-440e-8ca2-bb010514136e)

**Comment by stylesuxx** [comment]
Closing this, feel free to re-open if you run into this issue again or can reproduce it consistently.
