### ISSUE TITLE
Filter packages by Device-type

### ISSUE THREAD

**Issue by Alia5** [fpv-wtf/wtfos-configurator#38]
Some Packages only make sense to be installed on either the AirUnit/Vista or the Goggles.  

I.e.
`msp-osd-goggles` or `goggle-led-draw` only makes sense for Goggles (obviously)
`msp-osd-airside` only for AirUnit/Vista
`enable-live-audio` Probably AirUnit/Vista but as someone who is just looking into this, it raises questions.

Since there is currently no meta-data on packages on device-compatibility, this would need to be implemented first

**Comment by j005u** [comment]
The plan was to use package architecture for this.

- pigeon-all
- pigeon-airside
- pigeon-glasses

But we haven't quite implemented it yet and are still using the entware architecture nomenclature at the moment.

Related issue: https://github.com/fpv-wtf/opkg-repo/issues/2

**Comment by Alia5** [comment]
Looked a bit into this.  
I'm assuming that the airside won't get a line `arch pigeon-glasses ...` in it's `opkg.conf` and vice versa.  
In that case, nothing has to be done on the UI side.

Except for a bug when selecting `All` in the "Repo"-Dropdown
I've made a PR for this: https://github.com/fpv-wtf/wtfos-configurator/pull/39
