### ISSUE TITLE
Signing Server Can't Be Reached

### ISSUE THREAD

**Issue by tvtechdir** [fpv-wtf/wtfos-configurator#391]
### Device

Caddx Vista

### Operating System (Including version)

MacOS Ventura 13.4.1

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

95c7d9b0-bfd0-4567-bbbb-9ffaa18de4fa

### Describe the issue

Cannot root Vista. New Vista, successfully downgraded to 0606 through DJI Assistant (FPV Series). Open WTFOS website to begin rooting process. Vista is seen by Chrome and successfully completes step 1, reboots to begin step 2. Then the process hangs with:
00:01 Attempting Step 1...

00:14 - Found Device: LT150, Version: 01.00.0606

00:14 Step 1 - Success! Rebooting...

00:33 Attempting Step 2...

00:44 The signing server could not be reached. It might be down or your ISP might be blocking it.

00:48 Device went away...

The last line is the quad being unplugged.

**Comment by stylesuxx** [comment]
Can you open this url: https://api.fpv.tools/ota/ - should return "Bad request".

**Comment by tvtechdir** [comment]
Confirmed the link returned "Bad Request".

**Comment by tvtechdir** [comment]
Sorry gang. I'll leave it up to the devs to close this thread. Vivaldi is working fine on my system. Vista is now rooted with WTFOS installed. As a note, I did just use Chrome on this same system to update my Goggles V2 to the latest WTFOS as recommended by Joonas. Weird that it won't work on the Vista.

**Comment by stylesuxx** [comment]
That is indeed very weird. Maybe it was some temporary outage in which the signing server could not be reached. Since you could open it manually I don't see what else could have been the issue. I'll close this for now and keep it in the back of my mind should it come up again.

**Comment by seanoneill482-sketch** [comment]
Same thing for me too.  Won't connect to server...
