### ISSUE TITLE
Unable to root Caddx Vista on v01.00.0606 fw

### ISSUE THREAD

**Issue by JoeSa3rd** [fpv-wtf/wtfos-configurator#401]
### Device

Goggles V1

### Operating System (Including version)

Windows 10

### Browser

Chrome or Edge

### Trace ID (bottom left of the configurator screen)

93e44de4-a65d-4a32-a24d-03ecd01d57f4

### Describe the issue

I'm unable to root two Caddx vista's running on v01.00.0606 fw. I've tried everything and just can't get past step 2 as seen below. on the same computer I was able to root a DJI Air Unit on v01.00.0606 fw on the same computer with zero issues. I've also rooted multiple Caddx vista's a few weeks back without any issues on the same computer. I suspect it's a new bug in the configurator. I've even tried using butter to reflash the Caddx vista's to v01.00.0606 fw and still no luck. I've tried a second computer running Windows 10 and still that same error, See the two traces below from two different computers running Windows 10.

**Caddx Vista root error on computer A**
00:02 Attempting Step 1...

00:04 - Found Device: LT150, Version: 01.00.0608

00:04 Step 1 - Success! Rebooting...

00:21 Attempting Step 2...

01:14 Failed after 10 retries.

v2.2.1 - Trace ID: 93e44de4-a65d-4a32-a24d-03ecd01d57f4
**Caddx Vista root error on computer A fw 0606**
00:01 Attempting Step 1...

00:04 - Found Device: LT150, Version: 01.00.0606

00:04 Step 1 - Success! Rebooting...

00:21 Attempting Step 2...

00:59 Failed after 10 retries.

v2.2.1 - Trace ID: 93e44de4-a65d-4a32-a24d-03ecd01d57f4

**Caddx Vista root error on computer B**

00:01 Attempting Step 1...

00:16 - Found Device: LT150, Version: 01.00.0606

00:16 Step 1 - Success! Rebooting...

00:33 Attempting Step 2...

01:11 Failed after 10 retries.

v2.2.1 - Trace ID: 23e494a2-0089-4f60-abfc-92ff190191d3

**Comment by stylesuxx** [comment]
Are you sure nothing else is claiming the device after the reboot?
Can you post the output of `chrome://device-log/` of such a failed rooting session please?

**Comment by JoeSa3rd** [comment]
> Are you sure nothing else is claiming the device after the reboot? Can you post the output of `chrome://device-log/` of such a failed rooting session please?

I don't believe so as this root was attempted after a clean reboot of the device with only chrome running.  I would think I would have the same issue with rooting a DJI Air Unit if that was the case but I can root those types just fine.

Here is the device-log from chrome for a failed attempt to root the Caddx Vista. I've also included the Trace ID below.

SerialDebug[06:53:46] Failed to flush serial port: The device does not recognize the command. (0x16)

SerialEvent[06:53:43] Serial device added: path=COM5 instance_id=USB\VID_2CA3&PID_001F&MI_04\6&3A7FE9B5&1&0004 vid=2CA3 pid=001F

USBEvent[06:53:43] USB device function updated: guid=ce7abd2d-36eb-47cb-980f-2e10ed5d0298, interface_number=4, path="\\?\usb#vid_2ca3&pid_001f&mi_04#6&3a7fe9b5&1&0004#{86e0d1e0-8089-11d0-9ce4-08003e301f73}", driver="usbser"

USBEvent[06:53:43] USB device function updated: guid=ce7abd2d-36eb-47cb-980f-2e10ed5d0298, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#6&3a7fe9b5&1&0003#{dee824ef-729b-4a0e-9c14-b7117d33a817}", driver="WinUSB"

USBEvent[06:53:43] USB device function updated: guid=ce7abd2d-36eb-47cb-980f-2e10ed5d0298, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#6&3a7fe9b5&1&0003#{731abd67-21d3-4659-85bb-e6a09063cea4}", driver="WinUSB"

USBEvent[06:53:43] USB device function updated: guid=ce7abd2d-36eb-47cb-980f-2e10ed5d0298, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#6&3a7fe9b5&1&0000#{cac88484-7515-4c03-82e6-71a87abac361}", driver="usbrndis6"

USBEvent[06:53:43] USB device function updated: guid=ce7abd2d-36eb-47cb-980f-2e10ed5d0298, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#6&3a7fe9b5&1&0000#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{7fabeb71-a7ac-4760-8f92-f28e65e3a125}", driver="usbrndis6"

USBUser[06:53:43] USB device added: path=\\?\usb#vid_2ca3&pid_001f#123456789abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "DJI FPV Air Unit Lite", serial="123456789ABCDEF", driver="usbccgp", guid=ce7abd2d-36eb-47cb-980f-2e10ed5d0298

USBUser[06:53:38] USB device removed: path=\\?\usb#vid_2ca3&pid_0040#5&1aa452e9&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=e61f8c42-7e19-4875-b9a0-9caa83e3cc98

USBUser[06:53:34] USB device added: path=\\?\usb#vid_2ca3&pid_0040#5&1aa452e9&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "", product=64 "", serial="", driver="libusb0", guid=e61f8c42-7e19-4875-b9a0-9caa83e3cc98

SerialEvent[06:53:33] Serial device removed: path=COM5

USBUser[06:53:33] USB device removed: path=\\?\usb#vid_2ca3&pid_001f#123456789abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36

SerialEvent[06:53:17] Serial device added: path=COM5 instance_id=USB\VID_2CA3&PID_001F&MI_04\6&3A7FE9B5&1&0004 vid=2CA3 pid=001F

USBEvent[06:53:17] USB device function updated: guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36, interface_number=4, path="\\?\usb#vid_2ca3&pid_001f&mi_04#6&3a7fe9b5&1&0004#{86e0d1e0-8089-11d0-9ce4-08003e301f73}", driver="usbser"

USBEvent[06:53:17] USB device function updated: guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#6&3a7fe9b5&1&0003#{dee824ef-729b-4a0e-9c14-b7117d33a817}", driver="WinUSB"

USBEvent[06:53:17] USB device function updated: guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36, interface_number=3, path="\\?\usb#vid_2ca3&pid_001f&mi_03#6&3a7fe9b5&1&0003#{731abd67-21d3-4659-85bb-e6a09063cea4}", driver="WinUSB"

USBEvent[06:53:17] USB device function updated: guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#6&3a7fe9b5&1&0000#{cac88484-7515-4c03-82e6-71a87abac361}", driver="usbrndis6"

USBEvent[06:53:17] USB device function updated: guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36, interface_number=0, path="\\?\usb#vid_2ca3&pid_001f&mi_00#6&3a7fe9b5&1&0000#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{7fabeb71-a7ac-4760-8f92-f28e65e3a125}", driver="usbrndis6"

USBUser[06:53:17] USB device added: path=\\?\usb#vid_2ca3&pid_001f#123456789abcdef#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=11427 "DJI", product=31 "DJI FPV Air Unit Lite", serial="123456789ABCDEF", driver="usbccgp", guid=66fb4ab3-f3ac-4c47-a697-f31d748d6e36

00:02 Attempting Step 1...

00:04 - Found Device: LT150, Version: 01.00.0606

00:04 Step 1 - Success! Rebooting...

00:21 Attempting Step 2...

00:59 Failed after 10 retries.

v2.2.1 - Trace ID: 93e44de4-a65d-4a32-a24d-03ecd01d57f4

**Comment by JoeSa3rd** [comment]
Ok I just figured this out. I have a second set of goggles that have not been rooted and when binding these goggles to the Vista that I've not been able to root, I was notified in the second set of goggles that the Vista needs to be activated in the dji assistant 2 (DJI FPV Series). After completing the activation process I can now root the Vista successful. Interestingly I never received an activation prompt in my other goggles that have been rooted.
