### ISSUE TITLE
unable to access startup menu on website

### ISSUE THREAD

**Issue by maximilien1990** [fpv-wtf/wtfos-configurator#403]
### Device

Goggles V2

### Operating System (Including version)

windows11

### Browser

edge

### Trace ID (bottom left of the configurator screen)

 8487f17c-f6ed-49a7-bed6-b3757071ff8e

### Describe the issue

i cant access the startup menu i want to stop moolight from booting in the beginnig... anyone have the cli command for it?

**Comment by stylesuxx** [comment]
Sorry for the late reply.

You can disable services via CLI like so:

```
dinitctl -u disable SERVICENAME
```

Are you still running in this issue?

**Comment by maximilien1990** [comment]
no  i ended up doing a firmware update and by having to reinstall the wtfos i was able to reset that. and i jist wanted to clarify, at this point, with my device being rooted, no matter what firmware update i do the device will stay rooted and i will be able to reinstall the wtfos is that correct?

**Comment by j005u** [comment]
> no i ended up doing a firmware update and by having to reinstall the wtfos i was able to reset that. and i jist wanted to clarify, at this point, with my device being rooted, no matter what firmware update i do the device will stay rooted and i will be able to reinstall the wtfos is that correct?

You may have to still go through the rooting process again when re-installing, but once you've rooted on the correct version once it will always works in the future regardless of currently installed FW version.
