### ISSUE TITLE
googlesv2 temperature - WTFOS

### ISSUE THREAD

**Issue by Gui123Bovo** [fpv-wtf/wtfos-configurator#406]
### Device

Goggles V2

### Operating System (Including version)

windows 10 homesingle- 10.0.19045

### Browser

chrome

### Trace ID (bottom left of the configurator screen)

v2.2.1 - Trace ID: 4e441e79-39a3-403b-9982-770a2f82c9ac

### Describe the issue

Incorrect temperature value shown in WTFOS - home guide.

![image](https://github.com/fpv-wtf/wtfos-configurator/assets/144503024/a8859ace-92a3-46c8-8ad5-3e1239ce7e1a)

**Comment by stylesuxx** [comment]
What makes you think that this is the incorrect temperature?

**Comment by j005u** [comment]
This is completely normal. 70 degrees is what the stock DJI firmware CPU fan curve is tuned to. wtfos does not change this.

Normal working temperature means max air temperature during use, not CPU temperature.

**Comment by Gui123Bovo** [comment]
Thanks for the explanation and response time! excellent job
