### ISSUE TITLE
Getting Artifacts along with OSD elements when using the OSD overlay tool

### ISSUE THREAD

**Issue by preisedj** [fpv-wtf/wtfos-configurator#407]
### Device

Goggles V2

### Operating System (Including version)

Windows 11

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

v2.2.1 - Trace ID: eb79149b-edb4-4b7f-bf84-247f036a911b

### Describe the issue

OSD shows perfectly in Goggles using INAV and Ardupilot.  When I use the overlay too in post processing, I get strange artifacts along with some of the OSD elements only. I've tried different fonts with the same results.

**Comment by j005u** [comment]
Looking at the video you posted on another issue, I'm pretty sure those artifacts are parts of the Betaflight logo.

Please double check that you're using the font file with the correct names, for example [font_inav_hd.bin](https://github.com/fpv-wtf/msp-osd/blob/main/fonts/font_inav_hd.bin) and [font_inav_hd_2.bin](https://github.com/fpv-wtf/msp-osd/blob/main/fonts/font_inav_hd_2.bin).
