### ISSUE TITLE
osd overwrite not working today

### ISSUE THREAD

**Issue by Sinansenfpv** [fpv-wtf/wtfos-configurator#430]
### Device

Goggles V1

### Operating System (Including version)

win10

### Browser

goggle

### Trace ID (bottom left of the configurator screen)

v2.3.0 - Trace ID: 53500682-0a94-4532-8815-85e62f6b7ea7

### Describe the issue

Today, the osd combiner stopped working. The glasses video and osd file are correct. The processing message appears, but the screen just waits without showing the video. I did not change the font etc. The system I use all the time. Thank you

**Comment by j005u** [comment]
Please try the new development version at https://develop.fpv.wtf/osd-overlay and let us know if the issue is fixed for you.

**Comment by Sinansenfpv** [comment]
I try but not working.
I always used the site https://fpv.wtf/osd-overlay. But this site stopped
doing osd about 3 weeks ago
The site https://develop.fpv.wtf/osd-overlay does not work either.
but I found an old version that works.
https://knifa-develop.fpv.wtf/osd-overlay
This site works. I just need to enter the fonts manually.
I expect positive news from you for the new version of the site.
Thank you.
Sinan

Joonas Trussmann ***@***.***>, 27 Kas 2024 Çar, 22:13
tarihinde şunu yazdı:

**Comment by jesuslg123** [comment]
Hi, is there any way you could share with us one of the files that are failing to render? This may help us to research the issue.

**Comment by Sinansenfpv** [comment]
I am sending you the sample file link that I just recorded.
https://drive.google.com/drive/folders/1CB7FteEVVmFwzG9hv9rHl5J-BCs2Gbtp?usp=sharing
 Thank you for your interest. Have a good day.
Sinan Sen


jesuslg123 ***@***.***>, 28 Kas 2024 Per, 02:35 tarihinde
şunu yazdı:

**Comment by j005u** [comment]
We found a 2nd issue and fixed it. Please try https://develop.fpv.wtf/osd-overlay again.

**Comment by Sinansenfpv** [comment]
https://develop.fpv.wtf/osd-overlay
https://fpv.wtf/osd-overlay
All started working normally. Thank you for your interest. Have a nice day.
Sinan Sen

Joonas Trussmann ***@***.***>, 28 Kas 2024 Per, 11:58
tarihinde şunu yazdı:

**Comment by j005u** [comment]
Awesome. Closing this issue, please re-open if needed.
