### ISSUE TITLE
OSD Overlay still not working (Nov 20 2024)

### ISSUE THREAD

**Issue by MartinovEm** [fpv-wtf/wtfos-configurator#432]
### Device

Goggles V1

### Operating System (Including version)

Windows 10

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

e2c8dc6e-c9e2-4cba-9424-68c4551bc240

### Describe the issue

Still not working. Hope you guys will solve the problem soon and make announcement in Discord. I have many videos of crashes that should be overlaid :D

**Comment by j005u** [comment]
Please try the new development version at https://develop.fpv.wtf/osd-overlay and let us know if the issue is fixed for you.

**Comment by MartinovEm** [comment]
> Please try the new development version at https://develop.fpv.wtf/osd-overlay and let us know if the issue is fixed for you.

Hi,
Tried it, but unfortunately it doesn't work for me. I tried it on Chrome and IE and waited for more than 8-10 min but didn't work. I do appreciate your effort on that issue and I believe you could be able to solve it soon. Don't hesitate to ask me trying again next time! Good luck!

**Comment by jesuslg123** [comment]
Hi, is there any way you could share with us one of the files that are failing to render?

**Comment by MartinovEm** [comment]
Sure! Where to send them (vid+osd+sub files)?

**Comment by jesuslg123** [comment]
You can maybe upload to [wetransfer](https://wetransfer.com/) and paste the link?

**Comment by MartinovEm** [comment]
Yeah, but I need an email of the recipient.

**Comment by j005u** [comment]
We found a 2nd issue and fixed it. Please try https://develop.fpv.wtf/osd-overlay again.

**Comment by MartinovEm** [comment]
Kaboom - it works! :)) So everytime I'm gonna use OSD Overlay, I have to
use those fonts?

На чт, 28.11.2024 г. в 10:57 Joonas Trussmann ***@***.***>
написа:

**Comment by j005u** [comment]
If you mean Sneaky's font set that is now default in msp-osd and the overlay tool then no - you can always supply your own in the overlay tool.

**Comment by MartinovEm** [comment]
I've never uploaded Fonts before the issue occurred. Now tried with and
without the fonts you sent me - it works well in both cases.

На чт, 28.11.2024 г. в 11:18 Joonas Trussmann ***@***.***>
написа:

**Comment by jesuslg123** [comment]
Please check also without adding the forms, using the default ones. It should work too

**Comment by MartinovEm** [comment]
Already did it - works fine on the dev and original URL

**Comment by j005u** [comment]
Awesome. Closing this issue, please re-open if needed.
