### ISSUE TITLE
Add rooting, wtfos install and package installa events to GA

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#54]
We should add events to track (both successful and failed) rooting, wtfos and individual package install events. Package installs should also include the package, so we could track package popularity.

Adding the active device to the GA context would also not be a bad idea, so we can observe Goggles vs Air Side rooting.

**Comment by j005u** [comment]
Could we prioritize this one?

Reasoning: I want to make sure we have 10-20 successful installs before we @everyone in Discord and it goes on YT etc. Failure rate is also important here.

**Comment by stylesuxx** [comment]
Sure - did you create the events in GA or should I?

**Comment by j005u** [comment]
I didn't. Does GA4 need you to pre-create events? It used to be that you just define it in code.

In any case, go ahead.

**Comment by stylesuxx** [comment]
Yeah, GA4 does things very differently than UA. I just checked - I don't think I have an invitation to GTM, where I would need to set up those events...

**Comment by j005u** [comment]
We can also leave this to later, but while you're at it could we also add router integration so pageviews are tracked  properly?

**Comment by j005u** [comment]
@stylesuxx thanks, I can't think of anything else right now.
