### ISSUE TITLE
Link to a packages Readme

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#66]
I think the most efficient way would be to add a link to the Readme via description field in the control file - this would allow use to easily add the link in the configurator without any overhead.

```
Description: Something, something, bla... Project Link: https://here.we.go
```

We could then easily parse for `Project Link: (.*)`. Solution is a bit of a hack, but the easiest way to get the needed information.

@j005u what do you think about this solution?

**Comment by j005u** [comment]
I don't like the idea of using the description field for structured metadata at all.

Did the Homepage property not pan out? In that case how about we just detect any links in the package description and make them clickable.

I think with the upcoming package configuration interface we're essentially going to have to figure out a way of extending package metadata (the desired config) anyway, so if we need that for the README links then we might as well do it properly.

**Comment by stylesuxx** [comment]
> I don't like the idea of using the description field for structured metadata at all.

Yeah, me neither - it's just the easiest way to get it into the package listing.

> Did the Homepage property not pan out? In that case how about we just detect any links in the package description and make them clickable.

No, because it does not show up when listing the packages.

> I think with the upcoming package configuration interface we're essentially going to have to figure out a way of extending package metadata (the desired config) anyway, so if we need that for the README links then we might as well do it properly. I'm still keen on eventually rendering the README markdown in an embedded fashion, like a lot of other extension management interfaces tend to do.

I think it is easy to do on an individual basis - so when we have a detail view per package we could easily show all the needed information. Maybe I was just to keen to have this information in the package list...

**Comment by j005u** [comment]
If we want to solve READMEs quickly then we could just take the approach of making any link in the description clickable.

I would also like to see this info in the listing. In fact, even if we are to implement a detailed view for packages, it'd still need to know whether there is a detailed view to expand into.

How about we just replace `opkg list` with:
```
pkgs = $(opkg list)
#we need to store the output because if we go line by line while opkg list is running opkg info fails due to package index lock
echo $pkgs | \
while read i
do
  opkg info $(echo "${i% - * - *}")
done
```
I realize it's not extremely optimal, but that takes about 3 seconds to execute on my Goggles, which I'm completely fine with.

If we ever get to for example the package.yaml I described in the other issue then we can just replace opkg info with cat /path/to/opkg/index/$i-package.yaml.

**Comment by j005u** [comment]
Making a note here that the same approach should work, but using cat /path/to/control/file instead of opkg info, to be able to fetch fields opkg doesn't expose.

**Comment by stylesuxx** [comment]
Yes, but for this the package needs to already be installed.

**Comment by j005u** [comment]
Good point. I was thinking about the control file, but you are entirely right.

The index only has very limited control data afaik, definitely not arbitary fields, at least not unless we change some things around? Correct me if I'm wrong.

**Comment by stylesuxx** [comment]
Yeah, I will try that out later today, it might be simpler to inject more stuff into the index though. I'll post an update once I know for sure.

**Comment by stylesuxx** [comment]
Alright, so there are a couple fields we could use(without modification to the tooling) that end up in the _Package_ file:
* **HomePage**: We already use this for linking to the readme (at least with some packages), so this I can technically implement any time into the configurator
* **OE**: No clue what this is for, but it ends up in the package file

AND - the most awesome thing: The *-f* flag when generating the Package file - it will include user defined fields:

```
Package: test-package
Version: 0.0.1
Architecture: armv7-3.2
Maintainer: Your Name <user@example.com>
MD5Sum: e207efa917ab94f57813af3f0c5881f2
Size: 754
Filename: test-package_0.0.1_armv7-3.2.ipk
Description: This is just a test package
OE: Oe comes here
Readme: Readme_
Foo: Bar
Font: true
Json: {"key": "value", "key_1": ["item 1", "item 2"]}
Previews: ["url_1", "url_2"]
```

This concludes, we can stuff the Package file full with whatever information we want

**Comment by stylesuxx** [comment]
Closing this, link to Homepage if set in control files is now being displayed in the package list.
Everything else is discussed in other issues anyway.
