### ISSUE TITLE
Add manual retry to v2 goggles rooting flow

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#75]
It appears the change in retry mechanism didn't do the trick and people are still ending up with failures (GA suggests so as well).

I guess we should change the process where if the step under question fails we ask the user to manually power cycle the goggles ( and inform them it may take a few tries) and then wait for the goggles to show up again on serial before attempting to resume.

**Comment by stylesuxx** [comment]
Also see #81 

I now added a prompt to manually power-cycle the device when step 3 fails - once the device comes back online - rooting continues from step 2.
