### ISSUE TITLE
Intelligent handling of multiple tabs

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#91]
We could use the Broadcast Channel API to detect if other tabs are connected to the current adb device: https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

Ideally, new tabs ask the old tab to disconnect, with an option to resume connection once one returns to a tab that has previously been terminated. However this may be a bad idea when some operation is currently already in progress and would need locks for that purpose.

**Comment by stylesuxx** [comment]
This is looking very interesting, thank you. I think in a first step I could implement a notification that it is connected in a different tab already not sure about disconnecting old tab and resuming in the new one. If we want this, I should implement the apps state more permanently, maybe keeping it in the local storage.
