### ISSUE TITLE
WFTOS broken by forget unplug the batterry.

### ISSUE THREAD

**Issue by viettrungphan** [fpv-wtf/wtfos-configurator#92]
Step to reproduce.

1. Goggles V1. Fw.6006
2. Keep power rooted Goggles until the battery is dead (4s Lipo)
3. Connect the goggles to Configurator.
4. Only CLI and Install WTFOS enabled. The package and Startup tabs are no longer available.
5. Try to reroot and Install WTFOS but no luck.

```bash
root@pigeon_wm150_gls:/ # dinitctl list
/system/bin/sh: dinitctl: not found
127|root@pigeon_wm150_gls:/ # opkg list-installed
/system/bin/sh: opkg: not found
127|root@pigeon_wm150_gls:/ # df /blackbox/
Filesystem               Size     Used     Free   Blksize
/blackbox/               1.5G   715.8M   796.1M   4096
root@pigeon_wm150_gls:/ # df //blackbox/opt/bin/opkg list-installed
Filesystem               Size     Used     Free   Blksize
//blackbox/opt/bin/opkg: No such file or directory
list-installed: No such file or directory
1|root@pigeon_wm150_gls:/ # /blackbox/opt/bin/opkg list-installed
/system/bin/sh: /blackbox/opt/bin/opkg: not found
127|root@pigeon_wm150_gls:/ # unrd
slot_1.status_active            1
slot_1.status_bootable          1
slot_2.status_active            0
slot_2.status_bootable          1
slot_2.status_successful                1
HW_VER          03.05.00
dji.build.version               10.02.11.13
wipe_counter            0
crash_counter           0
slot_1.status_successful                1 
opkg install --force-reinstall dinit
/system/bin/sh: opkg: not found

```

**Comment by stylesuxx** [comment]
For me this seems as if the slot where WTFOS was installed got currupted. Pinging @j005u - you did debug such a case a couple of weeks ago, no? Could you give some insight maybe?

**Comment by j005u** [comment]
Yup, it's #87.

In this case it should be solvable by simply switching to slot 2. However the problem will come back if the battery ever drains again. I'm going to re-create the situation on my Goggles and figure out a proper cleanup procedure.

**Comment by j005u** [comment]
See here: https://github.com/fpv-wtf/margerine/wiki/Troubleshooting#wtfos-install-stuck-in-a-loop

**Comment by stylesuxx** [comment]
This should now be handled by the healthchecks automatically, closing down here. Feel free to re-open if issue persists.
