### ISSUE TITLE
Cannot install WTFOS on Caddx Vista

### ISSUE THREAD

**Issue by dacan2810** [fpv-wtf/wtfos-configurator#93]
![image](https://user-images.githubusercontent.com/20985840/183238369-5bfe89cf-856c-4d65-a644-784be02a6faf.png)
This error console happened when i  try to install wtfos
it  just show installing wtfos then reboot. 
after that it show cannot connect.
Now a cannot connect to DJI assistant.
![image](https://user-images.githubusercontent.com/20985840/183238474-7a31ed98-e80b-405c-b7e7-9137cbf39a19.png)
![image](https://user-images.githubusercontent.com/20985840/183238479-f03873b9-ff4c-483d-87d9-ddd078f9a0a0.png)
video
https://www.youtube.com/watch?v=8BWKEflgPPw&t=1s

**Comment by Ben-Stevenss** [comment]
Exactly on this point

https://user-images.githubusercontent.com/20985840/183238474-7a31ed98-e80b-405c-b7e7-9137cbf39a19.png

It says rebooting and loops

**Comment by dacan2810** [comment]
> Exactly on this point
> 
> https://user-images.githubusercontent.com/20985840/183238474-7a31ed98-e80b-405c-b7e7-9137cbf39a19.png
> 
> It says rebooting and loops

i think it a bug of configurator. waiting for some one to confirm :D

**Comment by j005u** [comment]
Ignore the CORS errors, they are normal.

This is a known issue: https://github.com/fpv-wtf/wtfos-configurator/issues/87

Please wait for us to finish the fix.
