### ISSUE TITLE
Detect installed FW version during root

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#94]
It would be nice if root could check the current FW version and inform the user if they have the wrong version.

Documenting the required DUML command here: https://b3yond.d3vl.com/duml/#551604fc2a1f640040004f0100000000e80300006c58

The command allows us to fetch the .cfg.sig file associated with the current firmware in chunks by varying the payload.
```
01 00 00 00 00 e8 03 00 00
01 00 01 00 00 e8 03 00 00
01 00 02 00 00 e8 03 00 00
...
```
The first 9 bytes of the response are a payload header with 7th byte telling us how many chunks remain until the end of the file.

```
00 00 01 00 00 00 04 00 00
00 00 01 00 00 00 03 00 00
00 00 01 00 00 00 02 00 00
...
```

The beginning of the .cfg.sig file is an IM*H archive, however we can ignore this and seek in the stream until we find an `<?xml` opening tag for the xml contents, build a string until a 0 byte in the stream and then use a regexp to find the version in the file, eg. `version="01.00.0606"`.

**Comment by stylesuxx** [comment]
Firmware is now being detected (or at least an attempt is made) during step 1 of the rooting process.

Since this does not seem to work reliably (eg.: On my V2 goggles - although the file is available - the DUML does not return the file) no actual check is implemented right now.

We could add a check for the case that a version is being detected. If no version is being detected, we just continue to attempt to root.

**Comment by j005u** [comment]
I had a funny feeling about the issue on V2 Goggles and getting back unknown, went back and did some digging with packet capture.

The assistant users DUML receiver type 31 and index 0 (making for 3100), but on V2s the configurator uses receiver type 28 and index 5 instead (making for 2805).

So, if we query both of these we should have a _much_ more reliable way of detecting versions. However there are still cases where this can return a 0 response and in such cases the best we can do is proceed and catch the e3 for the OTA duml command.

Sorry I missed this the first time.

Also created this page: https://github.com/fpv-wtf/wtfos/wiki/Supported-firmware-versions
