### ISSUE TITLE
V2 goggle step5 skipped

### ISSUE THREAD

**Issue by kiufpv** [fpv-wtf/wtfos-configurator#95]
Hello when i try to root my v2 goggles it says step 5 skipped and it dosent show up on the coms tab, only in the root menu it shows up.
rooting works fine with air unites

![Bild_2022-08-11_000359938](https://user-images.githubusercontent.com/111022716/184028458-46ff8f9e-d928-4184-a731-c3b079638ec0.png)

**Comment by j005u** [comment]
There's a known issue at the moment in the configurator where rooting fails (even though it reports success) for some combination of host PCs and devices that we're trying to figure out.

If you can't wait for us to have solved it and are handy with the CLI you can root with [margerine ](https://github.com/fpv-wtf/margerine) and then proceed back to the configurator to install wtfos.

**Comment by kiufpv** [comment]
i fixed it by trying it on a different pc

**Comment by stylesuxx** [comment]
This should be resolved with the latest release - feel free to re-open if problem persists.
