### ISSUE TITLE
"ERROR: Failed installing WTFOS" - does not show stderr

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos-configurator#96]
When the wtfos postinst scripts fail, they do not show output on the screen, according to a user I've been debugging.

Is this the case? Can we improve it?

**Comment by stylesuxx** [comment]
It is being logged to the console. I could add a component "Error Log" to which I append the last output in case of an error.

**Comment by j005u** [comment]
Right, I didn't even realize to check in console in this case.

I think if install fails with an error, the users is going to come and ask for help likely anyway, so we might as well show them the error message.

**Comment by stylesuxx** [comment]
In this case I will add the output to the general log
